#!/usr/bin/env python3
"""Build the complete banked engine, renderer, loader and preload package."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import subprocess
from pathlib import Path

import bank_game

PROJECT = Path(__file__).resolve().parents[1]


def configuration(build: Path, banks: Path, overlay_run: int = 0xE000) -> str:
    """Share lower CPU addresses between the two explicitly swapped images."""
    cfg = (PROJECT / "src/doom.cfg").read_text()
    # Move the shared path/view scratch out of the posted HGR window without
    # changing the arena capacity: its ordinary BSS reservation also shrinks.
    cfg = cfg.replace('start = $0200, size = $B600, type = rw;',
                      'start = $0200, size = $B180, type = rw;')
    cfg = cfg.replace('    # the loader\n',
                      '    AMEMSTORE: file = "%OAMEM.BIN", start = $B800, size = $0300, type = ro;\n'
                      f'    AMEMCOPYRUN: file = "", start = ${overlay_run:04X}, size = $0100, type = rw;\n'
                      f'    AMEMPROBERUN: file = "", start = ${overlay_run:04X}, size = $0100, type = rw;\n'
                      f'    AMEMFILLRUN: file = "", start = ${overlay_run:04X}, size = $0100, type = rw;\n'
                      '    GZPMEM: file = "", start = $0040, size = $0008, type = rw;\n'
                      '    ISCRATCH: file = "", start = $B380, size = $0480, type = rw, define = yes;\n'
                      '    TABLES: file = "%OGAME.TABLES", start = $0200, size = $BDF0, type = ro;\n'
                      '    INFO: file = "%OGAME.INFO", start = $6000, size = $1000, type = ro;\n'
                      + (banks / "banks-memory.cfg").read_text() + '\n    # the loader\n')
    cfg = cfg.replace('    GZP:       load = KZP,', '    GZP:       load = GZPMEM,')
    cfg = cfg.replace('    GZP:       load = GZPMEM,',
                      '    RZP:       load = KZP, type = zp, define = yes;\n'
                      '    GZP:       load = GZPMEM,')
    cfg = cfg.replace('    STARTUP:  ',
                      '    AMEMCOPY: load = AMEMSTORE, run = AMEMCOPYRUN, type = rw, define = yes;\n'
                      '    AMEMPROBE: load = AMEMSTORE, run = AMEMPROBERUN, type = rw, define = yes;\n'
                      '    AMEMFILL: load = AMEMSTORE, run = AMEMFILLRUN, type = rw, define = yes;\n'
                      '    GBSTUBS: load = GAME, type = ro;\n'
                      '    GBANKCODE: load = GAME, type = rw;\n'
                      '    STARTUP:  ')
    cfg = cfg.replace('    GFAR:      load = GAME,', '    GFAR:      load = TABLES,')
    cfg = cfg.replace('    GOVL:      load = GAME,', '    GOVL:      load = TABLES,')
    cfg = cfg.replace('    INIT:     ',
                      '    GINFO: load = INFO, type = ro;\n'
                      '    GINPUT: load = GAME, type = bss;\n'
                      '    GBANKBSS: load = GAME, type = bss, define = yes;\n'
                      '    GINTERCEPTS: load = ISCRATCH, type = bss, define = yes;\n'
                      + (banks / "banks-segments.cfg").read_text()
                      + '    INIT:     ')
    return '# Generated by build_banked.py from src/doom.cfg.\n' + cfg


def preload(build: Path, inventory: dict) -> bytes:
    # Base auxiliary lower RAM holds the staged renderer. Its LC code must
    # be staged elsewhere until the final, post-ProDOS installation step.
    # The loader transfers it into auxiliary LC after its final ProDOS call.
    segments = [(inventory["code_staging"][str(bank)], 0x0200,
                 (build / f"GBANK{bank}.BIN").read_bytes())
                for bank in inventory["banks"].values()]
    segments.extend([(127, 0x0200, (build / "GAME.TABLES").read_bytes()),
                     (1, 0x6000, (build / "GAME.INFO").read_bytes()),
                     (122, 0xB800, (build / "AMEM.BIN").read_bytes())])
    header = bytearray(b"A2DM\x01" + bytes([len(segments)]) + b"\0\0")
    for bank, address, blob in segments:
        if not blob or address + len(blob) > 0xC000:
            raise ValueError(f"invalid preload segment {bank}:{address:04x}/{len(blob)}")
        header.extend(struct.pack("<BHH", bank, address, len(blob)))
    if len(header) > 256:
        raise ValueError("too many code-bank segments")
    return bytes(header).ljust(256, b"\0") + b"".join(s[2] for s in segments)


def build(args) -> None:
    video_hz = getattr(args, "video_hz", 60)
    if video_hz not in (50, 60):
        raise ValueError("video_hz must be 50 or 60")
    out, data = args.build.resolve(), args.data.resolve()
    out.mkdir(parents=True, exist_ok=True)
    banks = out / "banks"
    # A zero field is patched after linking, so the runtime tag identifies
    # the actual program bytes (including compiler/linker differences).
    (out / "profile-build.inc").write_text(
        ".macro PROFILE_BUILD_BYTES\n.byte 0,0,0,0\n.endmacro\n")
    prepared = argparse.Namespace(source=args.source.resolve(), data=data, out=banks,
                                  first_bank=96, ca65=args.ca65, cc65=args.cc65,
                                  ld65=args.ld65, standalone=False,
                                  control_bank=args.control_bank, video_hz=video_hz)
    inventory = bank_game.prepare(prepared)
    nums = list(inventory["banks"].values())
    staging = [inventory["code_staging"][str(bank)] for bank in nums]
    if len(set(nums)) != len(nums) or any(bank != 0 and not 96 <= bank < 122 for bank in nums):
        raise ValueError("code banks must be distinct base auxiliary or extended banks 96..121")
    # Remove only stale outputs of this builder when switching the placement
    # option in an existing build directory. The link checker rejects others.
    for stale in (out / f"GBANK{bank}.BIN" for bank in (0, 100) if bank not in nums):
        stale.unlink(missing_ok=True)
    (out / "banklayout.inc").write_text(
        f"CODE_BANK_COUNT = {len(nums)}\n"
        ".macro CODE_BANK_SOURCES\n.byte " + ",".join(map(str, staging)) + "\n.endmacro\n"
        ".macro CODE_BANK_TARGETS\n.byte " + ",".join(map(str, nums)) + "\n.endmacro\n")
    subprocess.run([args.python, str(PROJECT / "tools/gen_tables.py"), "--out", str(out)],
                   check=True)
    objects = list(inventory["objects"])
    sources = [PROJECT / "src/kernel" / f"{name}.s" for name in
               ("kstart", "space", "far", "video", "input", "frame", "loader", "gamebanks", "profile", "amem")]
    sources += sorted(p for p in (PROJECT / "src/render").glob("*.s") if p.stem != "stub")
    sources += [out / "render/tables.s"]
    for source in sources:
        obj = out / source.parent.name / (source.stem + ".o")
        obj.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run([args.ca65, "--cpu", "65c02", "-g", "-D", "BANKED_GAME",
                        "-D", f"VIDEO_HZ={video_hz}",
                        *(["-D", "PROFILE"] if args.profile else []),
                        "-I", str(PROJECT / "src/kernel"), "-I", str(PROJECT / "src/render"),
                        "-I", str(data), "-I", str(out), "-o", str(obj), str(source)],
                       check=True)
        objects.append(str(obj))
    cfg = out / "doom-banked.cfg"
    cfg.write_text(configuration(out, banks))
    link = [args.ld65, "-C", str(cfg), "-m", str(out / "doom.map"),
            "-Ln", str(out / "doom.lbl"), "--dbgfile", str(out / "doom.dbg"),
            "-o", str(out) + "/", *objects, "none.lib"]
    subprocess.run(link, check=True)
    # ld65 requires constant MEMORY starts. Overlay placement does not
    # change any resident segment's size; resolve kbuf from the first link.
    match = re.search(r"^al\s+([0-9A-Fa-f]+)\s+\.kbuf$",
                      (out / "doom.lbl").read_text(), re.M)
    if match is None:
        raise ValueError("resident kbuf is missing")
    cfg.write_text(configuration(out, banks, int(match[1], 16)))
    subprocess.run(link, check=True)
    (out / "DOOM.BANKS").write_bytes(preload(out, inventory))
    metadata = {"format": 1, "banks": inventory["banks"], "game_home": 125,
                "default_video_hz": video_hz,
                "code_staging": inventory["code_staging"],
                "render_home": 122, "packet_bank": 124, "packet_address": 0x0200,
                "tables_bank": 127, "info_bank": 1, "preload_file": "DOOM.BANKS",
                "memory_api_optional": True}
    (out / "banked.json").write_text(json.dumps(metadata, indent=2) + "\n")
    if args.profile:
        filenames = ["DOOM.SYSTEM", "LC.BIN", "GAME.BIN", "RENDER.BIN", "DOOM.BANKS"]
        digest = hashlib.sha256((data / "manifest.json").read_bytes())
        for name in filenames:
            digest.update(name.encode())
            digest.update((out / name).read_bytes())
        tag = digest.digest()[:4]
        labels = dict((name, int(value, 16)) for value, name in re.findall(
            r"^al\s+([0-9A-Fa-f]+)\s+\.([^\s]+)", (out / "doom.lbl").read_text(), re.M))
        offset = labels["profile_snapshot"] + 6 - 0x0200
        game_image = bytearray((out / "GAME.BIN").read_bytes())
        if game_image[offset-4:offset] != b"DPR1" or game_image[offset:offset+4] != bytes(4):
            raise ValueError("profiling runtime identity field moved or is not zero-initialized")
        game_image[offset:offset+4] = tag
        (out / "GAME.BIN").write_bytes(game_image)
        names = ["idle", "game_copy", "game_tics", "packet", "debug",
                 "render_copy", "render_setup", "walls", "planes", "things",
                 "masked", "present_wait", "blit"]
        fields = {name: {"offset": offset, "width": width} for name, offset, width in
                  [("sequence", 0, 2), ("magic", 2, 4), ("build_id", 6, 4),
                   ("clock", 10, 2), ("frames", 12, 2), ("tics", 14, 2), ("hz", 16, 1)]}
        fields.update({name: {"offset": 18 + i*2, "width": 2} for i, name in enumerate(names)})
        profile = {"format": 1, "address": 0x1A000, "size": 44, "magic": "DPR1",
                   "memory_api_optional": True,
                   "memory_api": {"address_space": "main_shadow",
                                  "available_address": labels["amem_available"],
                                  "status_address": labels["amem_status"]},
                   "default_video_hz": video_hz,
                   "build_id": tag.hex(), "fields": fields,
                   "stages": [{"name": name, "field": name} for name in names],
                   "clock_source": "mouse VBL", "publish_vbls": 60,
                   "sampling_caveat": "Periodic VBL samples can phase-lock; shares are coarse, not phase timings.",
                   "images": {name: hashlib.sha256((out / name).read_bytes()).hexdigest()
                              for name in filenames}}
        (out / "profile.json").write_text(json.dumps(profile, indent=2) + "\n")
    else:
        (out / "profile.json").unlink(missing_ok=True)
    print(f"Complete banked engine linked: {out}")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--profile", action="store_true", help="hardware VBL phase sampler")
    p.add_argument("--video-hz", type=int, choices=(50, 60), default=60,
                   help="initial video rate for the tic scheduler and debug readout")
    p.add_argument("--control-bank", type=int, choices=(0, 100), default=0,
                   help="control LC bank: base auxiliary 0, or extended 100 for comparison")
    p.add_argument("--build", type=Path, default=PROJECT / "build")
    p.add_argument("--data", type=Path, default=PROJECT / "build/data")
    p.add_argument("--source", type=Path, default=PROJECT / "src/game")
    p.add_argument("--ca65", default="ca65")
    p.add_argument("--cc65", default="cc65")
    p.add_argument("--ld65", default="ld65")
    p.add_argument("--python", default="python3")
    build(p.parse_args())


if __name__ == "__main__":
    main()
