#!/usr/bin/env python3
"""Write the 6502 renderer's tables for ca65 (DESIGN.md section 7).

    python3 tools/gen_tables.py [--out build]      -> build/render/tables.inc, tables.s

Every table the renderer (src/render/) reads is built by tools/refrender.py
(class Tables), the renderer's bit-exact specification, and written here
unchanged, so the assembly and the reference use the same numbers by
construction. Nothing here computes a table itself.

tables.inc  the renderer's constants (view, angles, fixed-point widths,
            lighting, per-frame limits) and a .global for every table
            label; include it from any render source (the Makefile puts
            the build directory on the include path: .include
            "render/tables.inc").
tables.s    the tables, in named segments: RTEXTDATA (main $0400-$0BFF,
            read-only: small per-column and per-row tables) and RRODATA
            (main, the rest). Multi-byte tables are split into one byte
            plane per table (NAME_lo, NAME_hi, NAME_mid...) so that an
            indexed load reads one byte of entry X or Y directly.

The sizes are printed and checked against the segments' room.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import refrender as R  # noqa: E402

PROJECT = Path(__file__).resolve().parents[1]
RTEXT_SIZE = 0x0800             # $0400-$0BFF (src/doom.cfg RTEXT)


def planes(values, nbytes, signed=False):
    """Split values into byte planes, least significant first."""
    out = []
    for k in range(nbytes):
        out.append([((v if not signed else v & ((1 << (8 * nbytes)) - 1)) >> (8 * k)) & 0xFF
                    for v in values])
    return out


class Emitter:
    def __init__(self):
        self.lines = []
        self.segment = None
        self.sizes = {}         # label -> (segment, bytes)
        self.labels = []

    def seg(self, name):
        if name != self.segment:
            self.lines.append(f'\n.segment "{name}"')
            self.segment = name

    def table(self, label, data, comment):
        self.lines.append(f"\n; {comment}")
        self.lines.append(f"{label}:")
        for i in range(0, len(data), 16):
            self.lines.append("        .byte   " + ",".join(f"${b:02X}" for b in data[i:i + 16]))
        self.sizes[label] = (self.segment, len(data))
        self.labels.append(label)

    def split(self, label, values, nbytes, comment, signed=False):
        names = ["lo", "hi"] if nbytes == 2 else ["lo", "mid", "hi"]
        for name, data in zip(names, planes(values, nbytes, signed)):
            self.table(f"{label}_{name}", data, f"{comment} ({name} byte)")


def build(outdir: Path):
    t = R.tables()
    e = Emitter()
    e.lines.append("; Doom for the Appletini -- the renderer's tables (generated by "
                   "tools/gen_tables.py\n; from tools/refrender.py; do not edit).")
    e.lines.append('\n.include "tables.inc"')
    e.lines.append(".import VIEWBUF")

    # small per-column / per-row tables: the read-only text-page area
    e.seg("RTEXTDATA")
    e.table("viewangletox", t.viewangletox,
            f"column of fine angle VATX_FIRST + i (clipped angles only), {len(t.viewangletox)}")
    e.split("xtoviewangle", t.xtoviewangle, 2, "BAM16 angle of each column's edge, 161")
    e.split("yslope", t.yslope, 2, "80 / |y - 41.5| in 8.8, per row")
    coladdr = [f"VIEWBUF + {R.VIEW_H} * {x}" for x in range(R.VIEW_W)]
    e.lines.append("\n; view buffer address of each column (lo byte)")
    e.lines.append("coladdr_lo:")
    for i in range(0, R.VIEW_W, 8):
        e.lines.append("        .lobytes " + ", ".join(coladdr[i:i + 8]))
    e.lines.append("coladdr_hi:")
    for i in range(0, R.VIEW_W, 8):
        e.lines.append("        .hibytes " + ", ".join(coladdr[i:i + 8]))
    e.sizes["coladdr_lo"] = ("RTEXTDATA", R.VIEW_W)
    e.sizes["coladdr_hi"] = ("RTEXTDATA", R.VIEW_W)
    e.labels += ["coladdr_lo", "coladdr_hi"]
    e.table("fuzzoffset", [v & 0xFF for v in t.fuzzoffset],
            "Doom's fuzz: +-1 row (signed byte), 50")

    e.seg("RRODATA")
    e.split("finesine", t.sine_q, 2, "sin(i * 2pi / 4096) Q14, i = 0..1024 (quarter wave)")
    e.split("tantoangle", t.tantoangle, 2, "BAM16 of atan(i / 1024), i = 0..1024")
    e.split("finetangent", t.tan_pos, 3,
            "tan((i + 0.5) * 2pi / 4096), 12 fraction bits, fine index 1024 + i")
    e.split("recip", t.recip, 3, "2^31 / (m + 0.5), m = 256 + i: texels per pixel")
    e.split("distscale", t.distscale, 2, "1 / cos(column angle), Q14")
    e.table("scalelight", [k for row in t.scalelight for k in row],
            "colormap (0..15) by light level (16) x scale >> 11 (48)")
    e.table("zlight", [k for row in t.zlight for k in row],
            "colormap (0..15) by light level (16) x distance >> 8 (128)")
    e.split("mul_sqr", t.mul_sqr, 2, "i*i/4, i = 0..511 (quarter-square multiply)")
    e.split("mul_nsqr", t.mul_nsqr, 2, "(i-255)^2/4, i = 0..511")

    consts = [
        ("VIEW_W", R.VIEW_W), ("VIEW_H", R.VIEW_H), ("CENTERX", R.CENTERX),
        ("CENTERY", R.CENTERY), ("PROJ", R.PROJ), ("SUBBITS", R.SUBBITS),
        ("VIEWHEIGHT", R.VIEWHEIGHT),
        ("ANG45", R.ANG45), ("ANG90", R.ANG90), ("ANG180", R.ANG180), ("ANG270", R.ANG270),
        ("FINEANGLES", R.FINEANGLES), ("FINESHIFT", R.FINESHIFT), ("SINEBITS", R.SINEBITS),
        ("SLOPEBITS", R.SLOPEBITS), ("SLOPERANGE", R.SLOPERANGE), ("TANBITS", R.TANBITS),
        ("CLIPANGLE", t.clipangle), ("VATX_FIRST", t.vatx_first),
        ("VATX_COUNT", len(t.viewangletox)),
        ("HEIGHTBITS", R.HEIGHTBITS), ("SCALE_MIN", R.SCALE_MIN), ("SCALE_MAX", R.SCALE_MAX),
        ("RECIPBITS", R.RECIPBITS),
        ("LIGHTLEVELS", R.LIGHTLEVELS), ("LIGHTSEGSHIFT", R.LIGHTSEGSHIFT),
        ("MAXLIGHTSCALE", R.MAXLIGHTSCALE), ("LIGHTSCALESHIFT", R.LIGHTSCALESHIFT),
        ("MAXLIGHTZ", R.MAXLIGHTZ), ("LIGHTZSHIFT", R.LIGHTZSHIFT),
        ("FUZZ_COLORMAP", R.FUZZ_COLORMAP), ("FUZZTABLE", len(t.fuzzoffset)),
        ("MINZ", R.MINZ), ("BASEYCENTER", R.BASEYCENTER),
        ("MAXSOLIDSEGS", R.MAXSOLIDSEGS), ("MAXDRAWSEGS", R.MAXDRAWSEGS),
        ("MAXVISPLANES", R.MAXVISPLANES), ("MAXOPENINGS", R.MAXOPENINGS),
        ("MAXVISSPRITES", R.MAXVISSPRITES), ("MAXBSPDEPTH", R.MAXBSPDEPTH),
    ]
    inc = ["; Doom for the Appletini -- renderer constants and tables (generated by",
           "; tools/gen_tables.py from tools/refrender.py; do not edit). DESIGN.md 7.",
           "", ".ifndef TABLES_INC", "TABLES_INC = 1", ""]
    # kernel.inc defines some of these too (VIEW_W, VIEW_H): define each one
    # unless it exists, and then insist that it is the same number
    for name, value in consts:
        v = f"{value}" if value < 256 else f"${value:X}"
        inc.append(f".ifndef {name}\n{name:<16} = {v}\n.else\n"
                   f".assert {name} = {v}, error, \"{name} differs from tools/refrender.py\"\n.endif")
    inc.append("")
    for label in e.labels:
        inc.append(f".global {label}")
    inc += ["", ".endif", ""]

    rdir = outdir / "render"
    rdir.mkdir(parents=True, exist_ok=True)
    (rdir / "tables.inc").write_text("\n".join(inc))
    (rdir / "tables.s").write_text("\n".join(e.lines) + "\n")
    return e.sizes


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=str(PROJECT / "build"),
                    help="build directory; the files go to OUT/render/")
    ap.add_argument("-q", "--quiet", action="store_true")
    a = ap.parse_args(argv)
    sizes = build(Path(a.out))
    total = {}
    for label, (seg, n) in sizes.items():
        total[seg] = total.get(seg, 0) + n
    if total.get("RTEXTDATA", 0) > RTEXT_SIZE:
        print(f"gen_tables: RTEXTDATA tables take {total['RTEXTDATA']} > {RTEXT_SIZE} bytes",
              file=sys.stderr)
        return 1
    if not a.quiet:
        for label, (seg, n) in sizes.items():
            print(f"  {label:<18} {seg:<10} {n:6d}")
        print("gen_tables: " + ", ".join(f"{s} {n} bytes" for s, n in sorted(total.items()))
              + f" -> {Path(a.out) / 'render'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
