#!/usr/bin/env python3
"""The generated include of the channel logic (src/native/fx_chan.s;
sound track S4), a port of upstream's
S_StartSound, S_StartSound2, sameOrigin, getChannel, priority,
stopChannel, S_StopSound, S_UpdateSounds and S_AdjustSoundParams [R
build/upstream/src/iigs/s_sound65.s:177-670].

Usage:  python3 tools/sound/fxchan.py --inc OUT
            the priority table, the constants fx_chan.s reads from
            upstream's files and S_AdjustSoundParams' constants

Nothing of upstream's code is copied: the priority table is read from
upstream's sfxPriority lines [R s_sound65.s:1274-1285] and the constants
from its offsets.inc through tools/bridge/incfile.py, at build time.
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(ROOT / 'tools'))

from bridge import incfile  # noqa: E402

UPSTREAM = ROOT / 'build' / 'upstream' / 'src' / 'iigs'
SOUND_SRC = UPSTREAM / 's_sound65.s'
OFFSETS = UPSTREAM / 'offsets.inc'

STEREO_SWING = 96
CLIP_HI = 1200                  # S_CLIPPING_DIST >> FRACBITS
CLOSE_HI = 160                  # S_CLOSE_DIST >> FRACBITS
ATTENUATOR = CLIP_HI - CLOSE_HI
PICKUP_SOUND = 0x8000
LISTENER = 0xFFFE               # s2t_pos's handle of the listener


class ModelError(Exception):
    pass


# ---------------------------------------------------------------------------
# What is read from upstream's files
# ---------------------------------------------------------------------------

def priority_table(path: Path = SOUND_SRC) -> List[int]:
    """sfxPriority's bytes, in sfxenum_t order [R s_sound65.s:1274-1285]:
    the lines from the label to the next blank line."""
    lines = path.read_text().splitlines()
    out: List[int] = []
    on = False
    for line in lines:
        code = line.split(';', 1)[0]
        if code.startswith('sfxPriority:'):
            on = True
            code = code[len('sfxPriority:'):]
        elif on and not code.strip():
            break
        if not on:
            continue
        m = re.match(r'\s*\.byte\s+(.*)$', code)
        if not m:
            raise ModelError('sfxPriority: cannot read %r' % line)
        out += [int(v, 0) for v in m.group(1).split(',')]
    if not out:
        raise ModelError('no sfxPriority in %s' % path)
    return out


def constants() -> Dict[str, int]:
    c = incfile.as_dict(incfile.parse(OFFSETS))
    return {k: c[k] for k in ('CONST_SFX_OOF', 'CONST_SFX_NOWAY',
                              'CONST_NUMSFX', 'OFS_MO_X', 'OFS_MO_Y',
                              'OFS_MO_ANGLE', 'OFS_PL_MO')}


# ---------------------------------------------------------------------------
# The generated include of fx_chan.s
# ---------------------------------------------------------------------------

def inc_text() -> str:
    sys.path.insert(0, str(ROOT / 'tools'))
    from native import glayout as GL, llayout as LL, \
        s2layout as S  # noqa: E402
    c = constants()
    prio = priority_table()
    out = ['; Generated by tools/sound/fxchan.py --inc. Do not edit.',
           '; Read from upstream\'s files at',
           '; build time: the priority table [R s_sound65.s:1274-1285],',
           '; CONST_* of offsets.inc.', '']

    def eq(name, value, note=''):
        out.append('%-15s = $%04X%s' % (name, value,
                                        ('    ; ' + note) if note else ''))
    eq('FXC_GA', GL.GA_RANGE[0], 'the arguments (docs/GAME.md, glayout)')
    eq('FXC_GT', GL.GT_RANGE[0], 'the temporaries')
    eq('FXC_GAMEMAP', LL.G['G_GAMEMAP'], 'gamemap (llayout G_GAMEMAP)')
    eq('FXC_LISTENER', LISTENER, 's2t_pos\'s handle of the listener')
    eq('FXC_PICKUPHI', PICKUP_SOUND >> 8, 'PICKUP_SOUND\'s high byte')
    eq('FXC_OOF', c['CONST_SFX_OOF'])
    eq('FXC_NOWAY', c['CONST_SFX_NOWAY'])
    eq('FXC_NUMSFX', c['CONST_NUMSFX'])
    eq('FXC_CLIPHI', CLIP_HI)
    eq('FXC_CLOSEHI', CLOSE_HI)
    eq('FXC_ATTEN', ATTENUATOR)
    eq('FXC_SWING', STEREO_SWING)
    if len(prio) != c['CONST_NUMSFX']:
        raise ModelError('%d priorities for %d sounds' % (
            len(prio), c['CONST_NUMSFX']))
    out += ['', '.macro FXC_PRIORITIES']
    for k in range(0, len(prio), 8):
        out.append('        .byte %s' % ', '.join(
            '%d' % v for v in prio[k:k + 8]))
    out += ['.endmacro', '']
    return '\n'.join(out) + '\n'


def write_if_changed(path: Path, text: str) -> None:
    if path.exists() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text)
    tmp.replace(path)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--inc', type=Path)
    args = ap.parse_args(argv)
    if args.inc:
        write_if_changed(args.inc, inc_text())
        return 0
    ap.print_help()
    return 1


if __name__ == '__main__':
    sys.exit(main())
