#!/usr/bin/env python3
"""The effect player (src/sound/fx.s) on a2vm against its model
tools/sound/fxplay.py and S2's music player (milestone 11, part fxplay;
docs/m11-parts/fxplay.md).

Usage (from demos/doom_gs, after make -C src/native -f m11.mk part
P=fxplay):
  python3 tools/sound/fxrun65.py --cfg OUT      the test machine's ld65 map
  python3 tools/sound/fxrun65.py --checkpoint [--jobs N] [--quick]
  python3 tools/sound/fxrun65.py --cost [--jobs N]
  python3 tools/sound/fxrun65.py --timing [--jobs N]
  python3 tools/sound/fxrun65.py --planted [--jobs N]

The machine (build/native/m11/fxplay/fxt.*): src/sound/fxdrv.s and
fx_service in main memory at $0800; S2's player (build/sound65, read
only), pl_irq.s (pl_vbl the IRQ vector) and fx.s's card part at the
game's places (s2layout.py); the songs in RamWorks banks 1-13 at $1000;
SFX.1 in bank SFX (103) at $0200. a2vm runs it on the W65C02S with the
cost model on its clock (--cost-timed; the Doom profile f121+phasor+
window32 unless said), the AY log, --irq-bounds 00D8-01FF,C0A0-C0AF,
C400-C4FF,E000-FFFF (MEMORY_MAP.md rule 2), the lowest S in the handler,
and a write log of the effects' card state, the rings, S2's snd_playing
and the driver's drv_mark.

The oracle. The write log gives the time of each main-loop event (an
action, a frame's fx_service and snd_refill: drv_mark) and of fx_song's
steps (FX_HOLD, snd_playing); the AY log the time of each interrupt.
Taken in time order, the model runs each: an interrupt is S2's music
model (run65.RingPlayer, the song started by the latest snd_start) then
fxplay.FxPlayer.step(); an action is the driver's (fxdrv.s); a frame is
fx_service, then snd_refill. An interrupt may land inside a song's start
only (the hold test): there the model follows what the write log says
had happened (FX_HOLD set, the old song stopped, the new one playing).
Each interrupt's AY writes must equal the model's, write for write: the
music's (chips 0-2), then chip 3's. The main loop's writes (the chips'
resets, each song start's reset_chips) equal the model's between the
same interrupts (or, when an interrupt landed inside a song start, in
the same order over the run). At the end the four chips hold what the
model's writes leave; drv_qlog holds the model's fx_isplaying answers.

The write log also checks the publish order: every ring byte that a
store to V_WPOS publishes was written by the main loop after the voice's
previous publish (or its start), and the interrupt never writes a ring.

Every run is bounded (cycles, wall time, the logs' sizes) in a tempfile
directory under build/ that is deleted after it. Standard library only.
"""

import argparse
import bisect
import json
import shutil
import statistics
import struct
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Dict, List, NamedTuple, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE.parent / 'native'))

from a2vm import costs  # noqa: E402
from native import s2layout as S  # noqa: E402
from ref816 import bounded  # noqa: E402
from sound import fxplay, player, run65, tables  # noqa: E402

ROOT = HERE.parents[1]
BUILD = ROOT / 'build'
M11 = BUILD / 'native' / 'm11'
PART = M11 / 'fxplay'
SFX1 = M11 / 'fxconv' / 'SFX.1'
SOUND65 = BUILD / 'sound65'
SONGS = BUILD / 'sound'
CASES = M11 / 'cases'
A2VM = BUILD / 'a2vm' / 'a2vm'
SRC = ROOT / 'src' / 'sound'
NATIVE_SRC = ROOT / 'src' / 'native'

DRV_MAIN = 0x0800
DRVZP = 0x80
LC_LO = 0xE900
SFX_BANK = S.SFX
SFX_AT = fxplay.BANK_BASE
SONG_BANK0, SONG_AT = 1, 0x1000
IRQ_BOUNDS = '00D8-01FF,C0A0-C0AF,C400-C4FF,E000-FFFF'
PROFILE = 'f121+phasor+window32'        # the Doom profile (NATIVE.md 15.1)
RUN_TIMEOUT = 900.0
MAX_FILE = 256 << 20
WRITE_LOG_LIMIT = 3_000_000
JOBS = 2

SONG, SONGSTOP, START, STOP, VOLUME, GATE, STOPALL, QUERY, FRAME, \
    SERVICE = range(1, 11)
KINDS = {SONG: 'SONG', SONGSTOP: 'SONGSTOP', START: 'START', STOP: 'STOP',
         VOLUME: 'VOLUME', GATE: 'GATE', STOPALL: 'STOPALL', QUERY: 'QUERY',
         FRAME: 'FRAME', SERVICE: 'SERVICE'}
ACT_SIZE = 10
MAX_ACTIONS = 255
QLOG = 64
MARK_FRAME, MARK_REFILL = 0x80, 0x81
SONG_LOOP, SONG_NTSC = 0x01, 0x80
VOL_NEAR, VOL_MID, VOL_FAR = 127, 63, 6     # SOUNDS.hdv's 1, 2, 3
SEP_LEFT, SEP_CENTRE, SEP_RIGHT = 64, 128, 200


class RunError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# the ld65 map of the test machine
# ---------------------------------------------------------------------------

def cfg_text() -> str:
    card = {name: (lo, hi) for name, lo, hi in S.S2_CARD}

    def area(name, lo, hi, file, extra=''):
        return '    %-7s start = $%04X, size = $%04X, %sfile = %s;\n' % (
            name + ':', lo, hi - lo, extra, file)
    out = ('# Generated by tools/sound/fxrun65.py --cfg (part fxplay;\n'
           '# s2layout.py\'s places). Do not edit.\nMEMORY {\n')
    out += area('DRVZP', DRVZP, DRVZP + 0x40, '""', 'type = rw, ')
    out += area('SNDZP', S.ZP_MUSIC[0], S.ZP_FXRING[0], '""', 'type = rw, ')
    out += area('MAIN', DRV_MAIN, 0x2000, '"%O.main"', 'type = rw, ')
    for key, name in (('RING', 'the song ring and its mirror'),
                      ('LIST', 'the player\'s write lists'),
                      ('STATE', 'the player\'s state')):
        out += area(key, card[name][0], card[name][1], '""', 'type = rw, ')
    r = card['S2\'s code and tables']
    out += area('SND', r[0], r[1], '"%O.lc"', 'fill = yes, ')
    out += area('FXC', S.FX_CODE[0], S.FX_CODE[1], '"%O.lc"', 'fill = yes, ')
    out += area('REST', S.FX_CODE[1], 0xFFFA, '"%O.lc"', 'fill = yes, ')
    out += area('VEC', 0xFFFA, 0x10000, '"%O.lc"')
    out += '}\nSEGMENTS {\n'
    rows = [('SNDZP', 'SNDZP', 'type = zp'), ('DRVZP', 'DRVZP', 'type = zp'),
            ('DRVCODE', 'MAIN', 'type = rw'),
            ('S2CODE', 'MAIN', 'type = rw, define = yes'),
            ('DRVDATA', 'MAIN', 'type = rw'),
            ('SNDBOOT', 'MAIN', 'type = rw'),
            ('SNDRING', 'RING', 'type = bss, align = $100'),
            ('SNDLIST', 'LIST', 'type = bss'),
            ('SNDBSS', 'STATE', 'type = bss'),
            ('SNDCODE', 'SND', 'type = ro'),
            ('SNDRODATA', 'SND', 'type = ro'),
            ('FXCODE', 'FXC', 'type = ro, define = yes'),
            ('VECTORS', 'VEC', 'type = ro')]
    for name, load, extra in rows:
        out += '    %-10s load = %s, %s;\n' % (name + ':', load, extra)
    return out + '}\n'


# ---------------------------------------------------------------------------
# builds
# ---------------------------------------------------------------------------

def make(m11: Path = M11, fxsrc: Path = SRC) -> None:
    """make -f m11.mk part P=fxplay into m11, fx.s and fxdrv.s from
    fxsrc; fails on a warning."""
    result = bounded.run(['make', '-s', '-C', str(NATIVE_SRC), '-f', 'm11.mk',
                          'part', 'P=fxplay', 'M11=%s' % m11,
                          'ROOT=%s' % ROOT, 'FXSRC=%s' % fxsrc],
                         timeout=300, stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT, universal_newlines=True)
    if result.returncode:
        raise RunError('the build failed:\n' + result.stdout)
    if 'arning' in result.stdout:
        raise RunError('the build warns:\n' + result.stdout)


def have_build(part: Path = PART) -> bool:
    return (part / 'fxt.map').exists() and SFX1.exists() and A2VM.exists()


class Linked(NamedTuple):
    dir: Path
    labels: Dict[str, int]
    segments: Dict[str, Tuple[int, int]]
    main: bytes
    lc: bytes


def load(part: Path = PART) -> Linked:
    return Linked(part, run65.read_labels(part / 'fxt.lbl'),
                  run65.segments(part / 'fxt.map'),
                  (part / 'fxt.main').read_bytes(),
                  (part / 'fxt.lc').read_bytes())


def sizes(part: Path = PART) -> Dict[str, int]:
    """The card part, fx_service and FXCODE in all (with pl_vbl)."""
    text = (part / 'fxt.map').read_text()
    mods = text.split('Modules list:', 1)[1].split('Segment list:', 1)[0]
    out, module = {}, None
    for line in mods.splitlines():
        if line and not line.startswith(' '):
            module = Path(line.strip().rstrip(':')).stem
            continue
        f = line.split()
        if module and f and f[0] in ('FXCODE', 'S2CODE'):
            size = int(next(x for x in f if x.startswith('Size='))[5:], 16)
            out['%s:%s' % (module, f[0])] = size
    seg = run65.segments(part / 'fxt.map')
    out['FXCODE'] = seg['FXCODE'][1]
    out['FXC_ROOM'] = S.FX_CODE[1] - S.FX_CODE[0]
    data = 4 * fxplay.NREGS + 1                 # want, shadow, the list
    out['card_data'] = data
    out['card_code'] = out['fx-card:FXCODE'] - data
    return out


# ---------------------------------------------------------------------------
# the actions
# ---------------------------------------------------------------------------

class Act(NamedTuple):
    kind: int
    vbl: int
    args: Tuple[int, ...] = ()
    delay: int = 0

    def pack(self) -> bytes:
        a = tuple(self.args) + (0,) * (5 - len(self.args))
        return struct.pack('<BH5BH', self.kind, self.vbl, *a, self.delay)


def song(vbl, index=0, ntsc=False, loop=True, matt=0, delay=0):
    return Act(SONG, vbl, (SONG_BANK0 + index, SONG_AT & 0xFF, SONG_AT >> 8,
                           (SONG_LOOP if loop else 0) |
                           (SONG_NTSC if ntsc else 0), matt), delay)


def start(vbl, c, sound, vol=VOL_NEAR, sep=SEP_CENTRE):
    return Act(START, vbl, (c, sound, vol, sep))


def stop(vbl, c):
    return Act(STOP, vbl, (c,))


def volume(vbl, c, vol):
    return Act(VOLUME, vbl, (c, vol))


def other(kind, vbl, *args):
    return Act(kind, vbl, tuple(args))


class Setup(NamedTuple):
    actions: Tuple[Act, ...]
    seconds: float
    ntsc: bool = False
    songs: Tuple[bytes, ...] = ()
    probe: bool = False
    mb_only: bool = False
    count: bool = False             # drv_count: the time left, for the cost
    calibrate: bool = False
    gate: int = 3
    frame: int = 1
    profile: str = PROFILE
    bank: Optional[bytes] = None    # SFX.1 by default


# ---------------------------------------------------------------------------
# a run
# ---------------------------------------------------------------------------

class Write(NamedTuple):
    clock: int
    pc: int
    addr: int
    old: int
    new: int


class Result(NamedTuple):
    state: Dict[str, Any]
    main: List[List[Any]]           # run65.group's
    bursts: List[List[Any]]
    times: List[Tuple[int, int]]    # (entry, RTI) clocks
    partial: Optional[List[Any]]
    writes: List[Write]
    ram: bytes                      # main 64 KB
    lc: bytes                       # $C000-$FFFF
    stack: Dict[str, Optional[int]]
    labels: Dict[str, int]
    fabric_mhz: float

    def byte(self, label: str, offset: int = 0) -> int:
        a = self.labels[label] + offset
        return self.lc[a - 0xC000] if a >= 0xC000 else self.ram[a]


def profile_name(setup: Setup) -> str:
    parts = setup.profile.split('+')
    if setup.ntsc and 'ntsc' not in parts:
        parts.append('ntsc')
    return '+'.join(parts)


def run(setup: Setup, work: Path, part: Path = PART) -> Result:
    d = load(part)
    lab = d.labels
    work.mkdir(parents=True, exist_ok=True)
    if len(setup.actions) > MAX_ACTIONS:
        raise RunError('%d actions, at most %d' % (len(setup.actions),
                                                   MAX_ACTIONS))
    main = bytearray(d.main)

    def poke(label, value):
        main[lab[label] - DRV_MAIN] = value
    poke('drv_mode', (1 if setup.count else 0) | (2 if setup.calibrate else 0))
    poke('drv_probe', 1 if setup.probe else 0)
    poke('drv_std', 0x80 if setup.ntsc else 0)
    poke('drv_gate', setup.gate)
    poke('drv_frame', setup.frame)
    table = b''.join(a.pack() for a in setup.actions) + b'\0'
    at = lab['drv_actions'] - DRV_MAIN
    main[at:at + len(table)] = table
    image = bytearray(b'A2VMIMG1')

    def record(kind, bank, address, data):
        image.extend(struct.pack('<BBHI', kind, bank, address, len(data)))
        image.extend(data)
    record(2, 0, LC_LO, d.lc)
    record(0, 0, DRV_MAIN, bytes(main))
    for k, data in enumerate(setup.songs):
        record(1, SONG_BANK0 + k, SONG_AT, data)
    record(1, SFX_BANK, SFX_AT, setup.bank or SFX1.read_bytes())
    (work / 'fx.img').write_bytes(bytes(image))
    (work / 'rom.bin').write_bytes(bytes(0x4000))
    name = profile_name(setup)
    (work / 'cost.txt').write_text(costs.text(name))
    fabric = costs.parameters(name)['fabric_mhz']
    fx_lo, fx_size = d.segments['FXCODE']
    snd_lo, snd_size = d.segments['SNDCODE']
    idle = lab['drv_idle']
    lowest = [(idle, idle + 5), (fx_lo, fx_lo + fx_size - 1),
              (snd_lo, snd_lo + snd_size - 1)]
    ranges = ','.join([
        'lc:%04X-%04X' % (S.FXV_BASE, S.FXV_END - 1),
        'lc:%04X-%04X' % (S.FX['FX_ON'], S.FX_RING - 1),
        'lc:%04X-%04X' % (S.FX_RING, S.FX_RING_END - 1),
        'lc:%04X' % lab['snd_playing'], 'main:%04X' % lab['drv_mark']])
    args = [str(A2VM), '--rom', str(work / 'rom.bin'),
            '--core', 'w65c02s', '--via-ora-nh',
            '--image', str(work / 'fx.img'),
            '--switch', 'lc_read=1', '--switch', 'lc_write=1',
            '--reg', 'pc=%X' % lab['drv_start'], '--reg', 's=FF',
            '--reg', 'p=34',
            '--cost', str(work / 'cost.txt'), '--cost-timed',
            '--cycles', str(int(round(setup.seconds * fabric * 1e6))),
            '--ay-log', str(work / 'ay.log'),
            '--state', str(work / 'state.json'),
            '--irq-bounds', IRQ_BOUNDS,
            '--lowest-s-in', ','.join('%X-%X' % r for r in lowest),
            '--write-log', ranges,
            '--write-log-file', str(work / 'writes.log'),
            '--write-log-limit', str(WRITE_LOG_LIMIT),
            '--snapshot-dir', str(work), '--final-snapshot',
            '--stop-pc', '%X' % lab['drv_halt'],
            '--stop-pc', '%X' % lab['pl_crash']]
    if setup.mb_only:
        args.append('--phasor-mb-only')
    if not setup.count:
        args += ['--idle', '%X:vbl:eq=%X,%X' % (idle, lab['vbl_count'],
                                                lab['drv_seen'])]
    try:
        result = bounded.run(args, timeout=RUN_TIMEOUT, max_bytes=MAX_FILE,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                             universal_newlines=True)
    except subprocess.TimeoutExpired:
        raise RunError('a2vm did not finish in %d s' % RUN_TIMEOUT)
    state_path = work / 'state.json'
    if result.returncode or not state_path.exists():
        halt = ''
        if state_path.exists():
            halt = json.loads(state_path.read_text()).get('halt', '')
        raise RunError('a2vm failed: %s\n%s' % (halt, result.stdout[-2000:]))
    state = json.loads(state_path.read_text())
    if state['end'] != 'cycles':
        raise RunError('the run ended early (%s at $%04X%s)' % (
            state['end'], state['pc'],
            ': ' + state['halt'] if state.get('halt') else ''))
    events = run65.read_log(work / 'ay.log')
    mains, bursts, times, partial = run65.group(events)
    writes = read_writes(work / 'writes.log')
    snap = (work / 'final.ram').read_bytes()
    low = state.get('lowest_s', {}).get('ranges', [])
    stack = {'idle': low[0].get('s') if low else None,
             'handler': min((x['s'] for x in low[1:]
                             if x.get('s') is not None), default=None)}
    return Result(state, mains, bursts, times, partial, writes,
                  snap[:0x10000], snap[0x10000:0x14000], stack, lab, fabric)


def read_writes(path: Path) -> List[Write]:
    out = []
    with open(path) as log:
        for line in log:
            if not line.startswith('w '):
                continue
            f = line.split()
            out.append(Write(int(f[1]), int(f[3], 16), int(f[4], 16),
                             int(f[8], 16), int(f[9], 16)))
    return out


def depth(stack: Dict[str, Optional[int]]) -> Optional[int]:
    """The interrupt's stack depth: S where it came (an entry in the idle
    loop, 3 bytes below its S) less the lowest S in the handler's code (as
    tools/native/plclock.py)."""
    top, low = stack.get('idle'), stack.get('handler')
    if top is None or low is None:
        return None
    return top + 3 - low


# ---------------------------------------------------------------------------
# the oracle
# ---------------------------------------------------------------------------

class Event(NamedTuple):
    value: int          # an action's kind, or MARK_FRAME
    start: int
    end: int


def main_events(res: Result) -> List[Event]:
    mark = res.labels['drv_mark']
    out, cur = [], None
    for w in res.writes:
        if w.addr != mark:
            continue
        if w.new == 0:
            if cur is not None:
                out.append(Event(cur[0], cur[1], w.clock))
                cur = None
        elif cur is None:
            cur = (w.new, w.clock)
        elif not (cur[0] == MARK_FRAME and w.new == MARK_REFILL):
            raise RunError('drv_mark $%02X inside $%02X' % (w.new, cur[0]))
    if cur is not None:
        out.append(Event(cur[0], cur[1], 1 << 62))
    return out


class Expect(NamedTuple):
    gaps: List[List[Any]]           # the main loop's writes after irq k
    bursts: List[List[Any]]
    queries: List[int]
    fx: fxplay.FxPlayer
    held: List[int]                 # interrupts with FX_HOLD at entry
    starved: List[int]              # interrupts where a voice starved
    choices: List[Tuple[int, int, int]]     # (voice, channel, sound)
    inside: bool                    # an interrupt landed in a song start
    problems: List[str]


class ChoiceLog(fxplay.FxPlayer):
    """fxplay.FxPlayer that records each start's voice."""

    def __init__(self, *a, **k):
        self.choices = []
        super().__init__(*a, **k)

    def start(self, v, c, m):
        self.choices.append((self.voices.index(v), c, m.sound))
        super().start(v, c, m)


def expect(setup: Setup, res: Result) -> Expect:
    bank = setup.bank or SFX1.read_bytes()
    fx = ChoiceLog(bank, ntsc=setup.ntsc)
    answer = fxplay.SND_NO_MUSIC if (setup.probe and setup.mb_only) \
        else fxplay.SND_MUSIC
    fx.init(answer)
    music = answer == fxplay.SND_MUSIC
    problems: List[str] = []
    gaps: List[List[Any]] = [list(run65.init_events(setup.probe,
                                                   setup.mb_only))]
    bursts: List[List[Any]] = []
    queries: List[int] = []
    held: List[int] = []
    starved: List[int] = []
    events = main_events(res)
    nact = sum(1 for e in events if e.value != MARK_FRAME)
    if nact != len(setup.actions):
        problems.append('%d actions ran, %d given' % (nact, len(setup.actions)))
    hold_at = S.FX['FX_HOLD']
    play_at = res.labels['snd_playing']
    points: List[Tuple[int, int, str, Any]] = []
    for k, (entry, _) in enumerate(res.times, 1):
        points.append((entry, 1, 'irq', k))
    inside = False
    acts = iter(setup.actions)
    for e in events:
        if e.value == MARK_FRAME:
            points.append((e.start, 0, 'frame', None))
            continue
        act = next(acts, None)
        if act is None:
            break
        if act.kind != e.value:
            problems.append('action %s ran as kind %d' % (act, e.value))
            break
        within = [w for w in res.writes if e.start <= w.clock <= e.end]
        if act.kind == SONG and music:
            seq = [(w.clock, 'hold' if w.new else 'release')
                   for w in within if w.addr == hold_at] + \
                  [(w.clock, 'on' if w.new else 'off')
                   for w in within if w.addr == play_at]
            if sorted(x[1] for x in seq) != ['hold', 'off', 'on', 'release']:
                problems.append('a song start without its four steps: %s'
                                % seq)
            for clock, step in seq:
                points.append((clock, 0, 'song-' + step, act))
        else:
            points.append((e.start, 0, 'act', act))
        n_in = [k for k, (entry, _) in enumerate(res.times, 1)
                if e.start < entry < e.end]
        if n_in:
            if act.kind == SONG:
                inside = True
            else:
                problems.append('interrupt %d inside %s: the model cannot '
                                'place it' % (n_in[0], KINDS[act.kind]))
    for e in events:
        if e.value == MARK_FRAME:
            n_in = [k for k, (entry, _) in enumerate(res.times, 1)
                    if e.start < entry < e.end]
            if n_in:
                problems.append('interrupt %d inside a frame\'s service: the '
                                'model cannot place it' % n_in[0])
    points.sort(key=lambda p: (p[0], p[1]))
    state = {'cur': None, 'new': None, 'gate': setup.gate}

    def do_act(act):
        a = act.args
        if act.kind == START:
            fx.mail_start(a[0], a[1], a[2], a[3])
        elif act.kind == STOP:
            fx.mail_stop(a[0])
        elif act.kind == VOLUME:
            fx.mail_volume(a[0], a[1])
        elif act.kind == GATE:
            state['gate'] = a[0]
        elif act.kind == STOPALL:
            fx.stopall()
        elif act.kind == QUERY:
            queries.append(sum(1 << c for c in range(fxplay.NUM_CHANNELS)
                               if fx.isplaying(c)))
        elif act.kind == SERVICE:
            fx.service()
        elif act.kind == SONGSTOP:
            if music and state['cur'] is not None:
                state['cur'].stop()

    for clock, _, what, arg in points:
        if what == 'irq':
            cur = state['cur']
            mus = cur.interrupt() if cur is not None else []
            if fx.hold:
                held.append(arg)
            w = fx.step()
            if any(v.flags & fxplay.STARVED for v in fx.voices):
                starved.append(arg)
            bursts.append(list(mus) + list(w))
            gaps.append([])
        elif what == 'frame':
            if state['gate'] & 1:
                fx.service()
            cur = state['cur']
            if state['gate'] & 2 and music and cur is not None and \
                    cur.playing:
                cur.refill()
        elif what == 'act':
            do_act(arg)
        elif what == 'song-hold':
            fx.song_begin()
        elif what == 'song-off':
            state['cur'] = None
            index = arg.args[0] - SONG_BANK0
            p = run65.RingPlayer(
                player.SongFile.from_bytes(setup.songs[index]),
                run65.machine_of(bool(arg.args[3] & SONG_NTSC)),
                loop=bool(arg.args[3] & SONG_LOOP),
                music_attenuation=arg.args[4])
            gaps[-1].extend(p.start())
            state['new'] = p
        elif what == 'song-on':
            state['cur'] = state['new']
        elif what == 'song-release':
            fx.song_end()
    return Expect(gaps, bursts, queries, fx, held, starved, fx.choices,
                  inside, problems)


def publish_problems(res: Result) -> List[str]:
    """Every ring byte a V_WPOS store publishes was written by the main
    loop since the voice's previous publish or start; no interrupt writes
    a ring."""
    out = []
    entries = [a for a, _ in res.times]

    def in_irq(clock):
        k = bisect.bisect_right(entries, clock) - 1
        return k >= 0 and clock <= res.times[k][1]
    for v in range(fxplay.VOICES):
        base = S.FX_RING + v * fxplay.RING
        wpos = S.FXV_BASE + v * S.VOICE_SIZE + S.VOICE['V_WPOS']
        fresh = set()
        for w in res.writes:
            if base <= w.addr < base + fxplay.RING:
                if in_irq(w.clock):
                    out.append('the interrupt wrote ring %d at $%04X (pc $%04X)'
                               % (v, w.addr, w.pc))
                fresh.add(w.addr - base)
            elif w.addr == wpos:
                if res.ram[w.pc] == 0x9E:           # stz abs,x: a start
                    fresh = set()
                    continue
                n = (w.new - w.old) & 0xFF
                if not 1 <= n <= fxplay.RING:
                    out.append('voice %d: V_WPOS $%02X to $%02X' % (
                        v, w.old, w.new))
                    continue
                for k in range(n):
                    off = (w.old + k) & (fxplay.RING - 1)
                    if off not in fresh:
                        out.append('voice %d: byte %d of the ring published '
                                   'at clock %d before it was written (pc '
                                   '$%04X)' % (v, off, w.clock, w.pc))
                        break
                    fresh.discard(off)
            if len(out) > 5:
                return out
    return out


def compare(setup: Setup, res: Result, ex: Expect) -> List[str]:
    """The run against the model: every interrupt's writes, the main
    loop's, the chips at the end, the answers of fx_isplaying, the burst
    order (chip 3 after the music's), the publish order."""
    out = list(ex.problems)
    if len(res.bursts) != len(ex.bursts):
        out.append('%d interrupts, the model %d' % (len(res.bursts),
                                                    len(ex.bursts)))
    for k, (got, want) in enumerate(zip(res.bursts, ex.bursts), 1):
        chips = [w[0] for w in got if w[0] != 'reset']
        if 3 in chips and any(c != 3 for c in chips[chips.index(3):]):
            out.append('interrupt %d: a write of chip 0-2 after chip 3\'s: %s'
                       % (k, got[:8]))
            break
        if got != want:
            music_got = [w for w in got if w[0] != 3]
            music_want = [w for w in want if w[0] != 3]
            which = 'chips 0-2' if music_got != music_want else 'chip 3'
            out.append('interrupt %d (%s): %s' % (
                k, which, run65.first_difference(got, want)))
            break
    if ex.inside:
        flat = [w for g in res.main for w in g]
        want = [w for g in ex.gaps for w in g]
        if flat != want:
            out.append('the main loop\'s writes: %s' % run65.first_difference(
                flat, want))
    else:
        for k, (got, want) in enumerate(zip(res.main, ex.gaps)):
            if got != want:
                out.append('main loop after interrupt %d: %s' % (
                    k, run65.first_difference(got, want)))
                break
    regs = [[0] * 16 for _ in range(4)]

    def apply(ws):
        for w in ws:
            if w[0] == 'reset':
                regs[w[1]] = [0] * 16
            else:
                regs[w[0]][w[1]] = w[2]
    apply(ex.gaps[0])
    for k, b in enumerate(ex.bursts):
        apply(b)
        if k + 1 < len(ex.gaps):
            apply(ex.gaps[k + 1])
    if res.partial:
        apply(res.partial)
    if not setup.mb_only:
        for chip in range(4):
            if res.state['phasor']['ay'][chip] != regs[chip]:
                out.append('at the end chip %d holds %s, the model %s' % (
                    chip, res.state['phasor']['ay'][chip], regs[chip]))
    nq = res.byte('drv_nq')
    got_q = [res.byte('drv_qlog', k) for k in range(nq)]
    if got_q != ex.queries[:QLOG]:
        out.append('fx_isplaying: %s, the model %s' % (got_q, ex.queries))
    out += publish_problems(res)
    return out


# ---------------------------------------------------------------------------
# the scenarios
# ---------------------------------------------------------------------------

def bank_bytes() -> bytes:
    return SFX1.read_bytes()


def effect_length(bank: bytes, sound: int, ntsc: bool = False) -> int:
    """Interrupts from an effect's first one to its voice's last write
    (alone, full volume), by the model."""
    fx = fxplay.FxPlayer(bank, ntsc=ntsc)
    fx.mail_start(0, sound, VOL_NEAR, SEP_CENTRE)
    fx.service()
    for k in range(1, 2000):
        fx.interrupt()
        fx.service()
        if not any(v.flags for v in fx.voices):
            return k
    raise RunError('effect %d never ends' % sound)


def song_files() -> List[Path]:
    return sorted(SONGS.glob('D_*.native12.ay'))


def alone_setup(bank: bytes, ntsc: bool, vol: int, voice: str,
                sounds: Sequence[int] = range(1, 53)) -> Setup:
    """Every effect alone, one after the other, on voice A, B or C."""
    acts, t = [], 2
    for s in sounds:
        if voice == 'A':
            acts.append(start(t, 0, s, vol, SEP_LEFT))
        elif voice == 'B':
            acts.append(start(t, 0, s, vol, SEP_RIGHT))
        else:           # C: A taken in the same gap, then freed before
            acts += [start(t, 0, s, vol, SEP_LEFT),      # any interrupt
                     start(t, 1, s, vol, SEP_LEFT),
                     other(SERVICE, t), stop(t, 0)]
        t += effect_length(bank, s, ntsc) + 2
    hz = tables.vbl_hz(run65.machine_of(ntsc))
    return Setup(tuple(acts), t / hz + 0.3, ntsc=ntsc, bank=bank)


def demo3_starts() -> List[int]:
    """demo3's S_StartSound and S_StartSound2 calls: their gametics."""
    import s2cap
    calls = s2cap.load_calls(CASES / 'demo3' / 'calls.z')
    starts = calls.of('S_StartSound') + calls.of('S_StartSound2')
    starts.sort(key=lambda c: c['call'])
    return [int.from_bytes(bytes.fromhex(c['in']['mem'][1]), 'little')
            for c in starts]


VOLS = (VOL_NEAR, 90, VOL_MID, 30, VOL_FAR)
SEPS = (SEP_CENTRE, 127, 129, SEP_LEFT, SEP_RIGHT, 1, 255)


def over_song_setup(songs: Sequence[bytes], index: int, gametics: List[int],
                    seconds: float = 20.0, ntsc: bool = False) -> Setup:
    """Song `index` from VBL 0, the effects at demo3's measured times
    (gametics at 34.955 a second, from VBL 10), each of the 52 in turn."""
    hz = tables.vbl_hz(run65.machine_of(ntsc))
    first = gametics[0]
    acts = [song(0, 0, ntsc)]
    k = 0
    for g in gametics:
        vbl = 10 + int(round((g - first) * hz / 34.955))
        if vbl > seconds * hz - 10 or len(acts) >= MAX_ACTIONS:
            break
        acts.append(start(vbl, k % 3, (k + 7 * index) % 52 + 1,
                          VOLS[k % len(VOLS)], SEPS[k % len(SEPS)]))
        k += 1
    return Setup(tuple(acts), seconds, ntsc=ntsc, songs=(songs[index],))


def three_setup(songs: Sequence[bytes], profile: str = PROFILE,
                seconds: float = 20.0, index: int = 0) -> Setup:
    """Song `index` with three effects started in one VBL, again and again
    (the worst interrupt, the stack). The first three start with the
    song's first burst: their mailboxes at VBL 0, the song at VBL 1, so
    the song's first interrupt (its first chord, the music's largest
    burst in D_INTRO) is the effects' first, a whole chip 3."""
    acts = [start(0, c, (2, 9, 15)[c], VOL_NEAR,
                  (SEP_LEFT, SEP_RIGHT, SEP_CENTRE)[c]) for c in range(3)]
    acts.append(song(1, 0))
    t, k = 25, 0
    while t < seconds * 50 - 60 and len(acts) + 3 <= MAX_ACTIONS:
        for c in range(3):
            acts.append(start(t, c, (3 * k + c) % 52 + 1, VOL_NEAR,
                              (SEP_LEFT, SEP_RIGHT, SEP_CENTRE)[c]))
        t += 45
        k += 1
    return Setup(tuple(acts), seconds, songs=(songs[index],),
                 profile=profile)


def underrun_setup(bank: bytes) -> Setup:
    """DORCLS (460 B) with fx_service gated off for 40 VBLs: its ring runs
    dry, the voice is silent and holds, then goes on."""
    s = 15
    acts = (start(2, 0, s), other(GATE, 3, 2), other(GATE, 43, 3),
            start(160, 1, 6, VOL_MID, SEP_RIGHT), other(GATE, 165, 2),
            other(GATE, 190, 3))
    return Setup(acts, 6.0, bank=bank)


def hold_setup(songs: Sequence[bytes], tries: int = 40) -> Setup:
    """Song starts while an effect plays, each after a delay a step
    longer, so that some VBLs land inside fx_song (calibrated delays)."""
    acts = []
    t = 4
    for i in range(tries):
        acts.append(start(t, i % 3, (5, 6, 15)[i % 3], VOL_NEAR,
                          (SEP_LEFT, SEP_RIGHT, SEP_CENTRE)[i % 3]))
        acts.append(song(t + 3, i % len(songs), delay=0))
        acts[-1] = acts[-1]._replace(delay=-(i + 1))    # placeholder
        t += 12
    return Setup(tuple(acts), (t + 20) / 50.0, songs=tuple(songs),
                 calibrate=True)


HOLD_SWEEP = 2.5       # the delay loop's turn is about half the
                       # calibration loop's [M: 45 and 90 fabric clocks]


def hold_delays(setup: Setup, cal: int, tries: int) -> Setup:
    """The song starts' delays: a step of HOLD_SWEEP x cal / tries, so the
    starts sweep a frame and more."""
    acts = []
    for a in setup.actions:
        if a.kind == SONG and a.delay < 0:
            i = -a.delay - 1
            a = a._replace(delay=min(0xFFFF, int(cal * HOLD_SWEEP *
                                                 (i + 0.5) / tries)))
        acts.append(a)
    return setup._replace(actions=tuple(acts))


def stereo_setup(bank: bytes) -> Tuple[Setup, List[str]]:
    """The stereo rule (each band and its bounds, the fallbacks with each
    voice busy, the channel's own voice freed first), the
    mailboxes' rules, fx_isplaying, the noise of the loudest. Returns the
    setup and the voices the starts must take, in order."""
    long_ = 15                          # DORCLS: 176 ticks
    acts, want = [], []
    t = 2

    def gap(n=1):
        nonlocal t
        t += n

    def stopall():
        acts.append(other(STOPALL, t))
    # alone, each band and its bounds (tools/sound/README.md "Stereo by
    # voice": A left, B right, C centre): below 96 A, 96 to 160 C, above
    # 160 B. The voices are written here, not taken from tables.py
    for sep, v in ((1, 'A'), (95, 'A'), (96, 'C'), (128, 'C'), (129, 'C'),
                   (160, 'C'), (161, 'B'), (255, 'B')):
        acts.append(start(t, 0, 1, VOL_NEAR, sep))
        want.append(v)
        gap(8)
        stopall()
        gap(3)
    # the fallbacks, to the nearest free voice in pan: three starts on
    # channels 0, 1, 2, each while the earlier ones play
    for case in (((128, 'C'), (128, 'A'), (100, 'B')),   # C busy: 128 left
                 ((129, 'C'), (160, 'B'), (140, 'A')),   # right of centre
                 ((50, 'A'), (95, 'C'), (1, 'B')),       # A busy: C, then B
                 ((200, 'B'), (161, 'C'), (255, 'A'))):  # B busy: C, then A
        for c, ((sep, v), sound) in enumerate(zip(case, (long_, 6, 1))):
            acts.append(start(t, c, sound, VOL_MID if c else VOL_NEAR, sep))
            want.append(v)
            gap(2)
        gap(18)
        stopall()
        gap(3)
    # a channel's own voice is freed first: A and B busy, channel 0 on C
    # at 128, then again at 1 (A first: busy; its own C freed)
    acts += [start(t, 1, long_, VOL_MID, 64), start(t, 2, long_, VOL_MID,
                                                    200)]
    want += ['A', 'B']
    gap(2)
    acts.append(start(t, 0, long_, VOL_NEAR, 128))
    want.append('C')
    gap(3)
    acts.append(start(t, 0, 6, VOL_NEAR, 1))
    want.append('C')
    gap(20)
    stopall()
    gap(3)
    # the mailboxes: a start then a stop in one frame: no voice
    acts += [start(t, 0, long_), other(QUERY, t), stop(t, 0),
             other(QUERY, t)]
    gap(5)
    acts.append(other(QUERY, t))
    gap(2)
    # a stop then a start: the new sound
    acts.append(start(t, 0, long_, VOL_NEAR, 64))
    want.append('A')
    gap(10)
    acts += [stop(t, 0), start(t, 0, 6, VOL_MID, 200), other(QUERY, t)]
    want.append('B')
    gap(10)
    acts.append(other(QUERY, t))
    # a start then a volume: the new volume
    acts += [start(t, 1, long_, VOL_NEAR, 64), volume(t, 1, 20)]
    want.append('A')
    gap(30)
    acts += [volume(t, 1, VOL_MID)]
    gap(20)
    stopall()
    gap(3)
    # the noise of the loudest: two noisy effects, the louder first (A)
    # and the quieter last (B), then the louder last
    acts += [start(t, 0, 9, VOL_NEAR, 64), start(t, 1, 49, 20, 200)]
    want += ['A', 'B']
    gap(60)
    stopall()
    gap(3)
    acts += [start(t, 0, 9, 20, 64), start(t, 1, 49, VOL_NEAR, 200)]
    want += ['A', 'B']
    gap(60)
    # fx_isplaying after the natural end of a sound
    acts.append(other(QUERY, t))
    gap(150)
    acts.append(other(QUERY, t))
    gap(5)
    return Setup(tuple(acts), t / 50.0 + 0.2, bank=bank), want


class NoiseWatch(fxplay.FxPlayer):
    """fxplay.FxPlayer that counts the composes where the loudest voice
    with noise and the last voice with noise have different periods (where
    the rule can be told from "the last voice's")."""

    telling = 0

    def compose(self):
        noisy = [(min(fxplay.ATT_SILENT, v.att + v.vatt), k, v.noise)
                 for k, v in enumerate(self.voices)
                 if v.flags & (fxplay.ACTIVE | fxplay.STARVED) ==
                 fxplay.ACTIVE and v.noise]
        if len(noisy) > 1 and min(noisy)[2] != noisy[-1][2]:
            self.telling += 1
        super().compose()


def noise_telling(bank: bytes, setup: Setup) -> int:
    """How many interrupts of `setup` (its effects, no music, one frame a
    VBL) tell the loudest voice's noise from the last one's, by the
    model."""
    fx = NoiseWatch(bank)
    acts = sorted(setup.actions, key=lambda a: a.vbl)
    i = 0
    for k in range(max(a.vbl for a in acts) + 10):
        while i < len(acts) and acts[i].vbl <= k:
            a = acts[i]
            if a.kind == START:
                fx.mail_start(*a.args[:4])
            elif a.kind == STOP:
                fx.mail_stop(a.args[0])
            elif a.kind == VOLUME:
                fx.mail_volume(a.args[0], a.args[1])
            elif a.kind == STOPALL:
                fx.stopall()
            elif a.kind == SERVICE:
                fx.service()
            i += 1
        fx.service()
        fx.interrupt()
    return fx.telling


def tone_first(bank: bytes) -> int:
    """The first effect whose first state has a tone."""
    for s in range(1, 53):
        fx = fxplay.FxPlayer(bank)
        fx.mail_start(0, s, VOL_NEAR, SEP_CENTRE)
        fx.service()
        fx.interrupt()
        if fx.chan_voice(0).per:
            return s
    raise RunError('no effect starts with a tone')


# ---------------------------------------------------------------------------
# the checkpoint
# ---------------------------------------------------------------------------

def tmpdir(tag: str) -> Path:
    BUILD.mkdir(exist_ok=True)
    return Path(tempfile.mkdtemp(prefix='tmp-fxplay-%s-' % tag,
                                 dir=str(BUILD)))


def checked(setup: Setup, tag: str, part: Path = PART,
            extra=None) -> Tuple[List[str], Result, Expect]:
    """Run and compare; the run's directory deleted."""
    work = tmpdir(tag)
    try:
        res = run(setup, work, part)
        ex = expect(setup, res)
        problems = compare(setup, res, ex)
        if extra:
            problems += extra(res, ex)
        return problems, res._replace(writes=[]), ex
    finally:
        shutil.rmtree(str(work), ignore_errors=True)


def s2_alone(song: bytes, seconds: float, ntsc: bool = False,
             profile: str = PROFILE) -> Any:
    """S2's own build (build/sound65, snd_vbl) plays the song alone."""
    work = tmpdir('s2')
    try:
        variants = [v for v in profile.split('+')[1:] if v != 'ntsc']
        return run65.run(run65.Player65(SOUND65), [song],
                         [run65.start_action(0, 0, ntsc=ntsc)], seconds,
                         work, ntsc=ntsc, variants=tuple(variants),
                         profile=profile.split('+')[0])
    finally:
        shutil.rmtree(str(work), ignore_errors=True)


def same_as_s2(mine: Result, s2: Any) -> List[str]:
    """The whole AY log equal to S2's: every group (before the first
    interrupt, each interrupt, the main loop after each), write for
    write; the interrupt the run cut a prefix of S2's or the reverse; the
    chips at the end (the cut's writes aside)."""
    out = []
    if len(mine.bursts) != len(s2.bursts):
        out.append('%d interrupts, S2 %d' % (len(mine.bursts),
                                             len(s2.bursts)))
    for k in range(min(len(mine.main), len(s2.main))):
        if mine.main[k] != s2.main[k]:
            out.append('main loop after interrupt %d: %s' % (
                k, run65.first_difference(mine.main[k], s2.main[k])))
            break
        if k < min(len(mine.bursts), len(s2.bursts)) and \
                mine.bursts[k] != s2.bursts[k]:
            out.append('interrupt %d: %s' % (k + 1, run65.first_difference(
                mine.bursts[k], s2.bursts[k])))
            break
    a, b = mine.partial or [], s2.partial or []
    if a[:len(b)] != b[:len(a)]:
        out.append('the interrupt the run cut: %s, S2 %s' % (a[:3], b[:3]))
    if not a and not b and mine.state['phasor'] != s2.state['phasor']:
        out.append('the Phasor at the end differs')
    return out


def music_of(res: Result) -> List[List[Any]]:
    return [[w for w in b if w[0] != 3] for b in res.bursts]


def checkpoint(jobs: int = JOBS, quick: bool = False, part: Path = PART,
               out=print) -> List[str]:
    bank = bank_bytes()
    songs_paths = song_files()
    songs = [p.read_bytes() for p in songs_paths]
    names = [p.name.split('.')[0] for p in songs_paths]
    problems: List[str] = []
    tasks = []
    # every effect alone: PAL and NTSC, three distances, each voice
    combos = [(ntsc, vol, voice) for ntsc in (False, True)
              for vol in (VOL_NEAR, VOL_MID, VOL_FAR) for voice in 'ABC']
    if quick:
        combos = [(False, VOL_NEAR, 'A'), (True, VOL_MID, 'B'),
                  (False, VOL_FAR, 'C')]
    for ntsc, vol, voice in combos:
        tasks.append(('alone %s vol %d voice %s' % (
            'NTSC' if ntsc else 'PAL', vol, voice),
            alone_setup(bank, ntsc, vol, voice), None))
    gametics = demo3_starts()
    sel = range(len(songs)) if not quick else (0, 9, 10)
    for i in sel:
        setup = over_song_setup(songs, i, gametics)
        played = {a.args[1] for a in setup.actions if a.kind == START}
        if len(played) != 52:
            problems.append('over %s: %d of the 52 effects' % (names[i],
                                                               len(played)))
        tasks.append(('effects over %s' % names[i], setup, ('vs-s2', i)))
        tasks.append(('no effect, %s' % names[i],
                      Setup((song(0, 0),), 20.0, songs=(songs[i],)),
                      ('s2', i)))
    tasks.append(('underrun', underrun_setup(bank), 'underrun'))
    st, want = stereo_setup(bank)
    tasks.append(('stereo and mailboxes', st, ('stereo', want)))
    tone = tone_first(bank)
    tasks.append(('a tone effect before any song',
                  Setup((start(3, 0, tone),), 2.0), ('tone', tone)))
    tasks.append(('--phasor-mb-only',
                  Setup((start(3, 0, tone), other(QUERY, 3), start(5, 1, 6),
                         other(QUERY, 6), song(8, 0)), 2.0, probe=True,
                        mb_only=True, songs=(songs[0],)), 'mb'))
    for i in (0, names.index('D_INTRO')):
        tasks.append(('no effect, %s, window 512' % names[i],
                      Setup((song(0, 0),), 20.0, songs=(songs[i],),
                            profile='f121+phasor'), ('three', 'alone')))
        for prof in (PROFILE, 'f121+phasor'):
            tasks.append(('three effects over %s, %s' % (names[i], prof),
                          three_setup(songs, prof, index=i), ('three', prof)))

    def one(task):
        name, setup, kind = task
        try:
            p, res, ex = checked(setup, 'ck')
        except RunError as e:
            return name, ['run: %s' % e], None, None, kind, None
        extra = None
        if isinstance(kind, tuple) and kind[0] in ('s2', 'vs-s2'):
            extra = s2_alone(setup.songs[0], setup.seconds)
        return name, p, res, ex, kind, extra

    with ThreadPoolExecutor(max_workers=jobs) as pool:
        results = list(pool.map(one, tasks))
    hold = hold_run(songs[:3], jobs)
    for name, p, res, ex, kind, s2 in results:
        if res is not None:
            p = p + scenario_problems(kind, res, ex, s2)
        line = '%-44s %s' % (name, 'ok' if not p else p[0])
        if res is not None:
            line += '  (%d interrupts, %d chip-3 writes)' % (
                len(res.bursts), sum(1 for b in res.bursts for w in b
                                     if w[0] == 3))
        out(line)
        if res is not None and (kind in (('s2', 0), ('s2', 10)) or
                                (isinstance(kind, tuple) and
                                 kind[0] == 'three')):
            ln = sorted(irq_lengths(res))
            out('    interrupts: worst %.1f µs, median %.1f µs, p99 %.1f '
                'µs; stack %s B' % (ln[-1], statistics.median(ln),
                                    ln[int(len(ln) * 0.99)],
                                    depth(res.stack)))
        problems += ['%s: %s' % (name, x) for x in p]
    out('%-44s %s' % ('an effect held across fx_song', hold[0] or 'ok'))
    out('    ' + hold[1])
    if hold[0]:
        problems.append('hold: %s' % hold[0])
    z = sizes(part)
    out('sizes: the card part %d B (code %d, state %d) of 748 (620 and '
        'VATT\'s 128, VATT now read from bank SFX); FXCODE %d of %d B with '
        'pl_vbl; fx_service %d of 400 B' % (
            z['fx-card:FXCODE'], z['card_code'], z['card_data'], z['FXCODE'],
            z['FXC_ROOM'], z['fx:S2CODE']))
    if z['fx:S2CODE'] > 400:
        problems.append('fx_service %d B over 400' % z['fx:S2CODE'])
    if z['FXCODE'] > z['FXC_ROOM']:
        problems.append('FXCODE over its room')
    out('problems: %d' % len(problems))
    return problems


def scenario_problems(kind, res: Result, ex: Expect, s2) -> List[str]:
    out = []
    if kind == 'underrun':
        if not ex.starved:
            out.append('the ring never ran dry')
        else:
            last = max(ex.starved)
            after = [k for k in range(last + 1, len(ex.bursts) + 1)
                     if any(w[0] == 3 and w[1] >= 8 and w[2]
                            for w in ex.bursts[k - 1])]
            if not after:
                out.append('the voice never went on after its underrun')
    elif isinstance(kind, tuple) and kind[0] == 'stereo':
        want = kind[1]
        got = ['ABC'[v] for v, _, _ in ex.choices]
        if got != want:
            out.append('voices %s, the rule %s' % (''.join(got),
                                                   ''.join(want)))
    elif isinstance(kind, tuple) and kind[0] == 'tone':
        first = next((b for b in res.bursts
                      if any(w[0] == 3 for w in b)), [])
        regs = [w[1] for w in first if w[0] == 3]
        if regs != list(range(fxplay.NREGS)):
            out.append('the first burst of chip 3 wrote %s, not R0-R10' %
                       regs)
        pre = [w for g in res.main[:1] for w in g if w[0] == 3]
        if pre:
            out.append('chip 3 written before the effect: %s' % pre[:3])
    elif kind == 'mb':
        writes = [w for g in res.main for w in g if w[0] != 'reset'] + \
                 [w for b in res.bursts for w in b]
        probe = [w for w in run65.PROBE_EVENTS[True] if w[0] != 'reset']
        if writes != probe:
            out.append('AY writes beyond the probe\'s: %s' % [
                w for w in writes if w not in probe][:4])
        if res.byte('drv_nq') != 2:
            out.append('%d queries' % res.byte('drv_nq'))
        if S.FX['FX_ON'] and res.lc[S.FX['FX_ON'] - 0xC000] != 0:
            out.append('FX_ON is not 0')
    elif isinstance(kind, tuple) and kind[0] == 's2':
        out += same_as_s2(res, s2)
    elif isinstance(kind, tuple) and kind[0] == 'vs-s2':
        mine = music_of(res)
        n = min(len(mine), len(s2.bursts))
        for k in range(n):
            if mine[k] != s2.bursts[k]:
                out.append('interrupt %d: chips 0-2 %s' % (
                    k + 1, run65.first_difference(mine[k], s2.bursts[k])))
                break
    elif isinstance(kind, tuple) and kind[0] == 'three':
        d = depth(res.stack)
        if d is None or d > S.IRQ_STACK:
            out.append('the interrupt\'s stack %s B' % d)
    return out


def irq_lengths(res: Result) -> List[float]:
    return [(b - a) / res.fabric_mhz for a, b in res.times]


def hold_run(songs: Sequence[bytes], jobs: int = JOBS,
             tries: int = 40) -> Tuple[Optional[str], str]:
    """Song starts with delays swept over a frame while effects play: at
    least one VBL must land with FX_HOLD set; in it no chip-3 write; at
    the next interrupt with a voice, all of R0-R10."""
    setup = hold_setup(songs, tries)
    work = tmpdir('cal')
    try:
        res = run(setup._replace(actions=(), seconds=0.3), work)
        cal = res.byte('drv_cal') | res.byte('drv_cal', 1) << 8
    except RunError as e:
        return 'calibration: %s' % e, ''
    finally:
        shutil.rmtree(str(work), ignore_errors=True)
    setup = hold_delays(setup, cal, tries)
    try:
        p, res, ex = checked(setup, 'hold')
    except RunError as e:
        return 'run: %s' % e, ''
    if not ex.held:
        p.append('no VBL landed with FX_HOLD set (%d tries)' % tries)
    for k in ex.held:
        b = res.bursts[k - 1]
        if any(w[0] == 3 for w in b):
            p.append('interrupt %d with FX_HOLD set wrote chip 3' % k)
        nxt = next((res.bursts[j] for j in range(k, len(res.bursts))
                    if any(w[0] == 3 for w in res.bursts[j])), None)
        if nxt is not None and \
                [w[1] for w in nxt if w[0] == 3] != list(range(11)):
            p.append('after the hold of interrupt %d chip 3 got %s' % (
                k, [w[1] for w in nxt if w[0] == 3]))
    note = ('%d song starts, delay steps of %d of %d loop turns a VBL; %d '
            'VBLs landed with FX_HOLD set (interrupts %s)' % (
                tries, cal // tries, cal, len(ex.held), ex.held[:8]))
    return (p[0] if p else None), note


# ---------------------------------------------------------------------------
# cost and timing
# ---------------------------------------------------------------------------

COST_VARIANTS = (('window 512', 'f121+phasor'),
                 ('window 32', 'f121+phasor+window32'),
                 ('FW-S1', 'f121+phasor+fws1'))


def cycling_actions(bank: bytes, voices: int, seconds: float,
                    with_song: bool) -> Tuple[Act, ...]:
    """`voices` channels each playing the 52 effects in turn, back to
    back (a start every effect's length)."""
    acts = [song(0, 0)] if with_song else []
    end = int(seconds * 50) - 5
    lengths = {s: effect_length(bank, s) for s in range(1, 53)}
    plans = []
    for c in range(voices):
        t, s = 3 + 7 * c, 1 + 17 * c
        while t < end:
            plans.append(start(t, c, (s - 1) % 52 + 1, VOL_NEAR,
                               (SEP_LEFT, SEP_RIGHT, SEP_CENTRE)[c]))
            t += lengths[(s - 1) % 52 + 1] + 1
            s += 1
    plans.sort(key=lambda a: a.vbl)
    acts += plans[:MAX_ACTIONS - len(acts)]
    return tuple(acts)


def cost(jobs: int = JOBS, seconds: float = 20.0, out=print) -> List[str]:
    """The effects' cost a second (1 and 3 voices; window 512, 32, FW-S1)
    as the time they take from the main loop (drv_count against a run
    without them), the part spent in the interrupt, and the slowdown
    tail: the main loop's time lost beyond the interrupts, a burst of
    chip 3 (with no music every burst of chip 3 is an interrupt where
    only the effects write); over D_E1M1, the extra tail the effects add
    to the song's, a burst where only the effects write."""
    bank = bank_bytes()
    songs = (song_files()[0].read_bytes(),)
    tasks = []
    for label, prof in COST_VARIANTS:
        for n in (0, 1, 3):
            acts = cycling_actions(bank, n, seconds, False) if n else ()
            tasks.append((label, n, False, Setup(acts, seconds, count=True,
                                                 profile=prof)))
        for n in (0, 3):
            acts = cycling_actions(bank, n, seconds, True) if n else \
                (song(0, 0),)
            tasks.append((label, n, True, Setup(acts, seconds, songs=songs,
                                                count=True, profile=prof)))
        # the integration's report (docs/SCREENS.md 8.3 item 2): D_E1M1
        # with the effects at demo3's measured start times, and with three
        # effects started in one VBL again and again (the worst case)
        tasks.append((label, 'demo3', True, over_song_setup(
            songs, 0, demo3_starts(), seconds)._replace(
                count=True, profile=prof)))
        tasks.append((label, 'three', True, three_setup(
            songs, prof, seconds)._replace(count=True)))

    def one(task):
        work = tmpdir('cost')
        try:
            return task, run(task[3], work)._replace(writes=[])
        finally:
            shutil.rmtree(str(work), ignore_errors=True)
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        done = list(pool.map(one, tasks))
    rows = {(label, n, m): res for (label, n, m, _), res in done}

    def figures(r, base):
        ms = 1000.0 * (1 - counter(r) / counter(base))
        irq = (sum(b - a for a, b in r.times) -
               sum(b - a for a, b in base.times)) / r.fabric_mhz / 1000.0 \
            / seconds
        return ms, irq
    out('Without music (the cost a second, ms of 1,000):')
    out('')
    out('| Setting | effects | from the main loop | in the interrupt | '
        'tail | chip-3 writes/s | bursts/s | tail a burst |')
    out('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |')
    for label, _ in COST_VARIANTS:
        base = rows[(label, 0, False)]
        for n in (1, 3):
            r = rows[(label, n, False)]
            ms, irq = figures(r, base)
            bursts = sum(1 for b in r.bursts if any(w[0] == 3 for w in b))
            w3 = sum(1 for b in r.bursts for w in b if w[0] == 3)
            out('| %s | %d | %.2f | %.2f | %.2f | %.0f | %.1f | %.0f µs |' % (
                label, n, ms, irq, ms - irq, w3 / seconds, bursts / seconds,
                1000.0 * (ms - irq) / (bursts / seconds)))
    out('')
    out('Over D_E1M1 (three effects; the song alone as the base):')
    out('')
    out('| Setting | the song alone | with the effects | the effects: in '
        'the interrupt, tail | bursts with the music\'s, alone, a second | '
        'extra tail a burst of their own |')
    out('| --- | ---: | ---: | --- | --- | ---: |')
    nothing = {label: rows[(label, 0, False)] for label, _ in COST_VARIANTS}
    for label, _ in COST_VARIANTS:
        alone, both = rows[(label, 0, True)], rows[(label, 3, True)]
        ms0, irq0 = figures(alone, nothing[label])
        ms3, irq3 = figures(both, nothing[label])
        shared = own = 0
        for b in both.bursts:
            if any(w[0] == 3 for w in b):
                if any(w[0] != 3 for w in b):
                    shared += 1
                else:
                    own += 1
        tail = (ms3 - irq3) - (ms0 - irq0)
        out('| %s | %.2f ms/s | %.2f ms/s | %.2f, %.2f ms/s | %.1f, %.1f | '
            '%.0f µs |' % (label, ms0, ms3, irq3 - irq0, tail,
                           shared / seconds, own / seconds,
                           1000.0 * tail / (own / seconds) if own else 0))
    out('')
    out('Over D_E1M1: the song alone, the effects at demo3\'s measured start '
        'times, three effects started in one VBL every 45 (ms of 1,000 a '
        'second from the main loop: in the interrupt, tail; the worst '
        'interrupt):')
    out('')
    out('| Setting | the song alone | demo3\'s start rate (starts) | three '
        'at once | worst interrupt: alone, demo3, three |')
    out('| --- | --- | --- | --- | --- |')

    def worst(r):
        return max((b - a for a, b in r.times), default=0) / r.fabric_mhz
    for label, _ in COST_VARIANTS:
        base = nothing[label]
        cells = []
        for key in (0, 'demo3', 'three'):
            r = rows[(label, key, True)]
            ms, irq = figures(r, base)
            cells.append('%.2f ms/s (%.2f, %.2f)' % (ms, irq, ms - irq))
        setup = next(task[3] for task, _ in done
                     if task[0] == label and task[1] == 'demo3')
        cells[1] += ' (%d)' % sum(1 for a in setup.actions
                                  if a.kind == START)
        out('| %s | %s | %.1f, %.1f, %.1f µs |' % (
            label, ' | '.join(cells), worst(rows[(label, 0, True)]),
            worst(rows[(label, 'demo3', True)]),
            worst(rows[(label, 'three', True)])))
    return []


def counter(res: Result) -> int:
    a = res.labels['drv_counter']
    return int.from_bytes(res.ram[a:a + 4], 'little')


def summary(pairs) -> str:
    if not pairs:
        return '-'
    extra = statistics.median(p[0] for p in pairs)
    writes = statistics.median(p[1] for p in pairs)
    one = [p[0] for p in pairs if p[1] == 1]
    return '%.1f µs, %g writes (%d interrupts; 1 write: %s)' % (
        extra, writes, len(pairs),
        '%.1f µs' % statistics.median(one) if one else '-')


def timing(jobs: int = JOBS, out=print) -> List[str]:
    """fx_service a frame (docs/SCREENS.md 6.4): three effects, music on,
    a frame every VBL (50 a second) and every 8 (6 a second), f121 and
    fastpath (the Doom profile's window 32)."""
    bank = bank_bytes()
    songs = [song_files()[0].read_bytes()]
    tasks = []
    for prof in ('f121+phasor+window32', 'fastpath+phasor+window32'):
        for frame in (1, 8):
            acts = cycling_actions(bank, 3, 20.0, True)
            tasks.append((prof, frame, Setup(acts, 20.0, songs=tuple(songs),
                                             profile=prof, frame=frame)))

    def one(task):
        prof, frame, setup = task
        work = tmpdir('time')
        try:
            res = run(setup, work)
            return task, frame_times(res), res
        finally:
            shutil.rmtree(str(work), ignore_errors=True)
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        done = list(pool.map(one, tasks))
    out('| Profile | frames a second | fx_service median / p99 / worst µs '
        '| frames |')
    out('| --- | ---: | --- | ---: |')
    for (prof, frame, _), t, res in done:
        hz = 50.08 / frame
        if not t:
            out('| %s | %.1f | - | 0 |' % (prof, hz))
            continue
        t.sort()
        out('| %s | %.1f | %.1f / %.1f / %.1f | %d |' % (
            prof, hz, statistics.median(t), t[min(len(t) - 1,
                                                  int(len(t) * 0.99))],
            t[-1], len(t)))
    return []


def frame_times(res: Result) -> List[float]:
    """Each frame's fx_service in µs (drv_mark $80 to $81), an
    interrupt inside it left out."""
    mark = res.labels['drv_mark']
    out, begin = [], None
    for w in res.writes:
        if w.addr != mark:
            continue
        if w.new == MARK_FRAME:
            begin = w.clock
        elif w.new == MARK_REFILL and begin is not None:
            if not any(begin < a < w.clock for a, _ in res.times):
                out.append((w.clock - begin) / res.fabric_mhz)
            begin = None
    return out


# ---------------------------------------------------------------------------
# the planted bugs
# ---------------------------------------------------------------------------

# (name, the text in fx.s, its replacement, the scenarios that must fail)
PLANTED = (
    ('chip 3\'s burst before the music\'s',
     '        sty fx_wn\n@done:  rts\n',
     '        sty fx_wn\n        jmp fx_burst\n@done:  rts\n', ('songs',)),
    ('the noise period of the last voice instead of the loudest',
     '        cmp FXZ_BEST\n        bcs @tone',
     '        cmp FXZ_BEST\n        nop\n        nop', ('stereo',)),
    ('a ring refill published before its bytes',
     '        lda FXS_P\n        jsr fx_copy\n',
     '        lda FXS_P\n        clc\n        adc FXV_BASE + V_WPOS,x\n'
     '        sta FXV_BASE + V_WPOS,x\n        lda FXS_P\n'
     '        jsr fx_copy\n', ('underrun',)),
    ('the sides inverted (the right\'s order from the left\'s offset)',
     '        .byte FXO_L, FXO_C, FXO_L, FXO_C, FXO_R, FXO_L, FXO_R\n'
     '        .byte FXO_R, FXO_C, FXO_L, $FF',
     '        .byte FXO_R, FXO_C, FXO_L, FXO_C, FXO_R, FXO_L, FXO_R\n'
     '        .byte FXO_L, FXO_C, FXO_R, $FF', ('stereo',)),
    ('the distance attenuation added twice',
     '        adc FXV_BASE + V_ATT,x\n        cmp #ATT_SILENT + 1',
     '        adc FXV_BASE + V_ATT,x\n        adc FXV_BASE + V_ATT,x\n'
     '        cmp #ATT_SILENT + 1', ('alone',)),
    ('FX_INVAL ignored (the shadow kept across a song start)',
     '        ldx #1\n        stx FX_INVAL\n',
     '        ldx #1\n        nop\n        nop\n        nop\n', ('hold',)),
    ('separation 128 falling back to the right',
     '        cpx #FX_SEP_CENTRE + 1  ; carry: right of the centre',
     '        cpx #FX_SEP_CENTRE      ; carry: right of the centre',
     ('stereo',)),
    ('separation 96 to the left voice',
     '        cpx #FX_SEP_LEFT        ; carry: not the left',
     '        cpx #FX_SEP_LEFT + 1    ; carry: not the left', ('stereo',)),
    ('fx_isplaying ignoring a pending start',
     '        and #MX_START\n        bne @yes',
     '        and #0\n        bne @yes', ('stereo',)),
)
# the third bug moves the publish: its later publish is taken out
PUBLISH_AFTER = (':       lda FXS_P               ; published: its bytes '
                 'are in\n        clc\n        adc FXV_BASE + V_WPOS,x\n'
                 '        sta FXV_BASE + V_WPOS,x\n')


def planted_variant(name: str, old: str, new: str, root: Path) -> Path:
    src = root / 'src'
    src.mkdir(parents=True)
    text = (SRC / 'fx.s').read_text()
    if text.count(old) != 1:
        raise RunError('planted %r: its text is not in fx.s once' % name)
    text = text.replace(old, new)
    if 'published before' in name:
        if text.count(PUBLISH_AFTER) != 1:
            raise RunError('planted %r: the later publish' % name)
        text = text.replace(PUBLISH_AFTER, ':\n')
    (src / 'fx.s').write_text(text)
    shutil.copy(str(SRC / 'fxdrv.s'), str(src / 'fxdrv.s'))
    return src


def scenario(kind: str, bank: bytes, songs: Sequence[bytes],
             part: Path) -> List[str]:
    """One scenario of the checkpoint on the build in `part`: its
    problems."""
    if kind == 'hold':
        return hold_check(songs[:3], part)
    if kind == 'songs':
        setup = over_song_setup(songs, 0, demo3_starts())
        k = None
    elif kind == 'stereo':
        setup, want = stereo_setup(bank)
        k = ('stereo', want)
    elif kind == 'underrun':
        setup, k = underrun_setup(bank), 'underrun'
    else:
        setup, k = alone_setup(bank, False, VOL_MID, 'A'), None
    p, res, ex = checked(setup, 'pl', part)
    return p + scenario_problems(k, res, ex, None)


def hold_check(songs, part, tries=40) -> List[str]:
    setup = hold_setup(songs, tries)
    work = tmpdir('cal')
    try:
        res = run(setup._replace(actions=(), seconds=0.3), work, part)
        cal = res.byte('drv_cal') | res.byte('drv_cal', 1) << 8
    finally:
        shutil.rmtree(str(work), ignore_errors=True)
    p, res, ex = checked(hold_delays(setup, cal, tries), 'hold', part)
    return p if ex.held else p + ['no VBL landed with FX_HOLD set']


def planted(jobs: int = JOBS, out=print) -> List[str]:
    """Each planted bug in a scratch copy, built apart, must fail its
    scenarios. Returns the bugs that were not caught."""
    bank = bank_bytes()
    songs = [p.read_bytes() for p in song_files()]

    def one(entry):
        name, old, new, kinds = entry
        root = tmpdir('planted')
        try:
            src = planted_variant(name, old, new, root)
            m11 = root / 'm11'
            make(m11, src)
            caught = []
            for kind in kinds:
                p = scenario(kind, bank, songs, m11 / 'fxplay')
                if p:
                    caught.append('%s: %s' % (kind, p[0]))
            return name, caught
        except RunError as e:
            return name, ['(the run) %s' % str(e).splitlines()[0]]
        finally:
            shutil.rmtree(str(root), ignore_errors=True)
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        done = list(pool.map(one, PLANTED))
    missed = []
    for name, caught in done:
        out('%-58s %s' % (name, caught[0] if caught else 'NOT CAUGHT'))
        if not caught:
            missed.append(name)
    return missed


# ---------------------------------------------------------------------------

def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--cfg')
    parser.add_argument('--checkpoint', action='store_true')
    parser.add_argument('--quick', action='store_true')
    parser.add_argument('--cost', action='store_true')
    parser.add_argument('--timing', action='store_true')
    parser.add_argument('--planted', action='store_true')
    parser.add_argument('--jobs', type=int, default=JOBS)
    args = parser.parse_args(argv)
    if args.cfg:
        S.write_if_changed(Path(args.cfg), cfg_text())
        return 0
    if not have_build():
        print('no build: make -C src/native -f m11.mk part P=fxplay, and '
              'SFX.1 (part fxconv)', file=sys.stderr)
        return 2
    bad = 0
    if args.checkpoint:
        bad += len(checkpoint(args.jobs, args.quick))
    if args.cost:
        bad += len(cost(args.jobs))
    if args.timing:
        bad += len(timing(args.jobs))
    if args.planted:
        bad += len(planted(args.jobs))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
