#!/usr/bin/env python3
"""The tables of the 65C02 player (src/sound), as a ca65 include.

Usage:  python3 tools/sound/tables65.py LAYOUT OUT.inc

LAYOUT is native12 or mb6. Every value comes from tools/sound/tables.py,
the tables the player model (player.py) uses, so the 65C02 player and
its oracle cannot drift apart: the voices of the layout and the
registers the music owns, the period tables of the layout's card mode
for a PAL and an NTSC //e, the bend magnitudes, the attenuation-to-level
table and the tempo. tests/test_sound_player65.py reads the tables back
from the assembled player and compares them with tables.py.

Standard library only.
"""

import sys
from pathlib import Path

if __package__ in (None, ''):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sound import tables  # noqa: E402


def byte_lines(label, values, per_line=16):
    out = ['%s:' % label]
    values = list(values)
    for start in range(0, len(values), per_line):
        out.append('        .byte   ' + ', '.join(
            '$%02X' % v for v in values[start:start + per_line]))
    return out


def owned_list(layout):
    """The flush order: chips descending, each a marker $80 + chip, then
    its registers descending as indexes into want (chip x 16 + register);
    $FF ends. The burst walks each chip's writes backwards, so they reach
    the chip in ascending order, as player.flush writes them."""
    out = []
    for chip, regs in sorted(tables.owned_registers(layout).items(),
                             reverse=True):
        out.append(0x80 | chip)
        out.extend(chip * 16 + reg for reg in sorted(regs, reverse=True))
    return out + [0xFF]


def generate(layout_name):
    layout = tables.LAYOUTS[layout_name]
    pal, ntsc = tables.LAYOUT_MACHINES[layout_name]
    voices = tables.voices(layout)
    lines = ['; Generated by tools/sound/tables65.py %s from tools/sound/'
             'tables.py.' % layout_name,
             '; Do not edit: rerun the generator (src/sound/Makefile does).',
             '',
             'LAYOUT_ID       = %d' % layout.ident,
             'NV              = %d          ; music voices: melodic, then drums'
             % len(voices),
             'NMELODIC        = %d' % len(layout.melodic),
             'LAYOUT_CHIPS    = $%02X        ; bit c: chip c is in the layout'
             % sum(1 << c for c in layout.chips),
             'TEMPO_INT_PAL   = %d' % tables.tempo(pal)[0],
             'TEMPO_FRAC_PAL  = %d' % tables.tempo(pal)[1],
             'TEMPO_INT_NTSC  = %d' % tables.tempo(ntsc)[0],
             'TEMPO_FRAC_NTSC = %d' % tables.tempo(ntsc)[1],
             'ATT_MAX         = %d' % tables.ATT_MAX,
             'HW_DRUM_ATT     = %d' % tables.HW_DRUM_ATT,
             '']
    lines.append('.macro SND_VOICE_TABLES')
    lines += byte_lines('v_tone', [c * 16 + 2 * ch for c, ch in voices])
    lines += byte_lines('v_level', [c * 16 + 8 + ch for c, ch in voices])
    lines += byte_lines('v_base', [c * 16 for c, ch in voices])
    lines += byte_lines('v_chip', [c for c, ch in voices])
    lines += byte_lines('v_tonebit', [1 << ch for c, ch in voices])
    lines += byte_lines('v_noisebit', [8 << ch for c, ch in voices])
    lines += byte_lines('owned_list', owned_list(layout))
    lines.append('.endmacro')
    lines.append('')
    lines.append('.macro SND_PERIOD_TABLES')
    for name, machine in (('period_pal', pal), ('period_ntsc', ntsc)):
        table = tables.period_table(machine)
        lines.append('; %s: %s, PSG clock %d Hz; low bytes, then high bytes'
                     % (name, machine.name, tables.psg_clock(machine)))
        lines += byte_lines(name, [p & 0xff for p in table] +
                            [p >> 8 for p in table])
    lines.append('.endmacro')
    lines.append('')
    lines.append('.macro SND_LEVEL_TABLES')
    lines += byte_lines('bend_magnitude', tables.BEND_MAGNITUDE)
    lines += byte_lines('level_of_att', tables.LEVEL)
    lines.append('.endmacro')
    return '\n'.join(lines) + '\n'


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 2 or argv[0] not in tables.LAYOUTS:
        print(__doc__, file=sys.stderr)
        return 2
    Path(argv[1]).write_text(generate(argv[0]))
    return 0


if __name__ == '__main__':
    sys.exit(main())
