#!/usr/bin/env python3
"""a2vm runs of the channel logic (milestone 11, part fxchan;
docs/m11-parts/fxchan.md): the test machines of src/native/m11/fxchan.mk
under the driver src/native/fx_cdrv.s, many cases a run.

Usage:  python3 tools/native/fxcrun.py --cfg OUT      the ld65 map
        python3 tools/native/fxcrun.py --smoke         one case a build

The builds (fxchan.mk), each in build/native/m11/fxchan/<name>.*:

    fxc8    FXCH8: 8 channels (s2-fxch8.inc), isPlaying injected
            (fx_cdrv -D FCD_PLAY) and the positions from a table
            (-D FCD_POS): comparisons 1-3 of docs/SCREENS.md 3
    fxc8r   FXCH8 with fxplay's fx_isplaying (fx.s's card part
            assembled for FXCH8): comparison 4, the two-tic case
    fxc3    3 channels (s2.inc, the release's places), fxplay's
            fx_isplaying: against tools/sound/fxchan.py
    fxcm8   MENUW's object (-D FXC_NOSEP) with fx_pcache's s2t_pos,
            FXCH8, isPlaying injected: the paused frame

The machine (a2vm's W65C02S, the RTL's core): main $0800-$17FF the driver,
the channel logic and their data; $1DBE-$1DBF gamemap (llayout's
G_GAMEMAP); $2000-$5FFF the cases; $6000-$6FFF
the math's W part (the game's math.s, not the render subset); $7000-$BFFF
the out records; the card's bank 1 the quarter squares, MATHLC, MATHFAR;
the card's $E000 part the channel blocks of the build's s2.inc, and with
fx_isplaying S2's player and fx.s's card part at the game's places; the
math tables in RamWorks bank 120. Every byte the cases do not set is the
fill ($A5 by default).

A run is bounded: cycles, wall time, file sizes (bounded.run); its
directory is the caller's or a tempfile directory, deleted.
"""

import argparse
import json
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from a2vm import costs  # noqa: E402
from native import lrun, s2layout as S  # noqa: E402
from ref816 import bounded  # noqa: E402

ROOT = HERE.parent.parent
BUILD = ROOT / 'build'
M11 = BUILD / 'native' / 'm11'
PART = M11 / 'fxchan'
SOURCE = ROOT / 'src' / 'native'
A2VM = lrun.A2VM
MATH_TABLES = BUILD / 'native' / 'math' / 'tables'

MAIN = (0x0800, 0x1800)
CASES = (0x2000, 0x6000)           # (gamemap is main $1DBE)
WMATH = (0x6000, 0x7000)
OUTS = (0x7000, 0xC000)
MT_TBANK = 120
CYCLE_LIMIT = 400_000_000
RUN_TIMEOUT = 300.0
MAX_FILE = 64 << 20
OPS = {'start': 0, 'start2': 1, 'stop': 2, 'update': 3}
END = 0xFF
FILL = 0xA5
POS_MAX = 16
ASKS = 32
TRACES = 8

BUILDS = {
    'fxc8': dict(inc='fxch8', play=True, pos=True, card=False),
    'fxc8r': dict(inc='fxch8', play=False, pos=True, card=True),
    'fxc3': dict(inc='test', play=False, pos=True, card=True),
    'fxcm8': dict(inc='fxch8', play=True, pos=False, card=False),
}


class RunError(RuntimeError):
    pass


# ---------------------------------------------------------------------------
# The map
# ---------------------------------------------------------------------------

def cfg_text() -> str:
    card = {name: (lo, hi) for name, lo, hi in S.S2_CARD}

    def area(name, lo, hi, file, extra=''):
        return '    %-7s start = $%04X, size = $%04X, %sfile = %s;\n' % (
            name + ':', lo, hi - lo, extra, file)
    out = ('# Generated by tools/native/fxcrun.py --cfg (part fxchan).\n'
           '# Do not edit.\nMEMORY {\n')
    out += area('SNDZP', S.ZP_MUSIC[0], S.ZP_FXRING[0], '""', 'type = rw, ')
    out += area('MAIN', MAIN[0], MAIN[1], '"%O.main"', 'fill = yes, ')
    out += area('CASES', CASES[0], CASES[1], '""', 'type = rw, ')
    out += area('W', WMATH[0], WMATH[1], '"%O.w"')
    out += area('OUTS', OUTS[0], OUTS[1], '""', 'type = rw, ')
    out += area('LC1', 0xD800, 0xDC00, '"%O.lc1"')
    out += area('FAR', 0xDC00, 0xE000, '"%O.far"')
    for key, name in (('RING', 'the song ring and its mirror'),
                      ('LIST', 'the player\'s write lists'),
                      ('STATE', 'the player\'s state')):
        out += area(key, card[name][0], card[name][1], '""', 'type = rw, ')
    r = card['S2\'s code and tables']
    out += area('SND', r[0], r[1], '"%O.lc"', 'fill = yes, ')
    out += area('FXC', S.FX_CODE[0], S.FX_CODE[1], '"%O.lc"', 'fill = yes, ')
    out += '}\nSEGMENTS {\n'
    rows = [('SNDZP', 'SNDZP', 'type = zp, optional = yes'),
            ('DRVCODE', 'MAIN', 'type = ro'),
            ('S2CODE', 'MAIN', 'type = ro, define = yes'),
            ('S2RODATA', 'MAIN', 'type = ro, define = yes'),
            ('DRVDATA', 'MAIN', 'type = rw'),
            ('CASES', 'CASES', 'type = bss, define = yes'),
            ('MATHRND', 'W', 'type = ro, align = $100'),
            ('MATHW', 'W', 'type = ro'),
            ('OUTS', 'OUTS', 'type = bss, define = yes'),
            ('MATHLC', 'LC1', 'type = ro'),
            ('MATHFAR', 'FAR', 'type = ro'),
            ('SNDRING', 'RING', 'type = bss, align = $100, optional = yes'),
            ('SNDLIST', 'LIST', 'type = bss, optional = yes'),
            ('SNDBSS', 'STATE', 'type = bss, optional = yes'),
            ('SNDCODE', 'SND', 'type = ro, optional = yes'),
            ('SNDRODATA', 'SND', 'type = ro, optional = yes'),
            ('FXCODE', 'FXC', 'type = ro, define = yes, optional = yes')]
    for name, load, extra in rows:
        out += '    %-10s load = %s, %s;\n' % (name + ':', load, extra)
    return out + '}\n'


# ---------------------------------------------------------------------------
# A build
# ---------------------------------------------------------------------------

def make(part: Optional[Path] = None, source: Path = SOURCE,
         fxsrc: Optional[Path] = None) -> List[str]:
    """make -f m11.mk part P=fxchan into `part` (build/native/m11/fxchan),
    fx_chan.s, fx_pcache.s, fx_cdrv.s from `source` and fx.s from `fxsrc`
    (scratch copies for the planted bugs); fails on a warning or when
    s2layout.py's check fails (the shared includes are always remade)."""
    part = part or PART
    args = ['make', '-s', '-C', str(SOURCE), '-f', 'm11.mk', 'part',
            'P=fxchan', 'ROOT=%s' % ROOT, 'FXCHAN_DIR=%s' % part,
            'FXCSRC=%s' % source]
    if fxsrc is not None:
        args.append('FXSRC=%s' % fxsrc)
    notes: List[str] = []

    def go(extra):
        return bounded.run(args + extra, timeout=300, stdout=subprocess.PIPE,
                           stderr=subprocess.STDOUT, universal_newlines=True)
    result = go([])
    if result.returncode:
        raise RunError('the build failed:\n' + result.stdout[-3000:])
    if 'arning' in result.stdout:
        raise RunError('the build warns:\n' + result.stdout[-3000:])
    return notes


def use_part(part: Path) -> None:
    """Runs and loads from another build directory (a planted bug's)."""
    global PART
    PART = Path(part)


def read_labels(path: Path) -> Dict[str, int]:
    out = {}
    for line in path.read_text().splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] == 'al':
            out[parts[2].lstrip('.')] = int(parts[1], 16)
    return out


class Build(NamedTuple):
    name: str
    dir: Path
    labels: Dict[str, int]
    sc_base: int
    channels: int
    s2t_base: int
    files: Dict[str, bytes]


def load(name: str, part: Optional[Path] = None) -> Build:
    d = part or PART
    labels = read_labels(d / (name + '.lbl'))
    b = S.BUILDS[BUILDS[name]['inc']]
    files = {}
    for suffix in ('main', 'w', 'lc1', 'far', 'lc'):
        p = d / ('%s.%s' % (name, suffix))
        if p.exists():
            files[suffix] = p.read_bytes()
    return Build(name, d, labels, b.sc_base, b.channels, b.s2t_base, files)


def have(name: str, part: Optional[Path] = None) -> Optional[str]:
    """None when the build and the tools exist, else what is missing."""
    part = part or PART
    for p in (part / (name + '.lbl'), part / (name + '.main'), A2VM,
              MATH_TABLES / 'tanto0.bin', MATH_TABLES / 'squares.bin'):
        if not p.exists():
            return '%s is missing' % p
    return None


# ---------------------------------------------------------------------------
# Cases and runs
# ---------------------------------------------------------------------------

class Case(NamedTuple):
    op: str
    pokes: List[Tuple[int, bytes]]
    cont: bool = False          # goes on from the case before: same run


def encode(cases: Sequence[Case]) -> bytes:
    out = bytearray()
    for c in cases:
        pokes = []
        for at, data in c.pokes:
            for k in range(0, len(data), 255):
                pokes.append((at + k, data[k:k + 255]))
        if len(pokes) > 255:
            raise RunError('a case with %d pokes' % len(pokes))
        out += bytes([OPS[c.op], len(pokes)])
        for at, data in pokes:
            out += struct.pack('<HB', at, len(data)) + data
    out.append(END)
    return bytes(out)


# FM and the listener in the tic-side block (FM_X .. LS_ANGLE's end), then
# LS_ON and SND_SFXVOL after the mailboxes (s2layout SC_EXTRA, request
# FXCHAN-2 as integrated): an out record's s2t is the two runs joined
S2T_RUN = S.S2T['LS_ANGLE'] + 4 - S.S2T['FM_X']
S2T_TAIL = S2T_RUN + S.SC_EXTRA_SIZE


def extra_base(b: Build) -> int:
    return S.sc_extra_base(b.sc_base, b.channels)


def out_ranges(b: Build) -> List[Tuple[int, int]]:
    """The out records' ranges: the channel blocks; the scratch block;
    FM and the listener; LS_ON and SND_SFXVOL; the asks (FCD_POS)."""
    lab = b.labels
    s2t = b.s2t_base
    out = [(b.sc_base, b.channels * (S.CHAN_SIZE + S.MAIL_SIZE)),
           (lab['fxc_scr'], 32),
           (s2t + S.S2T['FM_X'], S2T_RUN),
           (extra_base(b), S.SC_EXTRA_SIZE),
           (lab['fcd_ntr'], 1 + 6 * TRACES)]
    if 'fcd_nask' in lab:
        out.append((lab['fcd_nask'], 1 + 2 * ASKS))
    return out


def record_size(b: Build) -> int:
    return sum(n for _, n in out_ranges(b))


def image_records(b: Build, cases: bytes, fill: int) -> bytes:
    lab = b.labels
    img = bytearray(b'A2VMIMG1')

    def rec(kind, bank, address, data):
        for k in range(0, len(data), 0x8000):
            chunk = data[k:k + 0x8000]
            img.extend(struct.pack('<BBHI', kind, bank, address + k,
                                   len(chunk)))
            img.extend(chunk)
    rec(0, 0, 0x0000, bytes([fill]) * 0xC000)       # main, poisoned
    rec(0, 0, 0x0000, bytes(0x100))                 # zero page 0
    rec(0, 0, 0x0300, bytes(0xF0))                  # the persistent globals
    rec(2, 0, 0xE000, bytes([fill]) * 0x2000)       # the card, poisoned
    rec(3, 0, 0xD000, bytes([fill]) * 0x1000)
    rec(3, 0, 0xD000, (MATH_TABLES / 'squares.bin').read_bytes())
    rec(3, 0, 0xD800, b.files['lc1'])
    rec(3, 0, 0xDC00, b.files['far'])
    rec(0, 0, MAIN[0], b.files['main'])
    rec(0, 0, WMATH[0], b.files['w'])
    if 'lc' in b.files:
        rec(2, 0, 0xE900, b.files['lc'])
    t = MT_TBANK
    rec(1, t, 0x2000, (MATH_TABLES / 'sinelo.bin').read_bytes())
    rec(1, t, 0x4000, (MATH_TABLES / 'sinehi.bin').read_bytes())
    for k in range(4):
        rec(1, t, 0x6000 + 0x900 * k,
            (MATH_TABLES / ('tanto%d.bin' % k)).read_bytes())
    rec(1, t, 0x8400, (MATH_TABLES / 'quartlo.bin').read_bytes())
    rec(1, t, 0x8C00, (MATH_TABLES / 'quarthi.bin').read_bytes())
    # the out ranges
    rng = out_ranges(b)
    rec(0, 0, lab['fcd_nout'], bytes([len(rng)]))
    rec(0, 0, lab['fcd_olo'], bytes(a & 0xFF for a, _ in rng))
    rec(0, 0, lab['fcd_ohi'], bytes(a >> 8 for a, _ in rng))
    rec(0, 0, lab['fcd_olen'], bytes(n for _, n in rng))
    rec(0, 0, lab['fcd_in'], cases)
    return bytes(img)


class Result(NamedTuple):
    records: List[bytes]        # each case's out record
    state: Dict
    cost_us: Optional[float]    # phase 30's time over the calls, us
    calls: int


def run_chunk(b: Build, cases: Sequence[Case], work: Path,
              profile: Optional[str] = None, fill: int = FILL) -> Result:
    lab = b.labels
    data = encode(cases)
    if len(data) > CASES[1] - CASES[0]:
        raise RunError('%d bytes of cases' % len(data))
    size = record_size(b)
    if size * len(cases) > OUTS[1] - OUTS[0]:
        raise RunError('%d out records do not fit' % len(cases))
    work.mkdir(parents=True, exist_ok=True)
    (work / 'fx.img').write_bytes(image_records(b, data, fill))
    (work / 'rom.bin').write_bytes(bytes(0x4000))
    last = OUTS[0] + max(1, size * len(cases)) - 1
    args = [str(A2VM), '--rom', str(work / 'rom.bin'), '--core', 'w65c02s',
            '--io-cycles', '0', '--image', str(work / 'fx.img'),
            '--switch', 'lc_read=1', '--switch', 'lc_write=1',
            '--switch', 'lc_bank2=0',
            '--reg', 'pc=%X' % lab['fcd_start'], '--reg', 'p=34',
            '--stop-pc', '%X' % lab['fcd_halt'],
            '--cycles', str(CYCLE_LIMIT),
            '--state', str(work / 'state.json'),
            '--snapshot-dir', str(work), '--final-snapshot',
            '--snapshot-ranges', 'main:%X-%X' % (OUTS[0], last)]
    report = work / 'cost.json'
    if profile:
        (work / 'cost.txt').write_text(costs.text(profile))
        args += ['--cost', str(work / 'cost.txt'), '--cost-timed',
                 '--cost-phase', '%X' % lab.get('PHASE', 0x0300),
                 '--cost-report', str(report)]
    try:
        r = bounded.run(args, timeout=RUN_TIMEOUT, max_bytes=MAX_FILE,
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                        universal_newlines=True)
    except subprocess.TimeoutExpired:
        raise RunError('a2vm did not finish in %d s' % RUN_TIMEOUT)
    sp = work / 'state.json'
    if r.returncode or not sp.exists():
        raise RunError('a2vm failed: %s' % r.stdout[-2000:])
    state = json.loads(sp.read_text())
    if state.get('pc') != lab['fcd_halt']:
        raise RunError('a2vm stopped at $%04X (%s), not at fcd_halt' % (
            state.get('pc', -1), state.get('end')))
    snap = None
    for p in sorted(work.glob('*.img')):
        if p.name != 'fx.img':
            snap = p
    if snap is None:
        raise RunError('no snapshot')
    mem = _main_of(snap.read_bytes())
    out = bytes(mem[OUTS[0]:OUTS[0] + size * len(cases)])
    records = [out[k * size:(k + 1) * size] for k in range(len(cases))]
    cost = None
    if profile and report.exists():
        text = report.read_text()
        c = json.loads(text[text.rfind('{"final"'):])['cost']
        mhz = costs.parameters(profile)['fabric_mhz']
        phase = (S.PHASE_2D if hasattr(S, 'PHASE_2D') else 30)
        cost = c['phases'][phase] / mhz / max(1, len(cases))
    return Result(records, state, cost, len(cases))


def _main_of(data: bytes) -> bytearray:
    if data[:8] != b'A2VMIMG1':
        raise RunError('not an A2VMIMG1 snapshot')
    mem = bytearray(0x10000)
    at = 8
    while at < len(data):
        kind, bank, address, length = struct.unpack_from('<BBHI', data, at)
        at += 8
        if kind == 0:
            mem[address:address + length] = data[at:at + length]
        at += length
    return mem


def chunks(b: Build, cases: Sequence[Case]) -> List[List[Case]]:
    """The cases cut into runs that fit (a sequence is never cut: a case
    marked cont stays with the one before)."""
    size = record_size(b)
    cap_out = (OUTS[1] - OUTS[0]) // size
    cap_in = CASES[1] - CASES[0] - 1
    out: List[List[Case]] = []
    cur: List[Case] = []
    used = 0
    groups: List[List[Case]] = []
    for c in cases:
        if not c.cont or not groups:
            groups.append([c])
        else:
            groups[-1].append(c)
    for g in groups:
        n = len(encode(g)) - 1
        if cur and (used + n > cap_in or len(cur) + len(g) > cap_out):
            out.append(cur)
            cur, used = [], 0
        if n > cap_in or len(g) > cap_out:
            raise RunError('a sequence of %d cases does not fit a run'
                           % len(g))
        cur += g
        used += n
    if cur:
        out.append(cur)
    return out


def run(b: Build, cases: Sequence[Case], profile: Optional[str] = None,
        fill: int = FILL, jobs: int = 2) -> Tuple[List[bytes], List[float]]:
    """Every case's out record (in order) and the runs' us a call."""
    parts = chunks(b, cases)
    PART.mkdir(parents=True, exist_ok=True)
    temp = Path(tempfile.mkdtemp(prefix='tmp-fxcrun-', dir=str(PART)))
    try:
        def one(k):
            return run_chunk(b, parts[k], temp / ('r%04d' % k), profile, fill)
        if jobs > 1 and len(parts) > 1:
            from concurrent.futures import ThreadPoolExecutor
            with ThreadPoolExecutor(max_workers=jobs) as ex:
                results = list(ex.map(one, range(len(parts))))
        else:
            results = [one(k) for k in range(len(parts))]
        for k in range(len(parts)):
            shutil.rmtree(str(temp / ('r%04d' % k)), ignore_errors=True)
    finally:
        shutil.rmtree(str(temp), ignore_errors=True)
    records = [r for res in results for r in res.records]
    costs_us = [res.cost_us for res in results if res.cost_us is not None]
    return records, costs_us


# ---------------------------------------------------------------------------
# The out record, decoded
# ---------------------------------------------------------------------------

class Out(NamedTuple):
    table: bytes                # the channel records
    mail: bytes                 # the mailboxes
    scratch: bytes
    s2t: bytes                  # FM_X .. LS_ANGLE, LS_ON, SND_SFXVOL
    trace: List[Tuple[int, int, int, int]]  # each adjust: c, aud, vol, sep
    asks: List[int]             # the handles s2t_pos was asked (FCD_POS)


def decode(b: Build, rec: bytes) -> Out:
    n = b.channels
    t = n * S.CHAN_SIZE
    at = n * (S.CHAN_SIZE + S.MAIL_SIZE)
    table, mail = rec[:t], rec[t:at]
    scratch = rec[at:at + 32]
    at += 32
    s2t = rec[at:at + S2T_TAIL]
    at += S2T_TAIL
    nt = rec[at]
    trace = []
    for i in range(min(nt, TRACES)):
        r = rec[at + 1 + 6 * i:at + 7 + 6 * i]
        trace.append((r[0], r[5], r[1] | r[2] << 8, r[3] | r[4] << 8))
    at += 1 + 6 * TRACES
    asks: List[int] = []
    if 'fcd_nask' in b.labels:
        na = rec[at]
        asks = [rec[at + 1 + 2 * i] | rec[at + 2 + 2 * i] << 8
                for i in range(min(na, ASKS))]
    return Out(table, mail, scratch, s2t, trace, asks)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--cfg', type=Path)
    args = ap.parse_args(argv)
    if args.cfg:
        text = cfg_text()
        if not (args.cfg.exists() and args.cfg.read_text() == text):
            args.cfg.parent.mkdir(parents=True, exist_ok=True)
            args.cfg.write_text(text)
        return 0
    ap.print_help()
    return 1


if __name__ == '__main__':
    sys.exit(main())
