#!/usr/bin/env python3
"""The playable game's links (docs/PLAY.md 4): the maps and the generated
includes that join the separately linked images. src/native/play.mk calls
it; tools/native/playdisk.py imports it.

Usage (play.mk's):
  python3 tools/native/playlink.py --symbols OUT/playsym.inc
  python3 tools/native/playlink.py --symbols2 OUT/playsym2.inc \\
          --images OUT/playimg.inc --play PLAY
  python3 tools/native/playlink.py --kernel OUT/playk.inc --play PLAY
  python3 tools/native/playlink.py --tic-cfg GAME.CFG GPLACE.INC OUT.cfg
  python3 tools/native/playlink.py --image-cfg P2DW OUT.cfg
  python3 tools/native/playlink.py --init-cfg OUT.cfg
  python3 tools/native/playlink.py --card-cfg OUT.cfg
  python3 tools/native/playlink.py --sizes --play PLAY

Each image of the game is its own ld65 link: milestone 8's render images
and card (build rcard), milestone 9's load image (build lcard),
milestone 11's 2D images (its parts' builds), and play.mk's own: P2DW
with the frame glue, DLINIT, the tic image with every built part and the
glue's groups, DOOM.SYSTEM's link with the kernel. An image calls another
by the address in that one's label file: playsym.inc (the others'),
playsym2.inc (P2DW's and DLINIT's), playk.inc (the tic image's, for the
kernel), each symbol XS_<name>. playimg.inc is each image's descriptor
for the kernel's K_LOAD: its bank, its page runs, 0.
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from native import llayout as LL, lrun, playlayout as PL, \
    render_check as RC, rlayout as R, s2layout as S, s2run  # noqa: E402

ROOT = HERE.parent.parent
BUILD = ROOT / 'build'
M11 = BUILD / 'native' / 'm11'
RCARD = RC.OBJ                  # milestone 8's rcard (read only)
LCARD = lrun.OBJ                # milestone 9's lcard (read only)
PLBOOT = M11 / 'plboot'         # milestone 11's DOOM.SYSTEM link (read)

# milestone 11's 2D images: image -> (part, build), the parts' builds
# (docs/m11-parts/design.md R7 item 14: the release links of these images
# are the parts' objects without their test glue; until then the parts'
# builds, as pldisk.py's IMAGE_BUILDS); P2DW is play.mk's own
M11_IMAGES = {'MENUW': ('s2menu2', 's2m2'), 'AMAPW': ('s2amap', 'amw'),
              'WIW': ('s2wi', 'wiw'), 'FINW': ('s2fin', 'finw'),
              'PALW': ('s2pal', 'palw')}
OVLW_BUILD = ('s2ovl', 'ovlw')

# the symbols each image gives the others (playsym.inc)
RCARD_SYMS = ('far_get', 'far_put', 'far_pload', 'far_wload', 'far_mload',
              'nr_frame', 'nm_masked', 'nm_bkload', 'nb_frame',
              'nat_replay')    # (the benchmark's timing patches its entry)
LCARD_SYMS = ('nl_setup',)
IMAGE_SYMS = {'MENUW': ('m_load', 'm_save', 'm_init', 'm_startcp',
                        'm_responder', 'm_ticker', 'm_frame',
                        'm_savedone'),
              'AMAPW': ('am_frame', 'am_load', 'am_save', 'am_responder'),
              'WIW': ('wi_frame', 'wi_init'),
              'FINW': ('fin_frame', 'fin_load', 'fin_signon', 'fin_signoff',
                       'fin_init'),
              'PALW': ('palw_level', 'palw_gamma')}
CARD_SYMS = ('pl_time', 'fx_song', 'fx_isplaying', 'fx_stopall',
             'snd_stop', 'snd_song_bank', 'snd_song_addr',
             'snd_song_flags', 'snd_song_matt', 'vbl_count', 'pl_crash',
             'pl_vbl')
P2DW_SYMS = ('s2_frame', 's2_poll')
INIT_SYMS = ('dli_main', 'dli_quit')
TIC_SYMS = ('fc_go', 'dl_brain')

GROUP_SIZE = 0x0800
SLOTS = {1: 0x9E00, 2: 0xA600}


class LinkError(Exception):
    pass


def labels_of(obj: Path, name: str) -> Dict[str, int]:
    return RC.load_build(obj, name).labels


def pick(labels: Dict[str, int], names: Sequence[str], what: str
         ) -> List[Tuple[str, int]]:
    out = []
    for n in names:
        if n not in labels:
            raise LinkError('%s has no %s' % (what, n))
        out.append((n, labels[n]))
    return out


def m11_build(image: str, m11: Path = M11) -> s2run.Build:
    part, name = M11_IMAGES[image]
    return s2run.load_build(m11 / part, name, image)


def inc_lines(pairs: Sequence[Tuple[str, int]], head: str) -> str:
    out = ['; Generated by tools/native/playlink.py (docs/PLAY.md 4): %s. '
           'Do not edit.' % head, '']
    for name, value in pairs:
        out.append('XS_%-20s = $%04X' % (name, value))
    return '\n'.join(out) + '\n'


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


# ---------------------------------------------------------------------------
# playsym.inc: the others' links
# ---------------------------------------------------------------------------

def symbols(m11: Path = M11) -> List[Tuple[str, int]]:
    out = pick(labels_of(RCARD, 'rcard'), RCARD_SYMS, 'rcard')
    out += pick(labels_of(LCARD, 'lcard'), LCARD_SYMS, 'lcard')
    for image, names in IMAGE_SYMS.items():
        out += pick(m11_build(image, m11).labels, names, image)
    out += pick(labels_of(m11 / 'plboot', 'plboot'), CARD_SYMS,
                'DOOM.SYSTEM\'s link')
    return out


# ---------------------------------------------------------------------------
# The images: banks and page runs (far_pload's lists)
# ---------------------------------------------------------------------------

class Load(NamedTuple):
    name: str
    bank: int
    runs: Tuple[Tuple[int, int], ...]


def runs_of(lo: int, end: int) -> Tuple[Tuple[int, int], ...]:
    return tuple(s2run.runs_of(lo, end))


def p2dw_build(play: Path) -> s2run.Build:
    return s2run.load_build(play / 'p2dw', 'p2dw', 'P2DW')


def init_build(play: Path) -> RC.Build:
    return RC.load_build(play / 'init', 'init')


def init_bytes(play: Path) -> bytes:
    b = init_build(play)
    lo, hi = b.segments['DLINIT']
    data = (b.obj / 'init.img').read_bytes()
    return data[:hi + 1 - PL.DLINIT_LO]


def lcode_load() -> Load:
    lb = RC.load_build(LCARD, 'lcard')
    lo, hi = lb.segments['LOADW']
    return Load('lcode', LL.LCODE, ((0x60, ((hi + 0x100) >> 8) - 0x60),))


def ovlw_bytes(m11: Path = M11) -> bytes:
    part, name = OVLW_BUILD
    return (m11 / part / ('%s.ovw' % name)).read_bytes()


def loads(play: Path, m11: Path = M11) -> List[Load]:
    out = [Load('p2dw', S.image_banks()['P2DW'],
                runs_of(*s2run.stored_extent(p2dw_build(play))))]
    for image in ('MENUW', 'AMAPW', 'WIW', 'FINW', 'PALW'):
        b = m11_build(image, m11)
        out.append(Load(image.lower(), S.image_banks()[image],
                        runs_of(*s2run.stored_extent(b))))
    ov = S.IMAGE['OVLW'].stored[0]
    out.append(Load('ovlw', S.OVLW_BANK,
                    runs_of(ov, ov + len(ovlw_bytes(m11)))))
    out.append(lcode_load())
    out.append(Load('dlinit', PL.DLBANK,
                    runs_of(PL.DLINIT_LO,
                            PL.DLINIT_LO + len(init_bytes(play)))))
    return out


def images_inc(play: Path, m11: Path = M11) -> str:
    out = ['; Generated by tools/native/playlink.py (docs/PLAY.md 4): each '
           'image\'s bank and page runs', '; (K_LOAD\'s descriptors). Do '
           'not edit.', '']
    for ld in loads(play, m11):
        runs = ', '.join('$%02X, %d' % r for r in ld.runs)
        out.append('img_%s: .byte $%02X, %s, 0' % (ld.name, ld.bank, runs))
    return '\n'.join(out) + '\n'


def symbols2(play: Path) -> List[Tuple[str, int]]:
    out = pick(p2dw_build(play).labels, P2DW_SYMS, 'P2DW')
    out += pick(init_build(play).labels, INIT_SYMS, 'DLINIT')
    return out


# ---------------------------------------------------------------------------
# The tic image
# ---------------------------------------------------------------------------

def gplace_groups(gplace: Path) -> int:
    m = re.search(r'^GROUPS = (\d+)$', gplace.read_text(), re.M)
    if not m:
        raise LinkError('%s has no GROUPS' % gplace)
    return int(m.group(1))


def tic_cfg(game_cfg: str, groups: int) -> str:
    """glayout.py's game.cfg with the glue's groups after its own: their
    memory areas (at their slots' addresses, their own files) and the
    segments of the glue and of milestone 11's tic-side modules."""
    lines = game_cfg.splitlines()
    mem, seg = [], []
    names = {}
    for name, off, slot in PL.DL_GROUPS:
        n = groups + off
        names[name] = n
        mem.append('    G%d:   start = $%04X, size = $%04X, file = "%%O.g%d";'
                   % (n, SLOTS[slot], GROUP_SIZE, n))
    seg_of = {'DLG_B': ['DLGB'], 'DLG_C': ['DLGC'], 'DLG_D': ['DLGD'],
              'DLG_H': ['DLGH', 'S2CODE', 'S2RODATA'],
              'DLG_S': ['DLGS', 'S2TCODE', 'S2TRODATA']}
    for name, segs in seg_of.items():
        for s in segs:
            seg.append('    %-9s load = G%d, type = rw, define = yes, '
                       'optional = yes;' % (s + ':', names[name]))
    out = []
    for line in lines:
        if line.strip().startswith('LC1:'):
            out += mem
        if line.strip().startswith('DRIVER:'):
            out += seg
            line = line.replace('type = rw;', 'type = rw, optional = yes;')
        if line.strip().startswith('DESC:'):
            line = line.replace('define = yes;',
                                'define = yes, optional = yes;')
        out.append(line)
    text = '\n'.join(out) + '\n'
    if text.count('G%d:' % (groups + 1)) != 1:
        raise LinkError('the glue\'s groups are not in game.cfg\'s map')
    return text.replace('# Generated by tools/native/glayout.py',
                        '# Generated by tools/native/playlink.py from '
                        'glayout.py\'s game.cfg (docs/PLAY.md 4);\n# '
                        'glayout.py\'s header:', 1)


def tic_build(play: Path) -> RC.Build:
    return RC.load_build(play / 'tic', 'tic')


def core_end(b: RC.Build) -> int:
    return max(b.segments[s][1] for s in ('GCORE', 'LOADW')
               if s in b.segments) + 1


def kernel_symbols(play: Path) -> List[Tuple[str, int]]:
    b = tic_build(play)
    out = pick(b.labels, TIC_SYMS, 'the tic image')
    groups = gplace_groups(play / 'tic' / 'gen' / 'gplace.inc')
    out.append(('DLG_BRAIN', groups + dict((n, o) for n, o, _ in
                                           PL.DL_GROUPS)['DLG_B']))
    out.append(('CORE_PAGES', ((core_end(b) + 0xFF) >> 8) - 0x60))
    return out


# ---------------------------------------------------------------------------
# The other maps
# ---------------------------------------------------------------------------

def image_cfg(image: str) -> str:
    """s2layout.py's map of a 2D image without a test driver: its card
    segments optional."""
    text = S.cfg_text(image)
    text = text.replace('DRIVER:    load = LCE, type = rw, define = yes;',
                        'DRIVER:    load = LCE, type = rw, define = yes, '
                        'optional = yes;')
    text = text.replace('DESC:      load = LCE, type = bss, define = yes, '
                        'align = $100;',
                        'DESC:      load = LCE, type = bss, define = yes, '
                        'align = $100, optional = yes;')
    return text


def init_cfg() -> str:
    return '\n'.join([
        '# Generated by tools/native/playlink.py (docs/PLAY.md 3): DLINIT.',
        'MEMORY {',
        '    W:    start = $%04X, size = $%04X, file = "%%O.img";' % (
            PL.DLINIT_LO, PL.DLINIT_HI - 0x200 - PL.DLINIT_LO),
        '}', 'SEGMENTS {',
        '    DLINIT:  load = W, type = rw, define = yes;',
        '}', ''])


def card_cfg() -> str:
    """DOOM.SYSTEM's link (pldisk.py's map) with the kernel in the
    platform's $FF00 part and pl_ready's segment PLRES in a discarded area
    at the same place: the boot's jmp pl_ready reaches the kernel."""
    from native import pldisk
    text = pldisk.cfg_text()
    plat = S.PLATFORM_CARD[1]
    text = text.replace(
        'MEMORY {', 'MEMORY {\n    PLRESX: start = $%04X, size = $0008, '
        'type = rw, file = "";\n    KMAIN:  start = $%04X, size = $%04X, '
        'file = "%%O.k08";\n    KMAIN2: start = $%04X, size = $%04X, '
        'file = "%%O.k0b";' % (plat, PL.KMAIN[0], PL.KMAIN[1] - PL.KMAIN[0],
                               PL.KMAIN2[0], PL.KMAIN2[1] - PL.KMAIN2[0]),
        1)
    text = text.replace('    PLRES:     load = PLAT,  type = ro, '
                        'define = yes;',
                        '    PLRES:     load = PLRESX, type = ro, '
                        'define = yes;\n    DLKERN:    load = PLAT,  '
                        'type = rw, define = yes;\n    DLKMAIN:   load = '
                        'KMAIN, type = ro, define = yes;\n    DLKMAIN2:  '
                        'load = KMAIN2, type = ro, define = yes;')
    if 'DLKERN' not in text:
        raise LinkError('pldisk.cfg_text() has no PLRES line to replace')
    return text.replace('# Generated by tools/native/pldisk.py --cfg',
                        '# Generated by tools/native/playlink.py from '
                        'pldisk.py\'s map (the kernel at $FF00);\n#', 1)


def card_build(play: Path) -> RC.Build:
    return RC.load_build(play / 'card', 'plboot')


def card_problems(play: Path, m11: Path = M11) -> List[str]:
    """The card's symbols the other images use at the m11 link's addresses
    must be the play link's (only the kernel differs between the two);
    the kernel at pl_ready's place, inside its room."""
    out = []
    mine = card_build(play)
    theirs = labels_of(m11 / 'plboot', 'plboot')
    for n in CARD_SYMS:
        if mine.labels.get(n) != theirs.get(n):
            out.append('the card\'s %s: $%04X in the play link, $%04X in '
                       'm11\'s' % (n, mine.labels.get(n, 0),
                                   theirs.get(n, 0)))
    if mine.labels.get('dl_kernel') != theirs.get('pl_ready'):
        out.append('the kernel is not at pl_ready\'s place')
    lo, hi = mine.segments['DLKERN']
    if lo != PL.KERNEL[0] or hi >= PL.KERNEL[1]:
        out.append('the kernel $%04X-$%04X passes $%04X-$%04X' % (
            lo, hi, PL.KERNEL[0], PL.KERNEL[1] - 1))
    return out


def sizes(play: Path) -> List[str]:
    out = []
    tb = tic_build(play)
    groups = gplace_groups(play / 'tic' / 'gen' / 'gplace.inc')
    end = core_end(tb)
    out.append('tic image: the core $6600-$%04X, %d of %d B' % (
        end - 1, end - 0x6600, 0x9A00 - 0x6600))
    for name, off, slot in PL.DL_GROUPS:
        n = groups + off
        data = tb.obj / ('tic.g%d' % n)
        used = data.stat().st_size if data.exists() else 0
        out.append('  group %s (G%d, slot %d): %d of %d B' % (
            name, n, slot, used, GROUP_SIZE))
    cb = card_build(play)
    lo, hi = cb.segments['DLKERN']
    out.append('kernel $%04X-$%04X: %d of %d B' % (
        lo, hi, hi + 1 - lo, PL.KERNEL[1] - PL.KERNEL[0]))
    pb = p2dw_build(play)
    lo, end = s2run.stored_extent(pb)
    out.append('P2DW $6600-$%04X: %d of %d B' % (
        end - 1, end - 0x6600, S.IMAGE['P2DW'].stored[1] - 0x6600))
    ib = init_bytes(play)
    out.append('DLINIT: %d B' % len(ib))
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--symbols', type=Path)
    parser.add_argument('--symbols2', type=Path)
    parser.add_argument('--images', type=Path)
    parser.add_argument('--kernel', type=Path)
    parser.add_argument('--tic-cfg', nargs=3, type=Path)
    parser.add_argument('--image-cfg', nargs=2)
    parser.add_argument('--init-cfg', type=Path)
    parser.add_argument('--card-cfg', type=Path)
    parser.add_argument('--sizes', action='store_true')
    parser.add_argument('--play', type=Path,
                        default=BUILD / 'native' / 'play')
    args = parser.parse_args(argv)
    try:
        if args.symbols:
            write_if_changed(args.symbols, inc_lines(
                symbols(), 'the other milestones\' links'))
        if args.symbols2:
            write_if_changed(args.symbols2, inc_lines(
                symbols2(args.play), 'P2DW\'s and DLINIT\'s links'))
        if args.images:
            write_if_changed(args.images, images_inc(args.play))
        if args.kernel:
            write_if_changed(args.kernel, inc_lines(
                kernel_symbols(args.play), 'the tic image\'s link'))
        if args.tic_cfg:
            game, gplace, out = args.tic_cfg
            write_if_changed(out, tic_cfg(game.read_text(),
                                          gplace_groups(gplace)))
        if args.image_cfg:
            image, out = args.image_cfg
            write_if_changed(Path(out), image_cfg(image))
        if args.init_cfg:
            write_if_changed(args.init_cfg, init_cfg())
        if args.card_cfg:
            write_if_changed(args.card_cfg, card_cfg())
        if args.sizes:
            print('\n'.join(sizes(args.play)))
            problems = card_problems(args.play)
            for p in problems:
                print('playlink: %s' % p, file=sys.stderr)
            if problems:
                return 1
    except (LinkError, OSError, KeyError) as e:
        print('playlink: %s' % e, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
