#!/usr/bin/env python3
"""The finale's generated include (`--inc OUT`, s2fin.inc) for FINW
(src/native/s2_fin.s): the pictures' lump numbers in the release, the
finale's game state, the end text's length, and the font '!' .. '_' with
each glyph's place in the 2D store and its width.

Usage:  python3 tools/native/s2fin.py --inc OUT
"""

import argparse
import json
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional, Sequence

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

ROOT = HERE.parent.parent
BUILD = ROOT / 'build'
M11 = BUILD / 'native' / 'm11'
FONT = (0x21, 0x5F)             # '!' .. '_'


class FinError(Exception):
    pass


# ---------------------------------------------------------------------------
# The generated include
# ---------------------------------------------------------------------------

def release():
    from native import umodel as U
    return U.Release()


def const_of(name: str) -> int:
    """A CONST_* of upstream's offsets.inc."""
    path = BUILD / 'upstream' / 'src' / 'iigs' / 'offsets.inc'
    for line in path.read_text().splitlines():
        f = line.split()
        if len(f) >= 3 and f[0] == name and f[1] == '.equ':
            return int(f[2], 0)
    raise FinError('%s is not in %s' % (name, path))


def e1text() -> bytes:
    """The end text's bytes in the release (f_finale65.s's e1text ..
    e1end)."""
    from native import s2cap as C
    a, e = C.sym('f_finale65.s:e1text'), C.sym('f_finale65.s:e1end')
    return C.code().get(a, e - a)


class Glyph(NamedTuple):
    char: int
    bank: int
    address: int
    width: int
    height: int
    top: int


def font() -> List[Glyph]:
    """'!' .. '_': each glyph's place in the 2D store (part s2data's
    manifest) and its patch's width, height and top offset (DOOM1.WAD's)."""
    from native import s2data as D
    path = M11 / 's2data' / 's2data.json'
    if not path.exists():
        raise FinError('%s is missing: make -C src/native -f m11.mk part '
                       'P=s2data' % path)
    lumps = {x['name']: x for x in json.loads(path.read_text())['lumps']}
    wad = D.read_wad()
    out = []
    for c in range(FONT[0], FONT[1] + 1):
        name = 'STCFN%03d' % c
        p = D.parse_patch(wad[name])
        x = lumps[name]
        out.append(Glyph(c, x['bank'], x['address'], p.width, p.height,
                         p.top))
    return out


def inc_text() -> str:
    rel = release()
    gs = font()
    bad = [g for g in gs if g.top > 0 or g.height - g.top > 8 or
           g.width > 63]
    if bad:     # s2_fin.s's GLYPH_H and its width arithmetic
        raise FinError('a glyph s2_fin.s cannot band: %r' % (bad[0],))
    lines = ['; Generated by tools/native/s2fin.py (part s2fin, '
             'docs/SCREENS.md). Do not edit.', '',
             '; the pictures\' lump numbers in the release (upstream\'s '
             'picturenum, PALST\'s PS_PICTURE)',
             'FIN_HELP2NUM    = $%04X' % rel.index('HELP2'),
             'FIN_TITLENUM    = $%04X' % rel.index('TITLEPIC'),
             '; offsets.inc\'s CONST_GS_FINALE; the end text\'s length '
             '(e1end - e1text)',
             'FIN_GS_FINALE   = $%04X' % const_of('CONST_GS_FINALE'),
             'FIN_E1LENGTH    = %d' % len(e1text()),
             '; the font \'!\' .. \'_\': each glyph\'s bank, address and '
             'width']
    for i, g in enumerate(gs):
        lines.append('FIN_FB_%d = %d' % (i, g.bank))
        lines.append('FIN_FA_%d = $%04X' % (i, g.address))
        lines.append('FIN_FW_%d = %d' % (i, g.width))
    return '\n'.join(lines) + '\n'


def write_inc(path: Path) -> None:
    text = inc_text()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text)
    tmp.replace(path)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--inc', type=Path, required=True)
    args = ap.parse_args(argv)
    write_inc(args.inc)
    return 0


if __name__ == '__main__':
    sys.exit(main())
