#!/usr/bin/env python3
"""Part s2menu2 of milestone 11's first half (docs/SCREENS.md 1.5.3, 4.1,
6.2, 6.3, 7.3; docs/m11-parts/s2menu2.md): the settings pages' values,
the key setup, the load and save pages' slots and the benchmark's result
in MENUW (src/native/s2_menu2.s), their generated include and their
checkpoint.

The include (`--inc OUT`, gen/s2menu2.inc): the load and save pages'
titles' x (centerPatch: 160 - width / 2 of M_LOADG and M_SAVEG, from the
2D store's headers) and the music's byte in SS_SETTINGS (the field map's
snd_MusicVolume). M_BFPS, the benchmark's FPS text in MENUW's state
block, is s2.inc's since wave 6's integration (request S2MENU2-1).

The checkpoint (`--capture`, `--check`, `--timing`, `--planted`, `--all`;
docs/m11-parts/s2menu2.md section 2) runs the MENUW image with both menu
parts (s2m2t: since wave 6's integration the same objects as part
s2menu1's s2m1t, request S2MENU2-3) on the reference's frames:
  - run A, part s2cap's menus cases: every frame and close, both fills
    (the whole screen: pixels, SCBs, palettes), and each session chained,
    but the key setup page's frames redrawn whole, whose names are
    upstream's ADB ones there (X-K, compared on runs K1 and K2);
  - run K1 (SCREENS.md 6.2 as written): menus.script to the key setup
    page, with the //e names and table (part plinput's plkeys) poked 1:1
    into ref816's keyNames and keyTable at uiDisplay's entry the first
    time the key setup is up; its key setup frames;
  - run K2: the whole menus.script with the //e names poked into keyNames
    at the main loop's first display (the bindings stay upstream's ADB
    table, so the script's keys work: the binding to Q and the defaults
    back are drawn); each key setup frame with its keyTable's Doom keys
    injected 1:1 into PL_KEYTAB;
  - run B: the menu opened over the title with the benchmark's result
    poked (messageToPrint, messageKind MSG_BENCH, menuversion, VW_BTXT)
    at uiDisplay's entry: the result's frame, the CPU, CACHE and ROM rows
    excluded (X2) and black natively.

Usage:  python3 tools/native/s2menu2.py --inc OUT/s2menu2.inc
        python3 tools/native/s2menu2.py --all [--jobs 2]
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from native import s2layout as S  # noqa: E402
from native import s2menu1 as M1  # noqa: E402

ROOT = HERE.parent.parent
BUILD = ROOT / 'build'
M11 = BUILD / 'native' / 'm11'
OUT = M11 / 's2menu2'
CASES = OUT / 'cases'

# s2menu1's checkpoint machinery, with its call log captured into this
# part's own directory (never into part s2menu1's)
M1.CAP = OUT / 'cap'
M1.CALLS_FILE = M1.CAP / 'menus-calls.json.z'


class Menu2Error(Exception):
    pass


# ---------------------------------------------------------------------------
# The include
# ---------------------------------------------------------------------------

# MENUW's native state field this part asked for (request S2MENU2-1,
# applied in wave 6: s2layout's MENUW_NATIVE): the benchmark's FPS text,
# 0-terminated ("x.xxx" [R m_menu65.s:2467-2482]: at most 7 characters);
# and the play build's phase rows over X2 (docs/PLAY.md 15: 3 x 32 B,
# drawn when not empty), which these cases leave empty: the rows black
MENU2_NATIVE = [('M_BFPS', 8), ('M_BROWS', 96)]
FONT_H = 7


def native_places() -> Dict[str, int]:
    """This part's native places in MENUW's state block (s2layout's)."""
    used = S.state_places('MENUW')
    return {name: used[name] for name, _ in MENU2_NATIVE}


def title_x(width: int) -> int:
    """centerPatch [R m_menu65.s:1248-1258]: 160 - width / 2."""
    return 160 - (width >> 1)


def inc_text() -> str:
    ps = M1.patches()
    lines = ['; Generated by tools/native/s2menu2.py --inc (part s2menu2, '
             'docs/m11-parts/s2menu2.md). Do not edit.', '',
             '; drawSlots\' titles centred (centerPatch: 160 - width / 2)']
    for name in ('M_LOADG', 'M_SAVEG'):
        x = title_x(ps[name].width)
        if not 0 <= x < 256:
            raise Menu2Error('%s at x %d' % (name, x))
        lines.append('M2_%s_X     = %d ; %s %d wide' % (name[2:], x, name,
                                                       ps[name].width))
    lines += ['', '; snd_MusicVolume\'s byte in SS_SETTINGS (the field map\'s, '
              'request S2MENU2-2)',
              'SET_MUSVOL      = %d' % settings_places()[MUSIC_FIELD]]
    return '\n'.join(lines) + '\n'


# snd_MusicVolume [R s_sound65.s] in the settings that persist: the
# field map's SS_SETTINGS+5 (request S2MENU2-2, applied in wave 6; s2_menu.s
# has the same SET_MUSVOL)
MUSIC_FIELD = 's_sound65.s:snd_MusicVolume'
SET_MUSVOL = 5


def settings_places() -> Dict[str, int]:
    """The field map's SS_SETTINGS bytes by their upstream symbol."""
    out = {}
    for f in S.field_map():
        place = getattr(f, 'place', '')
        if isinstance(place, str) and place.startswith('SS_SETTINGS+'):
            out[f.ref] = int(place.split('+')[1])
    return out


# the release's menuNum (MUSIC_MENU 1: the display page's 4 rows, the sound
# page's 2), s2_menu.s's t_num since request S2MENU2-2 (wave 6)
MENU1_NUM = 't_num:   .byte 6, 5, 8, 5, 11, 8, 4, 2, 5\n'


# ---------------------------------------------------------------------------
# The reference's runs (s2cap's capture, run into this part's directory)
# ---------------------------------------------------------------------------

MENU_KEYS = 8                   # currentMenu of the key setup
MSG_BENCH = 16
PAGE_OF = {4: 'load', 8: 'key setup', 10: 'save', 12: 'display & sound',
           16: 'controls'}
# the benchmark's result poked (bmDone's text: the view's label, the FPS,
# then three rows of the dropped accelerators [R m_menu65.s:2457-2533])
BENCH_TEXT = b'FULL\n12.345\nZIPGS 8.00 MHZ\n16 KB\n3'
BENCH_FPS = b'12.345'
RUNS = ('k1', 'k2', 'bench')


def run_root(run: str) -> Path:
    return CASES / run


def _cut_script(stop_after: str) -> str:
    """menus.script up to the line `stop_after` (kept), then a 3 s wait
    and the stop."""
    text = (ROOT / 'coverage' / 'm11' / 'menus.script').read_text()
    at = text.index(stop_after)
    return text[:at] + stop_after + '\nat +3s stop\n'


def bench_script() -> str:
    return ('# the menu over the title, its frame redrawn whole with the\n'
            '# benchmark\'s result poked (tools/native/s2menu2.py)\n'
            'wait d_main65.s:pagedrawn == 1 within 90s\n'
            'at +10f press escape\n'
            'wait _g_menuactive == 1 within 10s\n'
            'wait m_menu65.s:messageToPrint == 1 within 10s\n'
            'at +3s stop\n')


def _poke_lines(point: str, items: Sequence[Tuple[int, bytes]]) -> List[str]:
    out = []
    for at, data in items:
        for off in range(0, len(data), 64):
            out.append('%s %06X %s' % (point, at + off,
                                       data[off:off + 64].hex()))
    return out


def pokes(run: str) -> Tuple[str, str]:
    """(the script, the poke file) of a run."""
    from native import s2cap as C, s2state as T
    names, table = T.apple2e_keys()
    ui = C.sym('i_viigs65.s:uiDisplay')
    if run == 'k1':
        point = 'pc=%06X,if=%06X:2:eq:%d,hits=1' % (
            ui, C.sym('m_menu65.s:currentMenu'), MENU_KEYS)
        return (_cut_script('wait m_menu65.s:currentMenu == 8 within 10s'),
                T.keys_poke(names, table, point))
    if run == 'k2':
        text = T.keys_poke(names, table)
        # (the names alone: keyTable's lines dropped, each line one range)
        tb = C.sym('i_iigs65.s:keyTable')
        keep = [x for x in text.splitlines() if x.startswith('#') or
                not (tb <= int(x.split()[1], 16) < tb + 256)]
        return ((ROOT / 'coverage' / 'm11' / 'menus.script').read_text(),
                '\n'.join(keep) + '\n')
    if run == 'bench':
        point = 'pc=%06X,if=%06X:2:eq:1,hits=1' % (
            ui, C.sym('m_menu65.s:_g_menuactive'))
        items = [(C.sym('m_menu65.s:messageToPrint'), b'\x01\x00'),
                 (C.sym('m_menu65.s:messageKind'),
                  bytes([MSG_BENCH, 0])),
                 (C.sym('m_menu65.s:menuversion'), b'\x77\x00'),
                 (C.sym('VW_BTXT'), BENCH_TEXT + b'\x00')]
        return (bench_script(),
                '# the benchmark\'s result (tools/native/s2menu2.py)\n' +
                '\n'.join(_poke_lines(point, items)) + '\n')
    raise Menu2Error('no run %s' % run)


def capture(runs: Sequence[str] = RUNS) -> Dict[str, Dict]:
    """Each run on ref816 through part s2cap's capture (the points of
    SCREENS.md 6.1, streamed and distilled) into CASES/<run>, with its
    script and pokes; and s2menu1's call log of menus.script into
    OUT/cap. The runs' files are deleted."""
    import shutil
    import tempfile
    from native import s2cap as C
    C.check_disk(BUILD)
    OUT.mkdir(parents=True, exist_ok=True)
    out = {}
    work = Path(tempfile.mkdtemp(prefix='tmp-cap-', dir=str(OUT)))
    try:
        for run in runs:
            script, poke = pokes(run)
            sp = work / (run + '.script')
            sp.write_text(script)
            pp = work / (run + '.poke')
            pp.write_text(poke)
            idx = C.capture('menus', run_root(run), work_root=work,
                            pokes=pp, script_path=sp)
            if idx['problems']:
                raise Menu2Error('the capture of %s: %s'
                                 % (run, idx['problems'][:3]))
            out[run] = {'frames': len(idx['frames']),
                        'events': len(idx['events'])}
    finally:
        shutil.rmtree(str(work), ignore_errors=True)
    M1.capture()
    return out


def ready_cases(run: str) -> Path:
    from native import s2cap as C
    root = C.run_dir('menus') if run == 'a' else run_root(run)
    if not (root / 'index.json').exists():
        raise Menu2Error('%s is missing: python3 tools/native/s2menu2.py '
                         '--capture (run A: tools/native/s2cap.py '
                         '--capture)' % root)
    return root



# ---------------------------------------------------------------------------
# The jobs: s2menu1's (part s2cap's cases, menu_jobs), chosen and injected
# with what this part's pages read beyond s2menu1's injection
# ---------------------------------------------------------------------------

X_K = 'X-K: the key setup page drawn with upstream\'s ADB names (runs K1, K2)'


class MJob(NamedTuple):
    run: str
    page: str                   # what is up: a page's name, or a message
    job: object                 # s2menu1.Job


def page_of(d) -> Tuple[int, int, int]:
    return (M1.uval(d, 'm_menu65.s:currentMenu'),
            M1.uval(d, 'm_menu65.s:messageToPrint'),
            M1.uval(d, 'm_menu65.s:messageKind'))


def page_name(d) -> str:
    menu, msg, kind = page_of(d)
    if msg:
        return 'benchmark' if kind == MSG_BENCH else 'message %d' % kind
    return M1.PAGE_NAMES.get(menu, 'page %d' % menu)


def jobs_of(run: str, setchg: Dict[str, int]) -> List[MJob]:
    """The run's jobs this part compares: run A all of s2menu1's (both
    parts' pages; the key setup's frames redrawn whole excluded, X-K),
    runs K1 and K2 the key setup page's frames, run B the benchmark's."""
    root = ready_cases(run)
    out = []
    for j in M1.menu_jobs(setchg if run == 'a' else {}, root):
        menu, msg, kind = page_of(j.case.before)
        why = ''
        if run == 'a':
            if j.kind == 'full' and not msg and menu == MENU_KEYS:
                why = X_K
            elif msg and kind == MSG_BENCH:
                why = 'the benchmark in run A'      # (never: run B's)
        elif run in ('k1', 'k2'):
            if msg or menu != MENU_KEYS or j.kind not in ('full', 'skull'):
                continue
        elif run == 'bench':
            if not (msg and kind == MSG_BENCH):
                continue
        out.append(MJob(run, page_name(j.case.before),
                        j._replace(excluded=why)))
    return out


def bench_record() -> Tuple:
    """M_BFPS (s2layout's, S2MENU2-1) holding the poked FPS text, and
    M_BROWS after it empty (the play build's phase rows: X2 stays
    black)."""
    at = native_places()['M_BFPS']
    if native_places()['M_BROWS'] != at + dict(MENU2_NATIVE)['M_BFPS']:
        raise Menu2Error('M_BROWS does not follow M_BFPS')
    base = S.SS['SS_MENUW'] - S.OWN_STATE['MENUW'][1]
    return (1, S.S2STATE, base + at,
            BENCH_FPS + bytes(dict(MENU2_NATIVE)['M_BFPS'] -
                              len(BENCH_FPS) +
                              dict(MENU2_NATIVE)['M_BROWS']))


def extra_records(case) -> List[Tuple]:
    """What this part's pages read that s2menu1's injection does not: the
    bindings (keyTable's Doom keys 1:1 into PL_KEYTAB, 6.2), the effects'
    volume (snd_SfxVolume into SND_SFXVOL; s2menu1's sound blocks are
    zeros), the benchmark's FPS text."""
    from native import s2cap as C
    d = case.before
    kt = d.get(C.sym('i_iigs65.s:keyTable'), 256)
    music = settings_places()[MUSIC_FIELD]
    return [(0, 0, S.KEYTAB_PLACE[0], bytes(kt[0::2])),
            (1, S.S2STATE, S.SS['SS_SETTINGS'] + music,
             bytes([M1.uval(d, MUSIC_FIELD) & 0xFF])),
            (2, 0, sfxvol_place(),
             bytes([M1.uval(d, 's_sound65.s:snd_SfxVolume') & 0xFF])),
            bench_record()]


def sfxvol_place() -> int:
    cb = S.BUILDS['test']
    return S.sc_extra_base(cb.sc_base, cb.channels) + \
        S.SC_EXTRA['SND_SFXVOL']


def job_records(b, job, fill: int, poison: bool):
    recs, screen = _M1_JOB_RECORDS(b, job, fill, poison)
    return recs + extra_records(job.case), screen


_M1_JOB_RECORDS = M1.job_records


# ---------------------------------------------------------------------------
# The writers of a run (SCREENS.md 6.3): s2menu1's, which name this part's
# module since the two parts' MENUW is one (S2MENU2-3)
# ---------------------------------------------------------------------------

def owners(b, loads) -> List:
    return M1.owners(b, loads)


# ---------------------------------------------------------------------------
# Every frame: both fills, the whole screen (s2menu1's comparison), X2
# ---------------------------------------------------------------------------

X2_ROWS = ((92, 99), (108, 115), (124, 131))   # uiBenchmark's rows 3-5


def x2_offsets() -> List[int]:
    from native import s2check as K
    return K.offsets(K.x2(X2_ROWS).region)


class _Case:
    """A case whose screens before and after the frame are the
    reference's with the X2 rows black (what the native shows there: a
    frame after the result's first keeps the black rows its first drew)."""

    def __init__(self, case, before: bytes, after: bytes):
        self._case = case
        self.screen_before = before
        self.screen_after = after

    def __getattr__(self, name):
        return getattr(self._case, name)


def _black(screen: bytes) -> Tuple[bytes, int]:
    out = bytearray(screen)
    drawn = 0
    for a in x2_offsets():
        drawn += out[a - S.SHR] != 0
        out[a - S.SHR] = 0
    return bytes(out), drawn


def expected_job(mj: MJob):
    """The job run and judged: on the benchmark's result, the screens with
    the X2 rows black (s2check's x2), so a byte there not 0 differs;
    (job, X2's bytes, those the reference drew)."""
    if mj.page != 'benchmark':
        return mj.job, 0, 0
    case = mj.job.case
    after, drawn = _black(case.screen_after)
    before, _ = _black(case.screen_before)
    return (mj.job._replace(case=_Case(case, before, after)),
            len(x2_offsets()), drawn)


def key_problems(mj: MJob) -> List[str]:
    """Runs K1 and K2: the reference drew the //e names (both) and the //e
    table (K1), poked 1:1 (SCREENS.md 6.2)."""
    from native import s2cap as C, s2state as T
    if mj.run not in ('k1', 'k2'):
        return []
    names, table = T.apple2e_keys()
    d = mj.job.case.before
    out = []
    want = b''.join(n.encode() + bytes(8 - len(n)) for n in names)
    if d.get(C.sym('m_menu65.s:keyNames'), 1024) != want:
        out.append('the reference\'s keyNames are not the //e names')
    if mj.run == 'k1' and d.get(C.sym('i_iigs65.s:keyTable'), 256) != \
            b''.join(bytes([k, ch]) for k, ch in table):
        out.append('the reference\'s keyTable is not the //e table')
    return out


def check_frames(b, setchg: Dict[str, int], runs: Sequence[str] = (
        'a', 'k1', 'k2', 'bench'), jobs: int = 2, work_root: Path = OUT,
        pick=None) -> Dict:
    """Every job of the runs not excluded, twice (as s2menu1's): fill $A5
    with the write log (the strays, the publish order; an open as a whole
    paused frame), fill $5A with the reference's marked bytes poisoned."""
    import shutil
    import tempfile
    from concurrent.futures import ThreadPoolExecutor
    from native import s2check as K
    work_root.mkdir(parents=True, exist_ok=True)
    all_jobs = [mj for run in runs for mj in jobs_of(run, setchg)]
    js = [mj for mj in all_jobs if not mj.job.excluded and
          (pick is None or pick(mj))]
    root = Path(tempfile.mkdtemp(prefix='tmp-frames-', dir=str(work_root)))

    def one(arg):
        mj, fill, poison = arg
        job = mj.job
        paused = not poison
        work = root / ('%s-%s-%02x' % (mj.run, job.name, fill))
        try:
            ejob, x2n, x2drawn = expected_job(mj)
            recs, screen = job_records(b, ejob, fill, poison)
            r = M1.run_calls(b, recs, [M1.call_of(job, paused)], fill, work,
                             M1.SNAP, write_log=not poison)
            probs, compared = M1.frame_problems(b, ejob, r, fill, poison,
                                                screen)
            probs += key_problems(mj)
            depth = M1.SR_depth(r)
            if depth is not None and depth > S.STACK_2D:
                probs.append('the stack %d B deep (at most %d)' % (
                    depth, S.STACK_2D))
            if not poison and r.ended() == 'stop':
                n, shown = M1.SR_stray(r, owners(b, r.loads))
                if n:
                    probs.append('%d stray writes: %s' % (n, shown[:3]))
                black = job.kind in ('open', 'close')
                probs += ['publish order: ' + x for x in
                          K.order(K.screen_stores(r.writes()), black)]
            return mj, fill, probs, compared, depth, x2n, x2drawn
        finally:
            shutil.rmtree(str(work), ignore_errors=True)
    work_list = [(mj, 0xA5, False) for mj in js] + \
        [(mj, 0x5A, True) for mj in js]
    out = {'jobs': len(js), 'runs': 0, 'compared': 0, 'kinds': {},
           'pages': {}, 'by_run': {}, 'problems': [], 'stack': 0,
           'excluded': {}, 'x2': {'bytes': 0, 'drawn_by_reference': 0}}
    for mj in all_jobs:
        if mj.job.excluded:
            out['excluded'][mj.job.excluded] = out['excluded'].get(
                mj.job.excluded, 0) + 1
    try:
        with ThreadPoolExecutor(jobs) as ex:
            for mj, fill, probs, compared, depth, x2n, x2d in ex.map(
                    one, work_list):
                out['runs'] += 1
                out['compared'] += compared
                out['stack'] = max(out['stack'], depth or 0)
                if fill == 0xA5:
                    k = mj.job.kind
                    out['kinds'][k] = out['kinds'].get(k, 0) + 1
                    pk = '%s %s' % (mj.page, k)
                    out['pages'][pk] = out['pages'].get(pk, 0) + 1
                    out['by_run'][mj.run] = out['by_run'].get(mj.run, 0) + 1
                    out['x2']['bytes'] += x2n
                    out['x2']['drawn_by_reference'] += x2d
                for pr in probs:
                    out['problems'].append('%s %s %s (%s) fill $%02X: %s' % (
                        mj.run, mj.job.kind, mj.job.name, mj.page, fill, pr))
    finally:
        shutil.rmtree(str(root), ignore_errors=True)
    return out


# ---------------------------------------------------------------------------
# Each session of run A chained from its open's state alone (s2menu1's
# check_chains with this part's injection; the key setup page's frames,
# whose names are upstream's ADB ones in run A, not compared: X-K)
# ---------------------------------------------------------------------------

def on_keys(job) -> bool:
    menu, msg, _ = page_of(job.case.before)
    return not msg and menu == MENU_KEYS


def check_chains(b, setchg: Dict[str, int], data: Dict, jobs: int = 2,
                 work_root: Path = OUT,
                 only: Optional[Sequence[str]] = None) -> Dict:
    saved = (M1.job_records, M1.on_m2)
    M1.job_records, M1.on_m2 = job_records, on_keys
    try:
        return M1.check_chains(b, setchg, data, jobs, work_root, only)
    finally:
        M1.job_records, M1.on_m2 = saved


# ---------------------------------------------------------------------------
# Timing (SCREENS.md 6.4): this part's pages' frames
# ---------------------------------------------------------------------------

def mine(mj: MJob) -> bool:
    return mj.page in ('load', 'save', 'key setup', 'display & sound',
                       'controls', 'benchmark')


def timing(b, setchg: Dict[str, int], jobs: int = 2,
           work_root: Path = OUT) -> Dict:
    """Each frame of this part's pages (runs A, K2, B; fill $A5, no write
    log) under each profile with --cost-timed: m_display alone in phase
    30, ms by page and kind (a frame redrawn whole or by the skull)."""
    import shutil
    import tempfile
    from concurrent.futures import ThreadPoolExecutor
    from native import s2run as SR
    js = [mj for run in ('a', 'k2', 'bench') for mj in jobs_of(run, setchg)
          if not mj.job.excluded and mine(mj)]
    root = Path(tempfile.mkdtemp(prefix='tmp-time-', dir=str(work_root)))

    def one(arg):
        mj, prof = arg
        work = root / ('%s-%s-%s' % (mj.run, mj.job.name, prof))
        try:
            recs, _ = job_records(b, mj.job, 0xA5, False)
            r = M1.run_calls(b, recs, [M1.call_of(mj.job)], 0xA5, work,
                             M1.SNAP, profile=prof)
            if r.ended() != 'stop':
                raise Menu2Error('%s: %s' % (mj.job.name, r.ended()))
            return mj, prof, SR.phase_ms(r, prof).get(30, 0.0)
        finally:
            shutil.rmtree(str(work), ignore_errors=True)
    out: Dict = {}
    try:
        with ThreadPoolExecutor(jobs) as ex:
            work_list = [(mj, p) for p in M1.PROFILES for mj in js]
            groups: Dict[Tuple[str, str], List[float]] = {}
            for mj, prof, ms in ex.map(one, work_list):
                groups.setdefault((prof, '%s %s' % (mj.page, mj.job.kind)),
                                  []).append(ms)
        for (prof, key), v in sorted(groups.items()):
            out.setdefault(prof, {})[key] = M1.stats(v)
    finally:
        shutil.rmtree(str(root), ignore_errors=True)
    return out


# ---------------------------------------------------------------------------
# The planted bugs (each in a scratch copy)
# ---------------------------------------------------------------------------

class Plant(NamedTuple):
    name: str
    what: str
    source: str                 # src/native/<file>, or gen/<file> (the
                                #   scratch build's generated include)
    old: str
    new: str
    runs: Tuple[str, ...]       # the runs whose frames are checked
    pages: Tuple[str, ...]      # and the pages


PLANTS = (
    Plant('thermo-dot', 'a thermometer\'s dot one step off', 's2_menu2.s',
          '        adc #<(TH_X0 + 8)\n        sta M2_V\n',
          '        adc #<(TH_X0 + 12)\n        sta M2_V\n', ('a',),
          ('display & sound', 'controls')),
    Plant('key-order', 'the key setup\'s second key from the wrong range '
          'order ($00-$1F before $20-$2F)', 'pl_keys.s',
          'pl_rlo: .byte $30, $20, $00, $40        ; I_ActionKeys\' ranges\n'
          'pl_rhi: .byte $40, $30, $20, $80\n',
          'pl_rlo: .byte $30, $00, $20, $40        ; I_ActionKeys\' ranges\n'
          'pl_rhi: .byte $40, $20, $30, $80\n', ('k1', 'k2'),
          ('key setup',)),
    Plant('view-size', 'the view size not limited to full (VIEW\'s value '
          'another size\'s label)', 's2_menu2.s',
          'tx_full:     .asciiz "FULL"\n',
          'tx_full:     .asciiz "3/4 SIZE"\n', ('a', 'bench'),
          ('display & sound', 'benchmark')),
    Plant('name-zero', 'a key name written without its 0 (the names\' '
          'pads spaces)', 'gen/plkeys.inc', ',$00   ; $', ',$20   ; $',
          ('k1', 'k2'), ('key setup',)),
)


def planted(setchg: Dict[str, int], jobs: int = 2,
            only: Optional[Sequence[str]] = None) -> Dict:
    """Each planted bug in a scratch copy of s2_menu2.s, pl_keys.s or the
    generated plkeys.inc, built into a scratch directory, and the frames
    of its runs and pages checked (the first frame redrawn whole of each
    page, and every one of the key setup's)."""
    import shutil
    import tempfile
    from native import s2run as SR
    out = {}
    for pl in PLANTS:
        if only is not None and pl.name not in only:
            continue
        root = Path(tempfile.mkdtemp(prefix='tmp-plant-', dir=str(OUT)))
        try:
            src = root / 'src'
            src.mkdir()
            for f in ('s2_menu2.s', 'pl_keys.s'):
                shutil.copy(str(ROOT / 'src' / 'native' / f), str(src / f))
            build = root / 'build'
            variables = ['S2M2SRC=%s' % src, 'S2M2PLSRC=%s' % src,
                         'S2M2_DIR=%s' % build]
            if pl.source.startswith('gen/'):
                SR.make('s2menu2', variables=variables)
                path = build / pl.source
            else:
                path = src / pl.source
            text = path.read_text()
            n = text.count(pl.old)
            if n != 1 and not pl.source.startswith('gen/'):
                raise Menu2Error('%s: the planted text is not in %s once'
                                 % (pl.name, pl.source))
            if n == 0:
                raise Menu2Error('%s: the planted text is not in %s'
                                 % (pl.name, pl.source))
            path.write_text(text.replace(pl.old, pl.new))
            if pl.source.startswith('gen/'):
                # (make's times have a second's resolution here: the
                # objects built from the include a moment ago and the
                # images linked from them are removed from the scratch
                # build, so they are made again)
                for f in ('s2_menu2.o', 's2m2.map', 's2m2t.map'):
                    (build / f).unlink()
            SR.make('s2menu2', variables=variables)
            img = 's2m2t.img'
            if (build / img).read_bytes() == (OUT / img).read_bytes():
                raise Menu2Error('%s: the planted image is the tree\'s'
                                 % pl.name)
            b = SR.load_build(build, 's2m2t', 'MENUW')
            seen = set()

            def pick(mj: MJob) -> bool:
                if mj.run not in pl.runs or mj.page not in pl.pages:
                    return False
                if mj.page == 'key setup':
                    return mj.job.kind == 'full'
                key = (mj.run, mj.page)
                if mj.job.kind not in ('full', 'open') or key in seen:
                    return False
                seen.add(key)
                return True
            r = check_frames(b, setchg, pl.runs, jobs, root, pick=pick)
            out[pl.name] = {'what': pl.what, 'runs': list(pl.runs),
                            'jobs': r['jobs'],
                            'caught': bool(r['problems']) and r['jobs'] > 0,
                            'problems': len(r['problems']),
                            'first': r['problems'][:2]}
        finally:
            shutil.rmtree(str(root), ignore_errors=True)
    return out


# ---------------------------------------------------------------------------
# Sizes, the report
# ---------------------------------------------------------------------------

BUDGET = 4000                   # s2menu2's (SCREENS.md 4.1, 7.3)
NAMES = 128 * 8                 # plk_names in this part's data


def sizes(obj: Path = OUT) -> Dict:
    """The image s2m2 (MENUW with both menu parts): s2layout's size table
    and its room; this part's module's code and data against its 4,000 B
    (the names, 1,024 B of the data, counted apart for 4.1's split; the
    sign's font, which this part's budget also held, went at wave 6's
    integration: S2MENU2-4)."""
    from native import s2run as SR
    b = SR.load_build(obj, 's2m2', 'MENUW')
    ms = SR.module_sizes(b)
    text = (obj / 's2m2.map').read_text()
    rows, problems = S.check_map('MENUW', text)
    segs = M1.module_segments(text).get('s2_menu2', {})
    code = segs.get('S2CODE', 0)
    data = sum(v for k, v in segs.items() if k != 'S2CODE')
    out = {'table': rows, 'problems': list(problems), 'code': code,
           'data': data, 'names': NAMES, 'own': code + data,
           'budget': BUDGET, 'glue': ms.modules.get('s2_menut', 0),
           's2menu1': sum(ms.modules.get(m, 0) for m in M1.OWN_MODULES),
           'extent': ['$%04X' % ms.extent[0], '$%04X' % (ms.extent[1] - 1)],
           'room_end': '$%04X' % M1.ROOM_END}
    out['total'] = code + data
    if code + data > BUDGET:
        out['problems'].append('s2_menu2 %d B, over its %d B'
                               % (code + data, BUDGET))
    if ms.extent[1] > M1.ROOM_END:
        out['problems'].append('MENUW ends at $%04X, past its room'
                               % (ms.extent[1] - 1))
    return out


def report(args, jobs: int = 2) -> Dict:
    from native import s2run as SR
    out: Dict = {}
    if not args.no_build:
        SR.make('s2menu2')
    if args.capture or not all((run_root(r) / 'index.json').exists()
                               for r in RUNS) or not M1.CALLS_FILE.exists():
        out['capture'] = capture()
    data = M1.load_calls()
    setchg = M1.settings_by_frame(data)
    b = SR.load_build(OUT, 's2m2t', 'MENUW')
    out['sizes'] = sizes()
    keys = ('sizes',)
    if args.check:
        out['frames'] = check_frames(b, setchg, jobs=jobs)
        out['chains'] = check_chains(b, setchg, data, jobs)
        # (s2menu1's engine on this image, its t_num as request S2MENU2-2
        # asks: every M_Responder and M_Ticker call of the call log)
        out['responders'] = M1.check_responders(b, data, 0xA5, jobs, OUT)
        out['tickers'] = M1.check_tickers(b, data, 0xA5, jobs, OUT)
        keys += ('frames', 'chains', 'responders', 'tickers')
    if args.timing:
        out['timing'] = timing(b, setchg, jobs)
    if args.planted:
        out['planted'] = planted(setchg, jobs)
    problems = sum(len(out[k]['problems']) for k in keys)
    if args.planted:
        problems += sum(1 for v in out['planted'].values() if not v['caught'])
    out['ok'] = problems == 0
    (OUT / 'report.json').write_text(json.dumps(out, indent=1) + '\n')
    return out


def summary(out: Dict) -> str:
    lines = ['s2menu2: %s' % ('ok' if out.get('ok') else 'PROBLEMS')]
    if 'capture' in out:
        lines.append('captured: %s' % json.dumps(out['capture']))
    sz = out.get('sizes')
    if sz:
        lines.append('sizes: s2_menu2 %d B (code %d, data %d with the names '
                     '%d): %d of %d B; s2menu1 %d B; glue %d B; MENUW '
                     '%s-%s; %s'
                     % (sz['own'], sz['code'], sz['data'], sz['names'],
                        sz['total'], sz['budget'], sz['s2menu1'], sz['glue'],
                        sz['extent'][0], sz['extent'][1],
                        '; '.join(sz['problems']) or 'within its room'))
    for key in ('frames', 'chains', 'responders', 'tickers'):
        r = out.get(key)
        if r is None:
            continue
        info = {k: v for k, v in r.items() if k != 'problems'}
        lines.append('%s: %s, %d problems' % (key, json.dumps(info),
                                               len(r['problems'])))
        lines += ['  ' + x for x in r['problems'][:10]]
    if 'timing' in out:
        lines.append('timing (ms): %s' % json.dumps(out['timing']))
    for name, v in out.get('planted', {}).items():
        lines.append('planted %s (%s): %s, %d jobs, %d problems, e.g. %s'
                     % (name, v['what'], 'caught' if v['caught']
                        else 'NOT CAUGHT', v['jobs'], v['problems'],
                        v['first'][:1]))
    return '\n'.join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--inc', type=Path)
    parser.add_argument('--capture', action='store_true',
                        help='the reference\'s runs K1, K2, B and the call '
                        'log again')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--timing', action='store_true')
    parser.add_argument('--planted', action='store_true')
    parser.add_argument('--all', action='store_true',
                        help='--capture --check --timing --planted')
    parser.add_argument('--no-build', action='store_true')
    parser.add_argument('--jobs', type=int, default=2)
    args = parser.parse_args(argv)
    try:
        if args.inc:
            M1.write_if_changed(args.inc, inc_text())
            return 0
        if args.all:
            args.capture = args.check = args.timing = args.planted = True
        if not (args.capture or args.check or args.timing or args.planted):
            parser.print_help()
            return 2
        out = report(args, args.jobs)
    except (Menu2Error, M1.MenuError) as error:
        print('s2menu2: %s' % error, file=sys.stderr)
        return 1
    print(summary(out))
    return 0 if out['ok'] else 1


if __name__ == '__main__':
    sys.exit(main())
