#!/usr/bin/env python3
"""Part s2menu2's generated include (gen/s2menu2.inc) for MENUW
(src/native/s2_menu2.s): the load and save pages' titles' x (centerPatch:
160 - width / 2 of M_LOADG and M_SAVEG, from the 2D store's headers) and
the music's byte in SS_SETTINGS (the field map's snd_MusicVolume).

Usage:  python3 tools/native/s2menu2.py --inc OUT/s2menu2.inc
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, Optional, Sequence

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from native import s2layout as S  # noqa: E402
from native import s2menu1 as M1  # noqa: E402


class Menu2Error(Exception):
    pass


def title_x(width: int) -> int:
    """centerPatch [R m_menu65.s:1248-1258]: 160 - width / 2."""
    return 160 - (width >> 1)


def inc_text() -> str:
    ps = M1.patches()
    lines = ['; Generated by tools/native/s2menu2.py --inc (part s2menu2, '
             'docs/SCREENS.md). Do not edit.', '',
             '; drawSlots\' titles centred (centerPatch: 160 - width / 2)']
    for name in ('M_LOADG', 'M_SAVEG'):
        x = title_x(ps[name].width)
        if not 0 <= x < 256:
            raise Menu2Error('%s at x %d' % (name, x))
        lines.append('M2_%s_X     = %d ; %s %d wide' % (name[2:], x, name,
                                                       ps[name].width))
    lines += ['', '; snd_MusicVolume\'s byte in SS_SETTINGS (the field '
              'map\'s)',
              'SET_MUSVOL      = %d' % settings_places()[MUSIC_FIELD]]
    return '\n'.join(lines) + '\n'


# snd_MusicVolume [R s_sound65.s] in the settings that persist: the
# field map's SS_SETTINGS+5 (s2_menu.s's SET_MUSVOL)
MUSIC_FIELD = 's_sound65.s:snd_MusicVolume'


def settings_places() -> Dict[str, int]:
    """The field map's SS_SETTINGS bytes by their upstream symbol."""
    out = {}
    for f in S.field_map():
        place = getattr(f, 'place', '')
        if isinstance(place, str) and place.startswith('SS_SETTINGS+'):
            out[f.ref] = int(place.split('+')[1])
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--inc', type=Path)
    args = parser.parse_args(argv)
    if not args.inc:
        parser.print_help()
        return 2
    try:
        M1.write_if_changed(args.inc, inc_text())
    except (Menu2Error, M1.MenuError) as error:
        print('s2menu2: %s' % error, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
