#!/usr/bin/env python3
"""The link map of the automap's overlay image OVLW (`--ovlw-cfg`,
src/native/m11/s2ovl.mk): OVLW (src/native/s2_ovl.s, s2_amline.s,
rrec.s, bucket.s) linked alone into MASKW's code room with BKFAR and
BKFAR2 as data, importing the frame image's symbols from its labels.

`--check-frame` checks that OVLW's places are the shipped renderer's: the
frame image ovf (render.mk's objects, the default RELEASE) and OVLW
against rcard (render.mk's rcard, what playdisk.py puts on the disk).
In the game the card, the far layer, MATHW and AUXW are rcard's, and the
bucket pass's main code (BKFAR, BKFAR2) is copied from the masked image
(rcard's) or from OVLW: every symbol OVLW imports from ovf, BKNEAR's
place, OVLW's labels in those places and its BKFAR's, BKFAR2's and
BKNEAR's sizes must be rcard's.

Usage:  python3 tools/native/s2ovl.py --ovlw-cfg FRAME_LBL OUT
        python3 tools/native/s2ovl.py --check-frame RCARD_LBL FRAME_LBL
            OVLW_LBL
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from native import rlayout as R, s2layout as S  # noqa: E402


# ---------------------------------------------------------------------------
# OVLW's link map: MASKW's code room, the frame image's symbols
# ---------------------------------------------------------------------------

# what OVLW's objects import from the frame image (the far layer, the
# math, the replay that bucket.s's BKFAR calls); ld65 fails on any other
OVLW_IMPORTS = ('far_get', 'far_put', 'fixmul', 'mul32', 'fixmulang',
                'recip', 'umul16', 'umul16lo', 'sdiv16', 'sineapprox',
                'cosineapprox', 'nat_replay',
                # the replay's, for bucket.s's rp_cut (-D RELEASE)
                'run_descriptors', 'draw_strip', 'rp_drawn', 'gcol', 'rp')
OVLW_RT = 0x9400                # its run time places (s2_ovl.s's NBUF ..)


def read_labels(path: Path) -> Dict[str, int]:
    out = {}
    for line in Path(path).read_text().splitlines():
        f = line.split()
        if len(f) == 3 and f[0] == 'al':
            out[f[2].lstrip('.')] = int(f[1], 16)
    return out


def ovlw_cfg_text(labels: Dict[str, int]) -> str:
    """ld65's map of OVLW: its stored bytes from $6800 to its run time
    places, BKFAR and BKFAR2 as data run at their main places, bucket.s's
    card part where the frame image has it (only its addresses matter:
    BKFAR calls it), the frame's symbols."""
    lo = S.IMAGE['OVLW'].stored[0]
    near = labels['__BKNEAR_LOAD__']
    lines = [
        '# Generated by tools/native/s2ovl.py --ovlw-cfg (part s2ovl, '
        'docs/SCREENS.md):',
        '# the image OVLW in MASKW\'s code room. Do not edit.',
        'MEMORY {',
        '    OVW:   start = $%04X, size = $%04X, file = "%%O.ovw";' % (
            lo, OVLW_RT - lo),
        '    BFAR:  start = $%04X, size = $%04X, file = "";' % (
            R.BKFAR_RUN, R.BKFAR_END - R.BKFAR_RUN),
        '    BFAR2: start = $%04X, size = $%04X, file = "";' % (
            R.BKFAR2_RUN, R.BKFAR2_END - R.BKFAR2_RUN),
        '    RCX:   start = $%04X, size = $%04X, file = "";' % (
            near, 0xFF00 - near),
        '}',
        'SEGMENTS {',
        '    OVLHEAD: load = OVW, type = ro;',
        '    S2CODE:  load = OVW, type = ro, define = yes;',
        '    MASKW:   load = OVW, type = rw, define = yes;',
        '    BKFAR:   load = OVW, run = BFAR, type = ro, define = yes;',
        '    BKFAR2:  load = OVW, run = BFAR2, type = ro, define = yes;',
        '    BKNEAR:  load = RCX, type = ro, define = yes;',
        '    BKCARD:  load = RCX, type = ro, optional = yes;',
        '}',
        'SYMBOLS {']
    for name in OVLW_IMPORTS:
        lines.append('    %s: type = export, value = $%04X%s;' % (
            name, labels[name], ', addrsize = zp' if labels[name] < 0x100
            else ''))
    lines += ['}', '']
    return '\n'.join(lines)


def write_ovlw_cfg(lbl: Path, out: Path) -> None:
    text = ovlw_cfg_text(read_labels(lbl))
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists() and out.read_text() == text:
        return
    tmp = out.with_name(out.name + '.tmp')
    tmp.write_text(text)
    tmp.replace(out)


# ---------------------------------------------------------------------------
# OVLW's places against the shipped renderer's
# ---------------------------------------------------------------------------

def shared_places(rcard: Dict[str, int]) -> List[Tuple[int, int, str]]:
    """[lo, hi) ranges whose labels every image of the frame shares with
    rcard: zero page, BKFAR2's and BKFAR's run places, MATHW and AUXW, the
    card's bank parts and its $F900 part (not its $E000 part: each link's
    own driver, the game's code in the game)."""
    w_end = rcard['__AUXW_RUN__'] + rcard['__AUXW_SIZE__']
    return [(0x0000, 0x0100, 'zero page'),
            (R.BKFAR2_RUN, R.BKFAR2_END, 'BKFAR2'),
            (R.BKFAR_RUN, R.BKFAR_END, 'BKFAR'),
            (rcard['__MATHW_RUN__'], w_end, 'MATHW, AUXW'),
            (0xD000, 0xE000, 'the card\'s banks'),
            (0xF900, 0xFF00, 'the card\'s $F900 part')]


def frame_problems(rcard: Dict[str, int], frame: Dict[str, int],
                   ovlw: Dict[str, int]) -> Tuple[List[str], int]:
    """The places OVLW takes that differ from rcard's ([] when none), and
    the number of labels compared: the symbols OVLW imports from ovf and
    BKNEAR's place in ovf (the card's code), and OVLW's own labels in the
    places it shares with rcard (BKFAR, BKFAR2, BKNEAR, zero page), with
    BKFAR's and BKFAR2's sizes. (ovf's other places are not OVLW's: its
    driver and its CLIPLOG objects are its own.)"""
    out = []
    places = shared_places(rcard)

    def shared(v: int) -> bool:
        return any(lo <= v < hi for lo, hi, _ in places)

    n = 0
    for name in OVLW_IMPORTS + ('__BKNEAR_LOAD__',):
        n += 1
        if frame.get(name) is None or frame.get(name) != rcard.get(name):
            out.append('OVLW takes %s from ovf at %s, rcard\'s is %s' % (
                name, fmt(frame.get(name)), fmt(rcard.get(name))))
    for name, v in sorted(ovlw.items()):
        # (cheap locals repeat: a .lbl keeps one of each name)
        if name.startswith('@') or not shared(v):
            continue
        if name.startswith('__') and not name.startswith('__BK'):
            continue
        n += 1
        if v != rcard.get(name):
            out.append('OVLW\'s %s is $%04X, rcard\'s %s' % (
                name, v, fmt(rcard.get(name))))
    for name in ('__BKFAR_SIZE__', '__BKFAR2_SIZE__', '__BKNEAR_SIZE__'):
        n += 1
        if ovlw.get(name) != rcard.get(name):
            out.append('OVLW\'s %s is %s, rcard\'s %s' % (
                name, fmt(ovlw.get(name)), fmt(rcard.get(name))))
    return out, n


def fmt(v: Optional[int]) -> str:
    return 'none' if v is None else '$%04X' % v


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    act = parser.add_mutually_exclusive_group(required=True)
    act.add_argument('--ovlw-cfg', nargs=2, type=Path,
                     metavar=('FRAME_LBL', 'OUT'))
    act.add_argument('--check-frame', nargs=3, type=Path,
                     metavar=('RCARD_LBL', 'FRAME_LBL', 'OVLW_LBL'))
    args = parser.parse_args(argv)
    if args.ovlw_cfg:
        write_ovlw_cfg(*args.ovlw_cfg)
        return 0
    rc, fr, ov = (read_labels(p) for p in args.check_frame)
    bad, n = frame_problems(rc, fr, ov)
    for line in bad:
        print('s2ovl: %s' % line, file=sys.stderr)
    if not bad:
        print('s2ovl: ovf and OVLW agree with rcard (%d labels)' % n)
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
