#!/usr/bin/env python3
"""Part s2pal (docs/SCREENS.md): the palettes, tints, gamma, SCBs, the finish and the wipe. Writes
the generated include s2pal.inc: the places the native code (s2_pal.s,
s2_nib.s, s2_palw.s) reads that are not in s2.inc.

Usage:  python3 tools/native/s2pal.py --inc OUT
"""

import argparse
import sys
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

# ---------------------------------------------------------------------------
# The native places: the generated include s2pal.inc
# ---------------------------------------------------------------------------

# S2PAL's places (SCREENS.md's bank 106: TINTPAL, the 16 nibble tables
# S2NIB, GSSTAT, GSOVL, GRAYMAP), PS_TXTINV and s2_pal's and s2_nib's zero
# page $78-$7F are s2layout's and in s2.inc

# page 1 $0100-$017F: newColors' bounce for TINTPAL's row (SCREENS.md:
# page 1 below $01B4 is free outside the replay; the stack stays at or
# above $01C0)
BOUNCE, BOUNCE_SIZE = 0x0100, 128
# the player's fields ST_doPaletteStuff reads (the game's player,
# llayout.player_layout, read only)
PLAYER_FIELDS = (('S2P_DAMAGE', ('damagecount',)),
                 ('S2P_STRENGTH', ('powers', 1)),
                 ('S2P_BONUS', ('bonuscount',)),
                 ('S2P_IRONFEET', ('powers', 3)))


def inc_values() -> List[Tuple[str, int]]:
    from native import llayout as LL
    out: List[Tuple[str, int]] = []
    pl = {tuple(p): at for p, _, at in LL.player_layout()}
    out += [('S2P_PLAYER', LL.G['G_PLAYER']),
            ('S2P_MENUACTIVE', LL.G['G_MENUACTIVE'])]
    out += [(n, pl[p]) for n, p in PLAYER_FIELDS]
    out += [('S2P_LVC', LL.LVC), ('S2P_GSVIEW', LL.LVC_GSVIEW)]
    out += [('S2P_BOUNCE', BOUNCE), ('S2P_BOUNCE_SIZE', BOUNCE_SIZE)]
    return out


def inc_text() -> str:
    lines = ['; Generated by tools/native/s2pal.py (part s2pal, '
             'docs/SCREENS.md). Do not edit.',
             '; (S2PAL\'s places, PS_TXTINV and S2P_A-S2P_F are in s2.inc.)',
             '']
    for n, v in inc_values():
        lines.append('%-16s= $%04X' % (n, v))
    return '\n'.join(lines) + '\n'


def write_inc(path: Path) -> None:
    text = inc_text()
    if path.exists() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text)
    tmp.replace(path)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--inc', metavar='OUT', required=True)
    args = parser.parse_args(argv)
    write_inc(Path(args.inc))
    return 0


if __name__ == '__main__':
    sys.exit(main())
