#!/usr/bin/env python3
"""Part s2wi's checks (docs/SCREENS.md 1.5.5, 6, 7.3; docs/m11-parts/
s2wi.md): the intermission's image WIW against upstream's frames.

The truth is part s2cap's capture of the tour (build/native/m11/cases/
tour): every frame whose game state is the intermission (`_g_gamestate`
1 at its start), both states (the stats, the next location with its
pointer), each with display's state at its start (PD0: the wi counters,
`_g_wminfo`, WI_Init's lumps, the palette state, the screen), the palette
state at I_FinishUpdate's entry (PDF) and the screen after the frame.

The native side is the test image s2wt (src/native/s2_wit.s, the glue;
src/native/s2_wi.s, the image's code; the shared drawers, the publish, the
palettes, the effect service and part plinput's pl_poll, with the input
block as the boot leaves it, since wave 5's integration) on a2vm
under the test driver: each case staged in RamWorks (the wi state at
milestone 10's places through s2state's injection, PALST, WIW's own block,
the SCBs and palettes), the pixels poisoned with the run's fill, then
wi_frame in the cost phase 30. After each call a snapshot of the screen,
the wi state and the state blocks; the write log judges every writer (no
stray write) and the publish order (s2check.order).

Checks, for every case:
  - the whole screen ($2000-$9FFF: s2layout's regions 'wi' and 'colors';
    $9DC8-$9DFF kept) equal to the reference's after the frame;
  - WI_SNLPTR equal to the reference's at I_FinishUpdate (WI_Drawer sets
    it in NoState);
  - PALST's scb, palette and picturenum equal to the reference's at
    I_FinishUpdate;
  - no stray write, the publish order of SCREENS.md 1.3, the stack;
  - (chained) W_LUMPS, made by wi_init, equal to the reference's lumps as
    2D store handles.
Modes: 'injected' (each case from its own state; fill $A5 with the
screen's colours as captured, fill $5A with every byte the frame marked
poisoned) and 'chained' (each intermission's frames in order from the
first frame's state: PALST carried by the native code, W_LUMPS from
wi_init, the wi state injected each frame as milestone 10 makes it).

Usage:
  python3 tools/native/s2wi.py --inc OUT       the generated s2wi.inc
  python3 tools/native/s2wi.py --check [--profile f121] [--jobs 2]
  python3 tools/native/s2wi.py --planted [--jobs 2]
  python3 tools/native/s2wi.py --all [--jobs 2] (the checks, the timing on
                                    f121 and fastpath, the planted bugs,
                                    the sizes: build/native/m11/s2wi/
                                    report.json)
"""

import argparse
import json
import shutil
import struct
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Dict, List, NamedTuple, Optional, Sequence, Tuple

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from native import s2layout as S  # noqa: E402

ROOT = HERE.parent.parent
BUILD = ROOT / 'build'
M11 = BUILD / 'native' / 'm11'
OUT = M11 / 's2wi'
SOURCE = ROOT / 'src' / 'native'
SHARED_GEN = M11 / 'shared' / 'gen'
KEEP_GEN = ('s2.inc', 's2-release.inc', 's2-m11.inc', 's2-fxch8.inc',
            'rlayout.inc')
RUN = 'tour'
JOBS = 2
PROFILES = ('f121', 'fastpath')
GS_LEVEL, GS_INTERMISSION = 0, 1
FILLS = ((0xA5, False), (0x5A, True))     # (fill, poisoned)

# the glue's stage (src/native/s2_wit.s)
T_STAGE = 80
PER_BANK = 19
REC = 0x0A00
REC_MAIN, REC_PALST, REC_OWN, REC_SCREEN, REC_CTL = 0, 0x200, 0x500, \
    0x600, 0x900
F_LEFT, F_CHAINED, F_INIT = 1, 2, 4
MAX_CASES = S.DRV_CALLS - 1            # the driver's call list
NLUMPS = 33
STATE_SNAP = 'aux104:0200-04FF,aux104:0B00-0BFF,aux106:1800-57FF'
DRAIN_US = 0.991        # µs a published byte drains on F1.2.1 [M: s2draw.md]
LOAD_US = 0.246         # µs a byte of far_pload [A on M: NATIVE.md 4.3]


class WiError(Exception):
    pass


# ---------------------------------------------------------------------------
# The generated include
# ---------------------------------------------------------------------------

def picnum() -> int:
    """The release's lump number of WIMAP0 (upstream's picturenum of the
    intermission's picture, PALST's PS_PICTURE)."""
    from native import umodel as U
    return U.Release().index('WIMAP0')


def inc_text() -> str:
    return ('; Generated by tools/native/s2wi.py (part s2wi, docs/m11-parts/'
            's2wi.md). Do not edit.\n\n'
            '; WIMAP0\'s lump number in the release (upstream\'s picturenum, '
            'PALST\'s PS_PICTURE)\n'
            'WI_PICNUM       = $%04X\n' % picnum())


def write_inc(path: Path) -> None:
    text = inc_text()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text)
    tmp.replace(path)


def inc_values(path: Path) -> Dict[str, int]:
    out = {}
    for line in path.read_text().splitlines():
        f = line.split(';')[0].split('=')
        if len(f) == 2 and f[1].strip().startswith('$'):
            out[f[0].strip()] = int(f[1].strip()[1:], 16)
    return out


# ---------------------------------------------------------------------------
# The cases
# ---------------------------------------------------------------------------

class Case(NamedTuple):
    name: str
    k: int                      # its index among the run's frames
    case: Any                   # s2cap.Case
    left: bool                  # display's I_SetPalette(0): a level left
    state: int                  # WI state at the start (0 stats, 1, -1)
    black: bool                 # a new picture: the black step
    inter: int                  # which intermission (0-7)


def cases(run: str = RUN) -> Tuple[List[Case], List[str]]:
    """The run's intermission frames, and the frames excluded (named)."""
    from native import s2cap as C
    rc = C.RunCases(C.run_dir(run))
    out: List[Case] = []
    excluded: List[str] = []
    inter = -1
    for k, (e, c) in enumerate(rc.frames()):
        b = c.before
        if b.point != 'PD0:display' or \
                C.val(b, 'g_game65.s:_g_gamestate') != GS_INTERMISSION:
            continue
        name = '%s/f%06d' % (run, e['frame'])
        pdf = c.one('PDF')
        if pdf is None:
            excluded.append('%s: no I_FinishUpdate' % name)
            continue
        if C.val(b, 'm_menu65.s:_g_menuactive'):
            excluded.append('%s: a menu over the intermission (s2menu1)'
                            % name)
            continue
        left = C.val(b, 'd_main65.s:oldgamestate') == GS_LEVEL
        if left:
            inter += 1
        st = C.val(b, 'wi_stuff65.s:state')
        out.append(Case(name, k, c, left, st - 0x10000 if st & 0x8000
                        else st,
                        bool(C.val(pdf, 'i_viigs65.s:palettecount')),
                        max(inter, 0)))
    return out, excluded


def screen_region() -> S.Region:
    wi, col = S.REGIONS['wi'], S.REGIONS['colors']
    return S.Region('intermission', 's2wi', wi.rows, col.scbs, col.palettes)


class Stage(NamedTuple):
    rec: bytes                  # the case's REC bytes
    before: bytes               # aux 0 $2000-$9FFF when wi_frame starts
    tintpal: bytes


def stage(c: Case, fill: int, poison: bool, flags: int,
          state: Optional[bytes] = None) -> Stage:
    """A case's stage record; `state`: the PALST and own block to use
    instead of the case's (a chain's continuation: SS_PALST's 768 then
    SS_WIW's 256)."""
    from native import llayout as LL, s2state as ST
    inj = ST.inject(c.case, 'intermission', fill, with_screen=False)
    pal = ST.inject(c.case, 'palettes', fill, with_screen=False)
    for i in (inj, pal):
        if i.unfit:
            raise WiError('%s: unfit %s' % (c.name, i.unfit))
    mb_lo, mb_hi = LL.G['G_WMINFO'], LL.G['WI_SNLPTR'] + 2
    main = bytearray([fill]) * (mb_hi - mb_lo)
    palst = bytearray([fill]) * S.PALST_SIZE
    own = bytearray([fill]) * 256
    gamma = None
    ss_pal, ss_own = S.SS['SS_PALST'], S.SS['SS_WIW']
    for kind, bank, address, data in inj.records + pal.records:
        for k, v in enumerate(data):
            a = address + k
            if kind == ST.MAIN and mb_lo <= a < mb_hi:
                main[a - mb_lo] = v
            elif kind == ST.AUX and bank == S.S2STATE:
                if ss_pal <= a < ss_pal + S.PALST_SIZE:
                    palst[a - ss_pal] = v
                elif ss_own <= a < ss_own + 256:
                    own[a - ss_own] = v
    for p in pal.places:
        if p.ref.endswith('_g_gamma'):
            gamma = p.value
    if gamma is None:
        raise WiError('%s: no gamma' % c.name)
    # PS_BEGUN (no upstream counterpart): s2_finish leaves it 0, so it is
    # 0 at every frame's start (SCREENS.md 1.3; s2_pub.s)
    palst[S.palst_places()['PS_BEGUN']] = 0
    if state is not None:
        palst[:] = state[:S.PALST_SIZE]
        own[:] = state[S.PALST_SIZE:S.PALST_SIZE + 256]
    screen, _ = ST.screen_image(c.case, fill, poison)
    rec = bytearray(REC)
    rec[REC_MAIN:REC_MAIN + len(main)] = main
    rec[REC_PALST:REC_PALST + S.PALST_SIZE] = palst
    rec[REC_OWN:REC_OWN + 256] = own
    tail = screen[S.SCB - S.SHR:]
    rec[REC_SCREEN:REC_SCREEN + len(tail)] = tail
    rec[REC_CTL:REC_CTL + 4] = bytes([flags, fill, gamma & 0xFF,
                                      gamma >> 8 & 0xFF])
    before = bytes([fill]) * (S.SCB - S.SHR) + tail
    return Stage(bytes(rec), before, c.case.carried('TINTPAL'))


_NIBTAB: Optional[bytes] = None


def picture_nibtab() -> bytes:
    """WIMAP0's 16 nibble tables (S2NIB) as drawPicture builds them."""
    global _NIBTAB
    if _NIBTAB is None:
        from native import s2pal as P, s2palmodel as M
        lp = P.lumps()
        pic = lp.get(lp.num('WIMAP0'))
        _NIBTAB = b''.join(M.build_nibtab(pic[M.PICTURE_PAIRS + 256 * i:
                                              M.PICTURE_PAIRS + 256 * i +
                                              256]) for i in range(16))
    return _NIBTAB


def stage_records(stages: Sequence[Stage]) -> List[Tuple[int, int, int,
                                                         bytes]]:
    banks: Dict[int, bytearray] = {}
    for k, st in enumerate(stages):
        bank, j = divmod(k, PER_BANK)
        data = banks.setdefault(T_STAGE + bank, bytearray(0xC000 - 0x0200))
        data[j * REC:(j + 1) * REC] = st.rec
    return [(1, b, 0x0200, bytes(d)) for b, d in sorted(banks.items())]


# ---------------------------------------------------------------------------
# The build and the machine
# ---------------------------------------------------------------------------

def make(obj: Path = OUT, source: Path = SOURCE, m11: Path = M11) -> None:
    from native import s2run as SR
    SR.make('s2wi', m11, source)
    del obj


def build_of(obj: Path = OUT):
    from native import s2run as SR
    if not (obj / 's2wt.map').exists():
        raise WiError('%s is missing: make -C src/native -f m11.mk part '
                      'P=s2wi' % (obj / 's2wt.map'))
    return SR.load_build(obj, 's2wt', 'WIW')


_STORE: Optional[List[Tuple[int, int, int, bytes]]] = None


def store_records() -> List[Tuple[int, int, int, bytes]]:
    """The 2D store (part s2data's GFX.n: the picture, the patches)."""
    global _STORE
    if _STORE is None:
        from native import lstore
        files = sorted((M11 / 's2data').glob('GFX.*'))
        if not files:
            raise WiError('no GFX.n in %s: make -f m11.mk part P=s2data' %
                          (M11 / 's2data'))
        # built whole, then published in one assignment: the check's job
        # threads call this at once, and a thread must never see a store
        # half read (the wave 8 integration: a partial store made a run
        # crash or run away now and then)
        store = []
        for p in files:
            for bank, address, data in lstore.read_bank_file(p.read_bytes()):
                store.append((1, bank, address, bytes(data)))
        _STORE = store
    return _STORE


def card_records(gen: Dict[str, int]) -> List[Tuple[int, int, int, bytes]]:
    """The effects' card state as at a boot with no sound: the voices
    idle, the mailboxes empty, FX_ON 0 (fx_service then only empties)."""
    voices = gen['VOICES'] * gen['VOICE_SIZE']
    mails = gen['NUM_CHANNELS'] * 4
    return [(2, 0, gen['FXV_BASE'], bytes(voices)),
            (2, 0, gen['SC_MAIL'], bytes(mails)),
            (2, 0, gen['FX_ON'], bytes(3))]


def module_pcs(b) -> Dict[str, Tuple[int, int]]:
    from native import s2drawcase as DC
    return DC.module_pcs(b)


def owners(b, loads, gen: Dict[str, int]):
    """The writers of a run of s2wt and what each may write."""
    from native import llayout as LL, plinput as PI, rlayout as R, \
        s2run as SR
    pcs = module_pcs(b)
    lab = b.labels
    data = b.segments['S2DATA']
    fa = ('main', 0, 0x0000, 0x0006)
    s2zp = ('main', 0, 0x48, 0x78)
    palzp = ('main', 0, 0x78, 0x80)
    wzp = ('main', 0, 0x80, 0xAE)
    gzp = ('main', 0, 0xB0, 0xB5)
    band = ('main', 0, S.IMAGE['WIW'].runtime[0][0], 0xBC00)
    palst = ('main', 0, S.PALST_W, S.PALST_W + S.PALST_SIZE)
    own = ('main', 0, S.PALST_W + S.PALST_SIZE, 0xC000)
    mb = ('main', 0, LL.G['G_WMINFO'], LL.G['WI_SNLPTR'] + 2)
    snl = ('main', 0, LL.G['WI_SNLPTR'], LL.G['WI_SNLPTR'] + 2)
    dat = ('main', 0, data[0], data[1] + 1)
    pixels = ('aux', 0, S.SHR, S.SCB)
    colors = ('aux', 0, S.SCB, S.SCREEN_END)
    ss_pal = ('aux', S.S2STATE, S.SS['SS_PALST'],
              S.SS['SS_PALST'] + S.PALST_SIZE)
    ss_own = ('aux', S.S2STATE, S.SS['SS_WIW'], S.SS['SS_WIW'] + 256)
    nib = ('aux', S.S2PAL, S.S2PAL_AT['S2P_NIB'],
           S.S2PAL_AT['S2P_NIB'] + S.S2PAL_SIZE['S2P_NIB'])
    begun = lab['s2_begun']
    gamma = S.resolve_game('GAMMA')[1]
    io_window = frozenset({0xC002, 0xC003, 0xC004, 0xC005, 0xC073})
    fxcard = tuple(('lc', 0, lo, hi) for lo, hi in (
        (gen['FXV_BASE'], gen['FXV_BASE'] + gen['VOICES'] *
         gen['VOICE_SIZE']),
        (gen['FX_ON'], gen['FX_RING']),
        (gen['SC_MAIL'], gen['SC_MAIL'] + gen['NUM_CHANNELS'] * 4)))
    return [
        SR.driver_owner(b), SR.loader_owner(b, loads),
        SR.Owner('the far layer', (b.segments['RFAR'],),
                 (fa, s2zp, wzp, band, palst, own, dat, ss_pal, ss_own,
                  nib), io_window),
        SR.Owner('the test glue', (pcs['s2_wit'],),
                 (fa, gzp, mb, ('main', 0, R.PHASE, R.PHASE + 2),
                  ('main', 0, gamma, gamma + 2), pixels, colors),
                 frozenset({0xC004, 0xC005})),
        SR.Owner('s2_wi', (pcs['s2_wi'],),
                 (fa, s2zp, wzp, dat, snl, own), frozenset()),
        SR.Owner('s2_draw', (pcs['s2_draw'],), (fa, s2zp), frozenset()),
        SR.Owner('s2_pub', (pcs['s2_pub'],),
                 (s2zp, pixels, ('main', 0, begun, begun + 1)),
                 frozenset({0xC004, 0xC005})),
        SR.Owner('s2_pal', (pcs['s2_pal'],), (fa, palzp, palst, colors),
                 frozenset({0xC004, 0xC005})),
        SR.Owner('s2_nib', (pcs['s2_nib'],), (fa, palzp, palst),
                 frozenset()),
        SR.Owner('fx_service', (pcs['fx'],), fxcard, frozenset()),
    ] + PI.image_owners(b)      # pl_poll, pl_time (S2WI-3, wave 5)


def write_log_ranges(b) -> str:
    """Every CPU write but: the stack page, the far layer's arguments and
    the drawers' zero page ($00-$05, $48-$7F), the image's code (its loops
    patch their operands) and WIW's runtime W ($8000-$BBFF: the band, the
    marks, the slots, the fetch buffer), the pixel rows 1-198 (32 KB a
    case: the whole screen is compared on the snapshots; rows 0 and 199,
    the frame's first and last band stores, stay for the order)."""
    lo, hi = b.segments['S2DATA']
    return ('main:0006-0047,main:0080-00FF,main:0200-65FF,main:%04X-%04X,'
            'main:BC00-FFFF,lc,lc1,aux0:0000-209F,aux0:9C60-FFFF,aux1-127,'
            'cpu:C000-C0FF' % (lo, hi))


class Span(NamedTuple):
    start: int
    end: int
    stores: List[Any]           # the screen stores (s2check.Store)
    published: int              # bytes s2_publish stored (rows 0, 199)


def spans(b, writes) -> List[Span]:
    """Each wi_frame of the glue: PHASE written PHV_2D, then 0."""
    from native import rlayout as R, s2check as K
    pcs = module_pcs(b)
    glue = pcs['s2_wit']
    pub = pcs['s2_pub']
    out: List[Span] = []
    cur: Optional[List[Any]] = None
    start = 0
    for w in writes:
        if w.storage == 'main' and w.offset == R.PHASE and \
                glue[0] <= w.pc <= glue[1]:
            if w.new == 2 * S.PHASE_2D:
                cur, start = [], w.clock
            elif w.new == 0 and cur is not None:
                st = K.screen_stores(cur)
                out.append(Span(start, w.clock, st, sum(
                    1 for x in cur if pub[0] <= x.pc <= pub[1])))
                cur = None
            continue
        if cur is not None:
            cur.append(w)
    return out


def ms(profile: str, clocks: int) -> float:
    from a2vm import costs
    return clocks / (costs.parameters(profile)['fabric_mhz'] * 1000.0)


# ---------------------------------------------------------------------------
# A run of up to 31 cases
# ---------------------------------------------------------------------------

class Job(NamedTuple):
    tag: str
    cases: Tuple[Case, ...]
    fill: int
    poison: bool
    chained: bool
    first_state: Optional[bytes]    # a chain's continuation: SS_PALST,
    #                                 SS_WIW, S2NIB as the last run left


def expected(c: Case) -> Dict[str, Any]:
    from native import s2cap as C, s2state as ST
    pdf = c.case.one('PDF')
    sym = C.sym
    lumps = c.case.before.get(sym('wi_stuff65.s:lumps'), 2 * NLUMPS)
    words = [lumps[k] | lumps[k + 1] << 8 for k in range(0, 2 * NLUMPS, 2)]
    handles, ok = ST.gfx_encode(words)
    return {'screen': c.case.screen_after,
            'snl': C.val(pdf, 'wi_stuff65.s:snl_pointeron'),
            'scb': pdf.get(sym('i_viigs65.s:scb'), 200),
            'palette': pdf.get(sym('i_viigs65.s:palette'), 512),
            'picture': C.val(pdf, 'i_viigs65.s:picturenum'),
            'lumps': handles if ok else None}


def run_job(job: Job, b, profile: Optional[str], work_root: Path,
            gen: Dict[str, int]) -> Dict[str, Any]:
    from native import llayout as LL, s2check as K, s2run as SR
    if not 0 < len(job.cases) <= MAX_CASES:
        raise WiError('%s: %d cases' % (job.tag, len(job.cases)))
    stages = []
    for i, c in enumerate(job.cases):
        flags = F_LEFT if c.left else 0
        state = None
        if job.chained:
            if i == 0:
                flags |= F_INIT if job.first_state is None else 0
                state = job.first_state
            else:
                flags |= F_CHAINED
        stages.append(stage(c, job.fill, job.poison, flags, state))
    tints = {st.tintpal for st in stages}
    if len(tints) != 1:
        raise WiError('%s: the cases have %d TINTPALs' % (job.tag,
                                                         len(tints)))
    recs = store_records() + stage_records(stages) + card_records(gen) + \
        [(1, S.S2PAL, S.S2PAL_AT['S2P_TINTPAL'], stages[0].tintpal)]
    # the input as the boot leaves it (pl_init; S2WI-3): pl_poll runs first
    # in every frame
    from native import plinput as PI
    recs += PI.boot_records()
    if job.first_state is not None:     # a chain goes on: the native
        recs.append((1, S.S2PAL, S.S2PAL_AT['S2P_NIB'],    # tables
                     job.first_state[S.PALST_SIZE + 256:]))
    elif not any(c.black for c in job.cases):
        # the nibble tables at the frames' start: the picture's on the
        # screen (WIMAP0's, built by its first frame; s2pal's model of
        # buildNibtab, checked against ref816's NIBTAB by part s2pal). A
        # run with a new picture starts with none: its frame builds them.
        recs.append((1, S.S2PAL, S.S2PAL_AT['S2P_NIB'], picture_nibtab()))
    calls = [SR.Call('wit_case', k) for k in range(len(stages))]
    mb_lo, mb_hi = LL.G['G_WMINFO'], LL.G['WI_SNLPTR'] + 2
    snap = 'aux0:2000-9FFF,main:%04X-%04X,main:BC00-BFFF,%s' % (
        mb_lo, mb_hi - 1, STATE_SNAP)
    work = Path(tempfile.mkdtemp(prefix='tmp-run-', dir=str(work_root)))
    problems: List[str] = []
    try:
        r = SR.run(b, calls, job.fill, work, extra_records=recs,
                   write_log=False, snap_ranges=snap, profile=profile,
                   timeout=600.0, extra_args=[
                       '--write-log', write_log_ranges(b),
                       '--write-log-file', str(work / 'writes.log'),
                       '--write-log-limit', str(SR.WRITE_LOG_LIMIT)])
        if r.ended() != 'stop' or r.status() != S.S2S['DONE']:
            st = r.status()
            return {'tag': job.tag, 'cases': len(job.cases), 'problems': [
                '%s: the run ended %s, status %s' % (
                    job.tag, r.ended(), 'none' if st is None else
                    '$%02X' % st)], 'frame_ms': [], 'state': None,
                'stray': 0, 'stack': None, 'writes': 0}
        snaps = r.calls()
        writes = r.writes()
        n_stray, stray_list = SR.stray(writes, owners(b, r.loads, gen))
        sps = spans(b, writes)
        stack = SR.stack_depth(r)
    finally:
        shutil.rmtree(str(work), ignore_errors=True)
    if n_stray:
        problems.append('%s: %d stray writes: %s' % (job.tag, n_stray,
                                                    stray_list[:3]))
    if len(snaps) != len(job.cases) or len(sps) != len(job.cases):
        raise WiError('%s: %d snapshots, %d frames for %d cases' % (
            job.tag, len(snaps), len(sps), len(job.cases)))
    region = screen_region()
    frame_ms = []
    last_state = None
    for c, st, m, sp in zip(job.cases, stages, snaps, sps):
        tag = '%s (fill %02X%s%s)' % (c.name, job.fill,
                                      ', poisoned' if job.poison else '',
                                      ', chained' if job.chained else '')
        want = expected(c)
        got = bytes(m.storage('aux', 0)[S.SHR:S.SCREEN_END])
        res = K.compare(want['screen'], st.before, got, region)
        for a, v, ref in res.differ[:1]:
            row = (a - S.SHR) // S.ROW_BYTES if a < S.SCB else None
            problems.append('%s: %s $%04X: $%02X, ref $%02X%s' % (
                tag, 'row %d byte %d,' % (row, (a - S.SHR) % S.ROW_BYTES)
                if row is not None else 'colours', a, v, ref,
                ' (%d bytes differ)' % len(res.differ)
                if len(res.differ) > 1 else ''))
        for a, v, was in res.outside[:1]:
            problems.append('%s: $%04X changed outside the region: $%02X, '
                            'was $%02X' % (tag, a, v, was))
        snl = m.main[LL.G['WI_SNLPTR']] | m.main[LL.G['WI_SNLPTR'] + 1] << 8
        if snl != want['snl']:
            problems.append('%s: WI_SNLPTR %d, ref %d' % (tag, snl,
                                                         want['snl']))
        w = S.PALST_W
        pp = S.palst_places()
        if bytes(m.main[w + pp['PS_SCB']:w + pp['PS_SCB'] + 200]) != \
                want['scb']:
            problems.append('%s: PALST scb differs' % tag)
        if bytes(m.main[w + pp['PS_PALETTE']:w + pp['PS_PALETTE'] + 512]) \
                != want['palette']:
            problems.append('%s: PALST palette differs' % tag)
        pic = m.main[w + pp['PS_PICTURE']] | \
            m.main[w + pp['PS_PICTURE'] + 1] << 8
        if pic != want['picture']:
            problems.append('%s: picturenum $%04X, ref $%04X' % (
                tag, pic, want['picture']))
        if job.chained:
            lumps = bytes(m.main[S.PALST_W + S.PALST_SIZE:
                                 S.PALST_W + S.PALST_SIZE + NLUMPS])
            if want['lumps'] is None or lumps != want['lumps']:
                problems.append('%s: W_LUMPS %s, ref %s' % (
                    tag, lumps.hex(), want['lumps'].hex()
                    if want['lumps'] else 'unfit'))
        problems += ['%s: order: %s' % (tag, x)
                     for x in K.order(sp.stores, c.black)]
        if profile:
            kind = 'new picture' if c.black else (
                'stats' if c.state == 0 else 'next location')
            frame_ms.append((kind, ms(profile, sp.end - sp.start)))
        aux = m.storage('aux', S.S2STATE)
        nib = m.storage('aux', S.S2PAL)
        last_state = bytes(aux[S.SS['SS_PALST']:S.SS['SS_PALST'] +
                               S.PALST_SIZE]) + \
            bytes(aux[S.SS['SS_WIW']:S.SS['SS_WIW'] + 256]) + \
            bytes(nib[S.S2PAL_AT['S2P_NIB']:S.S2PAL_AT['S2P_NIB'] +
                      S.S2PAL_SIZE['S2P_NIB']])
    return {'tag': job.tag, 'cases': len(job.cases), 'problems': problems,
            'frame_ms': frame_ms, 'state': last_state, 'stray': n_stray,
            'stack': stack, 'writes': len(writes)}


def jobs_of(cs: Sequence[Case], modes: Sequence[str]
            ) -> Tuple[List[Job], List[List[Job]]]:
    """The injected jobs (independent) and the chains (each a list of
    jobs run in order, the next starting from the last's native state)."""
    inj: List[Job] = []
    if 'injected' in modes:
        for fill, poison in FILLS:
            groups: Dict[Tuple[bytes, bool], List[Case]] = {}
            for c in cs:     # (a new picture's frames apart: no tables)
                groups.setdefault((c.case.carried('TINTPAL'), c.black),
                                  []).append(c)
            for g in groups.values():
                for i in range(0, len(g), MAX_CASES):
                    part = tuple(g[i:i + MAX_CASES])
                    inj.append(Job('injected %02X %s..%s' % (
                        fill, part[0].name, part[-1].name), part, fill,
                        poison, False, None))
    chains: List[List[Job]] = []
    if 'chained' in modes:
        by: Dict[int, List[Case]] = {}
        for c in cs:
            by.setdefault(c.inter, []).append(c)
        for n, g in sorted(by.items()):
            chain = []
            for i in range(0, len(g), MAX_CASES):
                part = tuple(g[i:i + MAX_CASES])
                chain.append(Job('chained %d (%s..%s)' % (
                    n, part[0].name, part[-1].name), part, 0xA5, False, True,
                    None))
            chains.append(chain)
    return inj, chains


def gen_values(obj: Path) -> Dict[str, int]:
    del obj
    return inc_values(SHARED_GEN / 's2.inc')


def check(profile: Optional[str] = None, obj: Path = OUT, jobs: int = JOBS,
          modes: Sequence[str] = ('injected', 'chained')
          ) -> Dict[str, Any]:
    b = build_of(obj)
    gen = gen_values(obj)
    cs, excluded = cases()
    if not cs:
        raise WiError('no intermission frame in the %s capture' % RUN)
    inj, chains = jobs_of(cs, modes)
    work_root = Path(tempfile.mkdtemp(prefix='tmp-s2wi-run-', dir=str(obj)))
    results: List[Dict[str, Any]] = []

    def chain_run(chain: List[Job]) -> List[Dict[str, Any]]:
        out, state = [], None
        for i, job in enumerate(chain):
            if i:
                job = job._replace(first_state=state)
            res = run_job(job, b, None, work_root, gen)
            out.append(res)
            state = res['state']
            if state is None:
                break
        return out
    try:
        with ThreadPoolExecutor(max(1, min(jobs, 4))) as ex:
            futs = [ex.submit(run_job, j, b, profile if j.fill == 0xA5
                              else None, work_root, gen) for j in inj]
            cfuts = [ex.submit(chain_run, ch) for ch in chains]
            results = [f.result() for f in futs]
            for f in cfuts:
                results += f.result()
    finally:
        shutil.rmtree(str(work_root), ignore_errors=True)
    problems = [p for r in results for p in r['problems']]
    kinds = {'stats': 0, 'next location': 0, 'new picture': 0}
    for c in cs:
        kinds['new picture' if c.black else (
            'stats' if c.state == 0 else 'next location')] += 1
    return {
        'run': RUN, 'cases': len(cs), 'excluded': excluded,
        'intermissions': len({c.inter for c in cs}), 'kinds': kinds,
        'pointer frames': sum(1 for c in cs if c.state != 0 and
                              expected(c)['snl']),
        'runs': [{k: v for k, v in r.items() if k not in ('state',
                                                          'frame_ms')}
                 for r in results],
        'frame_ms': [x for r in results for x in r['frame_ms']],
        'stray': sum(r['stray'] for r in results),
        'stack': max((r['stack'] or 0) for r in results),
        'problems': problems, 'profile': profile, 'modes': list(modes)}


# ---------------------------------------------------------------------------
# The nibble tables' units a patch needs (s2_wi.s: 16 in the slots)
# ---------------------------------------------------------------------------

def unit_needs() -> Dict[str, Any]:
    """For every patch WI_Drawer can draw, at each row it can be drawn at
    (the titles, the counts, the times, the splats and the pointer at the
    nine nodes), the most units of 2 pages (a palette and a parity) its
    rows need within one band of 40 rows on WIMAP0."""
    from native import s2pal as P
    lp = P.lumps()
    rel = lp.rel
    scb = [x & 15 for x in lp.get(rel.index('WIMAP0'))[32000:32200]]

    def head(n):
        return struct.unpack('<hhhh', lp.get(rel.index(n))[:8])

    def units(top: int, h: int) -> int:
        best = 0
        for b0 in range(0, 200, 40):
            rows = range(max(top, b0, 0), min(top + h, b0 + 40, 200))
            best = max(best, len({(scb[r], r & 1) for r in rows}))
        return best
    nodes = [(185, 164), (148, 143), (69, 122), (209, 102), (116, 89),
             (166, 55), (71, 56), (135, 29), (71, 24)]
    tops: List[Tuple[str, int]] = []
    for n in ['WILV%02d' % i for i in range(9)] + ['WIENTER', 'WIF']:
        _, h, _, t = head(n)
        tops += [(n, 2 - t), (n, 2 + 5 * head('WILV00')[1] // 4 - t)]
    for n, y in [('WIOSTK', 50), ('WIOSTI', 68), ('WISCRT2', 86)] + [
            (n, y) for n in ['WIPCNT'] + ['WINUM%d' % i for i in range(10)]
            for y in (50, 68, 86)] + [
            (n, y) for n in ['WITIME', 'WIPAR', 'WICOLON', 'WISUCKS'] +
            ['WINUM%d' % i for i in range(10)] for y in (160,)] + [
            (n, y) for n in ['WIMSTT', 'WICOLON', 'WISUCKS'] +
            ['WINUM%d' % i for i in range(10)] for y in (180,)]:
        tops.append((n, y - head(n)[3]))
    for _, y in nodes:
        tops.append(('WISPLAT', y - head('WISPLAT')[3]))
        tops.append(('WIURH0', max(y, 45) - head('WIURH0')[3]))
    worst = max(((units(t, head(n)[1]), n, t) for n, t in tops))
    return {'positions': len(tops), 'most': worst[0],
            'at': '%s rows %d-%d' % (worst[1], worst[2],
                                     worst[2] + head(worst[1])[1] - 1),
            'slots': 16}


# ---------------------------------------------------------------------------
# The planted bugs (each in a scratch copy of the sources)
# ---------------------------------------------------------------------------

PLANTED = (
    ('drawTime without the first colon', 's2_wi.s', (
        ('        lda wfld                ; always the first colon\n'
         '        beq @colon\n',
         '        lda wfld                ; (planted: no first colon)\n'),)),
    ('the splats drawn to last instead of next - 1 after the secret '
     'level', 's2_wi.s', (
         ('        cmp #8\n        bne @go\n',
          '        bra @go                 ; (planted)\n'),)),
    ('the "you are here" node not lowered to 45', 's2_wi.s', (
        ('        lda #NODE_TOP\n        sta wy\n', ''),)),
    ('the percent sign of a negative count', 's2_wi.s', (
        ('        lda wn+1\n        bmi @no\n        lda #<(SCREENW - '
         'SP_STATSX)\n',
         '        lda #<(SCREENW - SP_STATSX)\n'),
        ('        lda #L_WIPCNT\n        jsr lumpat\n',
         '        lda #L_WIPCNT\n        jsr lumpat\n'
         '        lda wn+1                ; (planted: after the sign)\n'
         '        bmi @no\n'))),
)


def plant(k: int, jobs: int = JOBS) -> Tuple[str, List[str]]:
    """Planted bug k in a scratch copy: built, then the injected check at
    fill $A5; the problems it gives."""
    name, source, edits = PLANTED[k]
    scratch = Path(tempfile.mkdtemp(prefix='tmp-s2wi-plant-', dir=str(OUT)))
    try:
        src = scratch / 'src'
        (src / 'm11').mkdir(parents=True)
        shutil.copy(str(SOURCE / 'm11.mk'), str(src / 'm11.mk'))
        for f in ('s2lay.mk', 's2wi.mk'):
            shutil.copy(str(SOURCE / 'm11' / f), str(src / 'm11' / f))
        for f in ('s2_wi.s', 's2_wit.s'):
            shutil.copy(str(SOURCE / f), str(src / f))
        text = (src / source).read_text()
        for old, new in edits:
            if text.count(old) != 1:
                raise WiError('planted %r: %r is not found once' % (
                    name, old[:40]))
            text = text.replace(old, new)
        (src / source).write_text(text)
        m11 = scratch / 'm11'
        (m11 / 'shared' / 'gen').mkdir(parents=True)
        for f in KEEP_GEN:
            shutil.copy(str(SHARED_GEN / f), str(m11 / 'shared' / 'gen' / f))
        (m11 / 's2data').mkdir()
        for f in (M11 / 's2data').glob('s2data.*'):
            shutil.copy(str(f), str(m11 / 's2data' / f.name))
        make(m11 / 's2wi', src, m11)
        try:
            res = check(None, m11 / 's2wi', jobs, ('injected',))
        except Exception as error:  # a run that fails is a catch too
            text = str(error).strip().splitlines()
            return name, ['the run failed: %s' % (text[0] if text else
                                                  type(error).__name__)]
        return name, res['problems']
    finally:
        shutil.rmtree(str(scratch), ignore_errors=True)


def planted(jobs: int = JOBS) -> List[Dict[str, Any]]:
    out = []
    for k in range(len(PLANTED)):
        name, problems = plant(k, jobs)
        out.append({'bug': name, 'caught': bool(problems),
                    'failures': len(problems),
                    'first': problems[0] if problems else None})
    return out


# ---------------------------------------------------------------------------
# The sizes, the timing, the report
# ---------------------------------------------------------------------------

def sizes(obj: Path = OUT) -> Dict[str, Any]:
    """WIW (wiw: the image without the test glue) against its room and
    the size table; s2_wi's segments against the part's budget."""
    text = (obj / 'wiw.map').read_text()
    ms_ = S.read_map(text)
    part = text.split('Modules list:', 1)[1].split('Segment list:', 1)[0]
    segs: Dict[str, int] = {}
    mod = None
    for line in part.splitlines():
        if line and not line.startswith(' ') and line.rstrip().endswith(':'):
            mod = Path(line.strip()[:-1].split('(')[0]).stem
            continue
        f = line.split()
        if mod == 's2_wi' and f:
            segs[f[0]] = int(f[2][5:], 16)
    return {'modules': dict(ms_.modules), 's2_wi': segs,
            'code': segs.get('S2CODE', 0), 'code_budget': 1400,
            'data': segs.get('S2RODATA', 0) + segs.get('S2DATA', 0),
            'data_budget': 400,
            'table': (obj / 'wiw.sizes').read_text().splitlines()}


def stats(values: Sequence[float]) -> Dict[str, float]:
    v = sorted(values)
    if not v:
        return {}
    return {'n': len(v), 'median': round(v[len(v) // 2], 3),
            'p99': round(v[min(len(v) - 1, (99 * len(v)) // 100)], 3),
            'worst': round(v[-1], 3)}


def timing(res: Dict[str, Any]) -> Dict[str, Any]:
    by: Dict[str, List[float]] = {}
    for kind, v in res['frame_ms']:
        by.setdefault(kind, []).append(v)
        by.setdefault('all', []).append(v)
    return {k: stats(v) for k, v in sorted(by.items())}


def report(jobs: int = JOBS) -> Dict[str, Any]:
    t0 = time.time()
    out: Dict[str, Any] = {'part': 's2wi', 'checks': {}, 'timing': {}}
    for profile in PROFILES:
        res = check(profile, OUT, jobs,
                    ('injected', 'chained') if profile == 'f121'
                    else ('injected',))
        out['checks'][profile] = {k: v for k, v in res.items()
                                  if k != 'frame_ms'}
        out['timing'][profile] = timing(res)
    sz = sizes()
    out['sizes'] = sz
    stored = sum(n for m, n in sz['modules'].items()
                 if S.module_row(m) != 'MATHW')
    out['load_ms'] = round(stored * LOAD_US / 1000.0, 2)
    out['drain_ms'] = round((32000 + 512) * DRAIN_US / 1000.0, 2)
    out['units'] = unit_needs()
    out['planted'] = planted(jobs)
    problems = [p for c in out['checks'].values() for p in c['problems']]
    problems += ['planted bug not caught: %s' % p['bug']
                 for p in out['planted'] if not p['caught']]
    if sz['code'] > 0 and any('room' in line and 'OVER' in line
                              for line in sz['table']):
        problems.append('WIW is over its room')
    out['problems'] = problems
    out['ok'] = not problems
    out['seconds'] = round(time.time() - t0, 1)
    (OUT / 'report.json').write_text(json.dumps(out, indent=1) + '\n')
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--inc', type=Path)
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--planted', action='store_true')
    ap.add_argument('--all', action='store_true')
    ap.add_argument('--units', action='store_true')
    ap.add_argument('--profile', choices=PROFILES)
    ap.add_argument('--mode', choices=('injected', 'chained'))
    ap.add_argument('--jobs', type=int, default=JOBS)
    args = ap.parse_args(argv)
    if args.inc:
        write_inc(args.inc)
        return 0
    if args.units:
        print(json.dumps(unit_needs(), indent=1))
        return 0
    if args.check:
        res = check(args.profile, OUT, args.jobs,
                    (args.mode,) if args.mode else ('injected', 'chained'))
        print('%d cases (%s), %d runs, %d stray, stack %d B; excluded %d' %
              (res['cases'], res['kinds'], len(res['runs']), res['stray'],
               res['stack'], len(res['excluded'])))
        if args.profile:
            print(json.dumps(timing(res)))
        for p in res['problems'][:30]:
            print('  ' + p)
        print('%d problems' % len(res['problems']))
        return 1 if res['problems'] else 0
    if args.planted:
        bad = 0
        for p in planted(args.jobs):
            print('%-70s %s' % (p['bug'], 'caught (%d): %s' % (
                p['failures'], p['first']) if p['caught'] else 'NOT CAUGHT'))
            bad += not p['caught']
        return 1 if bad else 0
    if args.all:
        out = report(args.jobs)
        print(json.dumps({k: out[k] for k in ('timing', 'units', 'planted',
                                              'load_ms', 'drain_ms', 'ok')},
                         indent=1))
        for p in out['problems'][:30]:
            print('  ' + p)
        return 0 if out['ok'] else 1
    ap.print_help()
    return 2


if __name__ == '__main__':
    sys.exit(main())
