#!/usr/bin/env python3
"""Part s2wi's generated include (the intermission's image WIW): WIMAP0's
lump number in the release.

Usage:
  python3 tools/native/s2wi.py --inc OUT       the generated s2wi.inc
"""

import argparse
import sys
from pathlib import Path
from typing import Optional, Sequence

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))


def picnum() -> int:
    """The release's lump number of WIMAP0 (upstream's picturenum of the
    intermission's picture, PALST's PS_PICTURE)."""
    from native import umodel as U
    return U.Release().index('WIMAP0')


def inc_text() -> str:
    return ('; Generated by tools/native/s2wi.py (part s2wi, docs/'
            'SCREENS.md). Do not edit.\n\n'
            '; WIMAP0\'s lump number in the release (upstream\'s picturenum, '
            'PALST\'s PS_PICTURE)\n'
            'WI_PICNUM       = $%04X\n' % picnum())


def write_inc(path: Path) -> None:
    text = inc_text()
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_text(text)
    tmp.replace(path)


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--inc', type=Path)
    args = ap.parse_args(argv)
    if args.inc:
        write_inc(args.inc)
        return 0
    ap.print_help()
    return 2


if __name__ == '__main__':
    sys.exit(main())
