#!/usr/bin/env python3
"""Build the seed tables of the port: the built-in default table and the
table files on the disk.

A table is the object database of the original (LOGIC, WSET, PBDATA:
count, sizes, records) with the port's L-record convention: on disk and
in the built-in image, bytes 0-1 of every L-record hold (kind, frame) and
bytes 5-7, 10-15 are zero; `table_normalise` (main.s) fills them in from
the kind table when the table is installed. Vertex coordinates are table
units (x 0..153, y 0..191); a part is placed by shifting its kit template
(from parts.json) so that its sprite box lands at the requested position.

    python3 tools/make_tables.py --parts build/parts.json --out build/tables \
        [--default build/default_table.s]
"""

import argparse
import json
from pathlib import Path

WSET_DEFAULT = [4, 4, 3, 4]         # gravity, speed, kick, elasticity


def rotate_down(xs, ys):
    """Rotate the vertex lists so that the first edge goes down (Y0 < Y1),
    as the scan converter requires of every stored polygon."""
    n = len(xs)
    for k in range(n):
        if ys[k] < ys[(k + 1) % n]:
            return xs[k:] + xs[:k], ys[k:] + ys[:k]
    raise ValueError('degenerate polygon')


def polygon(xs, ys, colour, border=False):
    xs, ys = rotate_down(xs, ys)
    return bytes([2 if border else 1, colour, len(xs)] + xs + ys)


def part(parts, name, x, y):
    """A library object at sprite box position (x, y): the template shifted."""
    p = next(q for q in parts if q['name'] == name)
    dx = x - p['x0']
    dy = y - (p['y0'] - p['hoty'])
    xs = [v + dx for v in p['x']]
    ys = [v + dy for v in p['y']]
    assert all(0 <= v <= 153 for v in xs) and all(1 <= v <= 190 for v in ys), (name, xs, ys)
    rec = bytes([3, 0x10, len(xs)] + xs + ys)
    # L-record: kind, frame, y, x lo, x hi, h, w, stride, time, score, vectors, state
    lrec = bytearray(p['objlen'] - len(rec))
    lrec[0] = p['kind']
    lrec[1] = 0
    lrec[2] = p['y0'] + dy
    lrec[3] = p['x0'] + dx
    lrec[8] = p['time']
    lrec[9] = p['score']
    return rec + bytes(lrec)


def table_one(parts):
    objs = []
    # the border: the outside of this outline is the cabinet
    top_arc = [(150, 30), (146, 18), (138, 10), (126, 5), (110, 3), (44, 3), (28, 5), (16, 10), (8, 18), (3, 30)]
    xs = [3, 3, 150] + [v[0] for v in top_arc]
    ys = [30, 190, 190] + [v[1] for v in top_arc]
    objs.append(polygon(xs, ys, 11, border=True))
    # the launcher lane wall
    objs.append(polygon([139, 139, 141, 141], [60, 188, 188, 60], 2))
    # lower guides toward the flippers
    objs.append(polygon([3, 45, 45, 3], [156, 180, 184, 164], 3))
    objs.append(polygon([138, 138, 96, 96], [156, 164, 184, 180], 3))
    # the deflector at the lane's top: a solid triangle against the border
    # whose hypotenuse sends the ball left into the playfield
    objs.append(polygon([141, 150, 150], [44, 30, 44], 3))
    # parts
    objs.append(part(parts, 'LEFTFLIPPER', 46, 168))
    objs.append(part(parts, 'RIGHTFLIPPER', 78, 168))
    objs.append(part(parts, 'LKICK', 10, 132))
    objs.append(part(parts, 'RKICK', 108, 132))
    objs.append(part(parts, 'BMP1', 38, 56))
    objs.append(part(parts, 'BMP1', 80, 56))
    objs.append(part(parts, 'BMP2', 62, 84))
    objs.append(part(parts, 'LANE1', 46, 14))
    objs.append(part(parts, 'LANE1', 90, 14))
    objs.append(part(parts, 'ROLL1', 24, 24))
    objs.append(part(parts, 'ROLL2', 68, 20))
    objs.append(part(parts, 'ROLL3', 112, 24))
    objs.append(part(parts, 'DROP1', 96, 108))
    objs.append(part(parts, 'TARG4', 8, 92))
    objs.append(part(parts, 'TARG5', 8, 104))
    objs.append(part(parts, 'TARG6', 8, 116))
    objs.append(part(parts, 'SPIN1', 60, 118))
    objs.append(part(parts, 'LAUNCHER', 144, 176))
    objs.append(part(parts, 'BALL', 144, 150))
    return objs


def database(objs, wset=WSET_DEFAULT, logic=None):
    logic = logic or [0] * 24
    pbdata = bytes([len(objs)] + [len(o) for o in objs]) + b''.join(objs)
    return bytes(logic) + bytes(wset) + pbdata


def pcs_file(db):
    return b'PCS1' + db + b'OVL1' + bytes(72) + b'\x01\x01'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--parts', required=True)
    ap.add_argument('--out', required=True, help='directory for the .PCS files')
    ap.add_argument('--default', help='write the built-in table as ca65 data')
    args = ap.parse_args()
    parts = json.loads(Path(args.parts).read_text())['parts']
    tables = {'TABLE1': table_one(parts)}
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for name, objs in tables.items():
        (out / (name + '.PCS')).write_bytes(pcs_file(database(objs)))
    if args.default:
        db = database(tables['TABLE1'])
        lines = ['; Generated by tools/make_tables.py. Do not edit.',
                 '; The built-in table: LOGIC, WSET, PBDATA (L-records hold kind, frame).',
                 '.setcpu "65C02"', '.export default_table, default_table_len',
                 '.segment "RODATA"', 'default_table:']
        for i in range(0, len(db), 16):
            lines.append('        .byte ' + ','.join('$%02X' % b for b in db[i:i + 16]))
        lines.append('default_table_len: .word %d' % len(db))
        Path(args.default).write_text('\n'.join(lines) + '\n')
    print('tables: %s (%d bytes)' % (', '.join(tables), len(database(tables['TABLE1']))))


if __name__ == '__main__':
    main()
