#!/usr/bin/env python3
"""Convert the upstream LISA 2.5 game source to one ca65 source file.

The converter reads the tokenized files from the upstream SOURCE disk and
follows the ICL chain from RUN. It makes these changes:

  * EPZ/EQU become '=' assignments.
  * '^n' local labels and their '<n' / '>n' references get unique names.
  * BLT/BGE become BCC/BCS; '/expr' becomes '#>(expr)'; '#label' takes the
    low byte, as LISA does.
  * "x" is high-bit ASCII, 'x' is low ASCII; STR is a counted string.
  * ORG starts a new segment; OBJ, DCM, LST and NLS are dropped.
  * Labels that clash with a 65C02 mnemonic get an 'L_' prefix.
  * Port layout only: each 'JSR DHD' calls a numbered trampoline that loads
    its call-site id and jumps to E_DHD; 'JSR $FC58' (HOME) calls E_HOME.

A patch file can drop routine bodies that the port replaces. Each dropped
range is [first label, end label); both labels must exist in the named file.
"""

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lisa  # noqa: E402

MNEMONICS = set("""
ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRA BRK BVC BVS CLC CLD CLI CLV CMP
CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP
PHX PHY PLA PLP PLX PLY ROL ROR RTI RTS SBC SEC SED SEI STA STX STY STZ TAX
TAY TRB TSB TSX TXA TXS TYA A X Y
""".split())
RENAMED_BRANCHES = {"BLT": "BCC", "BGE": "BCS"}
DROPPED = {"OBJ", "DCM", "LST", "NLS"}
IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
# Upstream reads these at fixed addresses inside its data image.
PORT_TABLES = {"TORDX", "TORDY", "STOEX", "STOEY", "WTOBX", "WTOBY"}


def load_chain(files, start="RUN"):
    """Return [(file name, line number, text)] for the whole ICL chain."""
    out = []
    name = start
    while name:
        following = None
        for number, text in enumerate(lisa.detokenize(files[name][1]), 1):
            match = re.match(r'\s+ICL\s+"([^"]+)"', text)
            if match:
                following = match.group(1)
                break
            out.append((name, number, text))
        name = following
    return out


def split_line(text):
    if not text.strip() or text[0] in ";*":
        return None
    label = text[:9].strip()
    fields = text[9:].split(None, 1) if len(text) > 9 else []
    if label.endswith(":"):
        return label[:-1], "", ""
    op = fields[0] if fields else ""
    arg = fields[1].rstrip() if len(fields) > 1 else ""
    return label, op, arg


def safe(name):
    return "L_" + name if name.upper() in MNEMONICS else name


def convert_operand(op, arg, resolve_local):
    if not arg:
        return ""
    if arg[0] in "<>" and arg[1:].isdigit():
        return resolve_local(arg[0], arg[1:])

    def literal(match):
        char = match.group(2)
        return "$%02X" % (ord(char) | (0x80 if match.group(1) == '"' else 0))

    arg = re.sub(r"""(["'])(.)\1""", literal, arg)
    # Hex and decimal literals are matched first so their digits stay as is.
    arg = re.sub(r"\$[0-9A-Fa-f]+|\d+|" + IDENT.pattern,
                 lambda m: safe(m.group(0))
                 if IDENT.fullmatch(m.group(0)) and
                 not re.search(r",\s*%s$" % m.group(0), arg) else m.group(0),
                 arg)
    if arg.startswith("/"):
        return "#>(%s)" % arg[1:]
    if arg.startswith("#") and not re.fullmatch(r"#(\$[0-9A-Fa-f]+|\d+)", arg):
        return "#<(%s)" % arg[1:]
    return arg


def convert(lines, drops, layout="port"):
    # Locate local label definitions for '<n' and '>n' references.
    local_defs = {}
    for index, (_, _, text) in enumerate(lines):
        parts = split_line(text)
        if parts and parts[0].startswith("^"):
            local_defs.setdefault(parts[0][1:], []).append(index)

    dropping = None
    seen_labels = {}
    dhd_sites = []
    out = [
        "; Generated by tools/lisa2ca65.py from the upstream SOURCE disk.",
        "; Do not edit.",
        ".setcpu \"65C02\"",
        ".feature labels_without_colons",
        "",
    ]
    segment = 0
    out.append('.segment "GAME%d"' % segment)
    if layout == "port":
        out.append("GAME_ENTRY:")
    for index, (name, number, text) in enumerate(lines):
        parts = split_line(text)
        if parts is None:
            continue
        label, op, arg = parts
        # A range ends at its end label, or at the end of its file.
        if dropping and (name != dropping[0] or label == dropping[1]):
            dropping = None
        if not dropping and (name, label) in drops:
            dropping = (name, drops[(name, label)])
            seen_labels[(name, label)] = True
            out.append("; %s:%d %s dropped, replaced by the port" %
                       (name, number, label))
        if dropping:
            continue

        def resolve_local(direction, digit, index=index):
            places = local_defs.get(digit, [])
            if direction == "<":
                found = [p for p in places if p <= index]
                target = found[-1] if found else None
            else:
                found = [p for p in places if p > index]
                target = found[0] if found else None
            if target is None:
                raise ValueError("%s:%d no local label ^%s" %
                                 (name, number, digit))
            return "LOC%d_%s" % (target, digit)

        if label.startswith("^"):
            label = "LOC%d_%s" % (index, label[1:])
        elif label:
            label = safe(label)
        if layout == "port" and label == "RIN":
            # RIN is the top-level restart point: control comes here by
            # JMP from nested calls and never returns. Upstream leaks stack
            # on each restart; the port keeps a routine at $0110, so the
            # stack is reset here.
            out.append("RIN         LDX #$FF")
            out.append("            TXS")
            label = ""
        if op in DROPPED:
            if label:
                out.append(label)
            continue
        if op == "END":
            break
        if op in ("EPZ", "EQU"):
            if layout == "port" and label in PORT_TABLES:
                continue        # the port links its own copy of the table
            out.append("%s = %s" % (label, convert_operand(op, arg, None)))
            continue
        if op == "ORG":
            # Upstream splits its object buffer with ORG, but the run-time
            # code is contiguous after the first ORG. The port ignores every
            # ORG. The baseline keeps the first one and checks the others.
            if layout == "baseline" and segment == 0:
                segment = 1
                out.append('.segment "GAME1"  ; ORG %s' % arg)
            elif layout == "baseline":
                out.append('.assert * = %s, warning, "ORG %s is not contiguous"'
                           % (arg, arg))
            continue
        if op == "HEX":
            data = bytes.fromhex(arg)
            body = ".byte " + ",".join("$%02X" % b for b in data)
        elif op == "ADR" or op == ".DA":
            body = ".addr " + convert_operand(op, arg, None)
        elif op == "STR":
            string = arg[1:arg.rindex(arg[0])]
            high = 0x80 if arg[0] == '"' else 0
            data = [len(string)] + [ord(c) | high for c in string]
            body = ".byte " + ",".join("$%02X" % b for b in data)
        elif op == "":
            body = ""
        elif layout == "port" and op == "JSR" and arg == "DHD":
            # Each call site gets an id, so the engine can pair a sprite
            # with the same sprite of the previous logic tick.
            body = "JSR DHD_SITE_%d" % len(dhd_sites)
            dhd_sites.append("%s:%d" % (name, number))
        elif layout == "port" and op == "JSR" and arg == "$FC58":
            body = "JSR E_HOME"         # text screen: the engine leaves SHR
        else:
            mnemonic = RENAMED_BRANCHES.get(op, op)
            body = (mnemonic + " " +
                    convert_operand(op, arg, resolve_local)).rstrip()
        out.append(("%-12s%s" % (label, body)).rstrip()
                   if label else "            " + body)
    for site, where in enumerate(dhd_sites):
        out.append("DHD_SITE_%d LDA #%d  ; %s" % (site, site, where))
        out.append("            JMP E_DHD")
    if layout == "port":
        out.append("DHD_SITE_COUNT = %d" % len(dhd_sites))
    missing = [key for key in drops if key not in seen_labels]
    if missing:
        raise ValueError("drop labels not found: %s" % missing)
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("upstream")
    parser.add_argument("--output", required=True)
    parser.add_argument("--drops", help="JSON list of [file, first, end]")
    parser.add_argument("--layout", choices=("port", "baseline"),
                        default="port")
    args = parser.parse_args()
    disk = next(Path(args.upstream).glob("*SOURCE*.dsk"))
    lines = load_chain(lisa.read_dsk(disk))
    drops = {}
    if args.drops:
        for name, first, end in json.loads(Path(args.drops).read_text()):
            drops[(name, first)] = end
    Path(args.output).write_text(convert(lines, drops, args.layout))
    print("%s: %d source lines" % (args.output, len(lines)))


if __name__ == "__main__":
    main()
