#!/usr/bin/env python3
"""Build the Phasor music table: "Fuer Elise" (Beethoven, 1810), A section.

This is a new arrangement written for this port. The upstream disks do not
hold the game's note file, and the piece itself is in the public domain.

Twelve voices = four AY chips x three channels. Voice = chip * 3 + channel.
Chips 0 and 2 also exist on a plain Mockingboard, so the melody and the
left hand use them. Chips 1 and 3 add a detuned chorus and a low octave;
the driver skips them when the card is not in Phasor native mode. Chip 2
channel C (voice 8) is left free for sound effects.

Output (ca65 source): a list of events on a 60 Hz time base.
    .byte wait_ticks            ; 0 = end of tune (the driver loops)
    .byte voice | $80 if last event of this group
    .word period                ; 12-bit AY tone period, 0 = note off
"""

import argparse
from pathlib import Path

PSG_CLOCK_NATIVE = 2 * 1020484      # Phasor native mode doubles the clock
TICKS_PER_16TH = 11

NOTE_INDEX = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def midi(name):
    letter, rest = name[0], name[1:]
    sharp = rest.startswith("#")
    octave = int(rest[1:] if sharp else rest)
    return 12 * (octave + 1) + NOTE_INDEX[letter] + (1 if sharp else 0)


def period(note, detune=0.0, native=True):
    frequency = 440.0 * 2 ** ((note - 69 + detune) / 12)
    clock = PSG_CLOCK_NATIVE if native else PSG_CLOCK_NATIVE // 2
    return max(1, min(4095, round(clock / (16 * frequency))))


# One bar = six sixteenths. '-' holds or rests for one sixteenth.
RIGHT = """
- - - - E5 D#5 |
E5 D#5 E5 B4 D5 C5 | A4 - - C4 E4 A4 | B4 - - E4 G#4 B4 | C5 - - E4 E5 D#5 |
E5 D#5 E5 B4 D5 C5 | A4 - - C4 E4 A4 | B4 - - E4 C5 B4 | A4 - - - E5 D#5 |
E5 D#5 E5 B4 D5 C5 | A4 - - C4 E4 A4 | B4 - - E4 G#4 B4 | C5 - - E4 E5 D#5 |
E5 D#5 E5 B4 D5 C5 | A4 - - C4 E4 A4 | B4 - - E4 C5 B4 | A4 - - B4 C5 D5 |
E5 - - G4 F5 E5 | D5 - - F4 E5 D5 | C5 - - E4 D5 C5 | B4 - - E4 E5 - |
- E5 E6 - - D#5 | E5 - - D#5 E5 D#5 |
E5 D#5 E5 B4 D5 C5 | A4 - - C4 E4 A4 | B4 - - E4 G#4 B4 | C5 - - E4 E5 D#5 |
E5 D#5 E5 B4 D5 C5 | A4 - - C4 E4 A4 | B4 - - E4 C5 B4 | A4 - - - - - |
"""
LEFT = """
- - - - - - |
- - - - - - | A2 E3 A3 - - - | E2 E3 G#3 - - - | A2 E3 A3 - - - |
- - - - - - | A2 E3 A3 - - - | E2 E3 G#3 - - - | A2 E3 A3 - - - |
- - - - - - | A2 E3 A3 - - - | E2 E3 G#3 - - - | A2 E3 A3 - - - |
- - - - - - | A2 E3 A3 - - - | E2 E3 G#3 - - - | A2 E3 A3 - - - |
C3 G3 C4 - - - | G2 G3 B3 - - - | A2 E3 A3 - - - | E2 E3 E4 - - - |
- - - - - - | - - - - - - |
- - - - - - | A2 E3 A3 - - - | E2 E3 G#3 - - - | A2 E3 A3 - - - |
- - - - - - | A2 E3 A3 - - - | E2 E3 G#3 - - - | A2 E3 A3 - - - |
"""

MELODY_VOICES = (0, 1)              # chip 0: alternate so notes overlap
CHORUS_VOICES = (3, 4)              # chip 1: detuned copy of the melody
LEFT_VOICES = (6, 7, 2)             # chips 2 and 0: arpeggio notes ring on
LOW_VOICES = (9, 10, 11)            # chip 3: left hand one octave down


def steps(text):
    return [token for token in text.replace("|", " ").split()]


def build():
    events = {}                     # tick -> list of (voice, period)

    def add(tick, voice, value):
        events.setdefault(tick, []).append((voice, value))

    def lay(line, voices, detune=0.0, shift=0):
        turn = 0
        for index, token in enumerate(steps(line)):
            if token == "-":
                continue
            voice = voices[turn % len(voices)]
            turn += 1
            add(index * TICKS_PER_16TH, voice,
                period(midi(token) + shift, detune))

    lay(RIGHT, MELODY_VOICES)
    lay(RIGHT, CHORUS_VOICES, detune=0.08)
    lay(LEFT, LEFT_VOICES)
    lay(LEFT, LOW_VOICES, shift=-12)
    length = len(steps(RIGHT)) * TICKS_PER_16TH
    return events, length


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    events, length = build()
    lines = ["; Generated by tools/make_music.py. Do not edit.",
             "music_data:"]
    clock = 0
    for tick in sorted(events) + [length]:
        wait = tick - clock
        while wait > 255:
            # A wait of 255 with an empty group keeps long rests exact.
            lines.append("    .byte 255, $FF")
            wait -= 255
        clock = tick
        if tick == length:
            lines.append("    .byte %d, $FE      ; end: loop" % max(1, wait))
            break
        group = events[tick]
        lines.append("    .byte %d" % wait)
        for position, (voice, value) in enumerate(group):
            last = 0x80 if position == len(group) - 1 else 0
            lines.append("    .byte $%02X" % (voice | last))
            lines.append("    .word %d" % value)
    Path(args.output).write_text("\n".join(lines) + "\n")
    print("%d event groups, %d ticks (%.1f s)" %
          (len(events), length, length / 60))


if __name__ == "__main__":
    main()
