#!/usr/bin/env python3
"""Assemble the upstream DATA disk into a memory image and read its shapes.

The DATA sources use only ORG, ADR, HEX, EQU, ICL, NLS and END, so a small
two-pass assembler is enough. The image is built at its assembly address
($2C00). The game moves it up by RELOC_DELTA at run time; pointers in the
tables already hold run-time addresses (minus one, because the blit indexes
rows with Y = XSIZE..1).
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lisa  # noqa: E402

RELOC_DELTA = 0x3400
TABLE_BASE = 0x2C00          # HS; DS, HSIZ, HD follow at +$100 each
SHAPE_COUNT = 128
CHAIN_START = "DATA"


def _source_lines(files, name):
    """Yield the lines of a file and of every file it includes."""
    for line in lisa.detokenize(files[name][1]):
        match = re.match(r'\s+ICL\s+"([^"]+)"', line)
        if match:
            yield from _source_lines(files, match.group(1))
            return
        yield line


def _evaluate(text, labels, strict):
    total = 0
    for sign, term in re.findall(r"([+-]?)\s*([$A-Za-z0-9_]+)", text):
        if term.startswith("$"):
            value = int(term[1:], 16)
        elif term[0].isdigit():
            value = int(term)
        elif term in labels:
            value = labels[term]
        elif strict:
            raise KeyError("undefined label %s" % term)
        else:
            value = 0
        total += -value if sign == "-" else value
    return total & 0xFFFF


def assemble(upstream):
    """Return (memory bytearray of 64 KiB, labels dict)."""
    disk = next(Path(upstream).glob("*DATA*.dsk"))
    files = lisa.read_dsk(disk)
    lines = list(_source_lines(files, CHAIN_START))
    labels = {}
    memory = bytearray(0x10000)
    for strict in (False, True):
        pc = 0
        for line in lines:
            if not line.strip() or line[0] in ";*":
                continue
            label = line[:9].strip().rstrip(":")
            fields = line[9:].split(None, 1)
            op = fields[0] if fields else ""
            arg = fields[1].strip() if len(fields) > 1 else ""
            if op == "EQU":
                labels[label] = _evaluate(arg, labels, strict)
                continue
            if label:
                labels[label] = pc
            if op == "ORG":
                pc = _evaluate(arg, labels, True)
            elif op == "ADR":
                value = _evaluate(arg, labels, strict)
                memory[pc] = value & 0xFF
                memory[pc + 1] = value >> 8
                pc += 2
            elif op == "HEX":
                data = bytes.fromhex(arg)
                memory[pc:pc + len(data)] = data
                pc += len(data)
            elif op == "END":
                break
    return memory, labels


def read_shapes(memory):
    """Return a list of shape dicts read through the HS/DS/HSIZ/HD tables.

    rows[y][x] holds one byte per source byte column; bit 0 is the left
    pixel. mask bit 1 = keep the background, 0 = inside the shape.
    """
    shapes = []
    for index in range(SHAPE_COUNT):
        entry = TABLE_BASE + index * 2
        mask_ptr = memory[entry] | (memory[entry + 1] << 8)
        data_ptr = memory[entry + 0x100] | (memory[entry + 0x101] << 8)
        xsize = memory[entry + 0x200]
        ysize = memory[entry + 0x201]
        hot_x = memory[entry + 0x300]
        hot_y = memory[entry + 0x301]
        if mask_ptr == 0 or xsize == 0 or ysize == 0:
            shapes.append(None)
            continue
        # Table pointers are run-time addresses minus one.
        mask_at = mask_ptr + 1 - RELOC_DELTA
        data_at = data_ptr + 1 - RELOC_DELTA
        size = xsize * ysize
        shapes.append({
            "index": index,
            "xsize": xsize,
            "ysize": ysize,
            "hot_x": hot_x,
            "hot_y": hot_y,
            "mask": bytes(memory[mask_at:mask_at + size]),
            "data": bytes(memory[data_at:data_at + size]),
        })
    return shapes


JOINT_TABLES = ("TORDX", "TORDY", "STOEX", "STOEY", "WTOBX", "WTOBY")
JOINT_BASE = TABLE_BASE + 0x400     # 16 signed offsets per table, by angle


def write_joint_tables(memory, path):
    """Write the body joint offset tables as a ca65 include.

    Upstream reads them at fixed run-time addresses after the shape
    tables. The port places them in its own image under the same labels.
    """
    lines = ["; Generated by tools/shapedata.py from the upstream DATA disk.",
             "; Do not edit."]
    for number, name in enumerate(JOINT_TABLES):
        start = JOINT_BASE + number * 16
        lines.append("%s: .byte %s" % (name, ",".join(
            "$%02X" % b for b in memory[start:start + 16])))
    Path(path).write_text("\n".join(lines) + "\n")


def main():
    if len(sys.argv) == 4 and sys.argv[2] == "--joint-tables":
        memory, _ = assemble(sys.argv[1])
        write_joint_tables(memory, sys.argv[3])
        return
    memory, labels = assemble(sys.argv[1])
    shapes = read_shapes(memory)
    used = [s for s in shapes if s]
    print("labels %d, shapes %d" % (len(labels), len(used)))
    total = 0
    for shape in used:
        total += len(shape["mask"])
        print("%3d  %dx%-3d bytes  hot %4d,%-4d" % (
            shape["index"], shape["xsize"], shape["ysize"],
            shape["hot_x"] - 256 * (shape["hot_x"] > 127),
            shape["hot_y"] - 256 * (shape["hot_y"] > 127)))
    print("mask bytes total", total)
    low = min(v for k, v in labels.items() if k.startswith(("MASK", "DET")))
    high = max(v for k, v in labels.items() if k.startswith(("MASK", "DET")))
    print("shape data $%04X-$%04X" % (low, high))


if __name__ == "__main__":
    main()
