/* Generated by tools/gen_info.py -- do not edit. */

/* Doom's states and thing types for episode 1, from the compact source
 * in tools/gen_info.py (vanilla names, order and values). */
#include "doomdata.h"
#include "info.h"

#ifdef DD_MAPDIR

const uint8_t st_sprite[424] = {
    SPR_TROO, SPR_SHTG, SPR_PUNG, SPR_PUNG, SPR_PUNG, SPR_PUNG, SPR_PUNG, SPR_PUNG,
    SPR_PUNG, SPR_PUNG, SPR_PISG, SPR_PISG, SPR_PISG, SPR_PISG, SPR_PISG, SPR_PISG,
    SPR_PISG, SPR_PISF, SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTG,
    SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTG, SPR_SHTF, SPR_SHTF,
    SPR_CHGG, SPR_CHGG, SPR_CHGG, SPR_CHGG, SPR_CHGG, SPR_CHGG, SPR_CHGF, SPR_CHGF,
    SPR_MISG, SPR_MISG, SPR_MISG, SPR_MISG, SPR_MISG, SPR_MISG, SPR_MISF, SPR_MISF,
    SPR_MISF, SPR_MISF, SPR_SAWG, SPR_SAWG, SPR_SAWG, SPR_SAWG, SPR_SAWG, SPR_SAWG,
    SPR_SAWG, SPR_PLSG, SPR_PLSG, SPR_PLSG, SPR_PLSG, SPR_PLSG, SPR_PLSF, SPR_PLSF,
    SPR_BLUD, SPR_BLUD, SPR_BLUD, SPR_PUFF, SPR_PUFF, SPR_PUFF, SPR_PUFF, SPR_BAL1,
    SPR_BAL1, SPR_BAL1, SPR_BAL1, SPR_BAL1, SPR_BAL2, SPR_BAL2, SPR_BAL2, SPR_BAL2,
    SPR_BAL2, SPR_PLSS, SPR_PLSS, SPR_PLSE, SPR_PLSE, SPR_PLSE, SPR_PLSE, SPR_PLSE,
    SPR_MISL, SPR_MISL, SPR_MISL, SPR_MISL, SPR_TFOG, SPR_TFOG, SPR_TFOG, SPR_TFOG,
    SPR_TFOG, SPR_TFOG, SPR_TFOG, SPR_TFOG, SPR_TFOG, SPR_TFOG, SPR_TFOG, SPR_TFOG,
    SPR_IFOG, SPR_IFOG, SPR_IFOG, SPR_IFOG, SPR_IFOG, SPR_IFOG, SPR_IFOG, SPR_PLAY,
    SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY,
    SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY,
    SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY, SPR_PLAY,
    SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS,
    SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS,
    SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS,
    SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_POSS, SPR_SPOS, SPR_SPOS, SPR_SPOS,
    SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS,
    SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS,
    SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS, SPR_SPOS,
    SPR_SPOS, SPR_SPOS, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO,
    SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO,
    SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO,
    SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_TROO, SPR_SARG, SPR_SARG,
    SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG,
    SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG, SPR_SARG,
    SPR_SARG, SPR_SARG, SPR_SARG, SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD,
    SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD, SPR_HEAD,
    SPR_HEAD, SPR_BAL7, SPR_BAL7, SPR_BAL7, SPR_BAL7, SPR_BAL7, SPR_BOSS, SPR_BOSS,
    SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS,
    SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS,
    SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_BOSS, SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL,
    SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL,
    SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_SKUL, SPR_ARM1, SPR_ARM1, SPR_ARM2, SPR_ARM2,
    SPR_BAR1, SPR_BAR1, SPR_BEXP, SPR_BEXP, SPR_BEXP, SPR_BEXP, SPR_BEXP, SPR_BON1,
    SPR_BON1, SPR_BON1, SPR_BON1, SPR_BON1, SPR_BON1, SPR_BON2, SPR_BON2, SPR_BON2,
    SPR_BON2, SPR_BON2, SPR_BON2, SPR_BKEY, SPR_BKEY, SPR_RKEY, SPR_RKEY, SPR_YKEY,
    SPR_YKEY, SPR_BSKU, SPR_BSKU, SPR_RSKU, SPR_RSKU, SPR_YSKU, SPR_YSKU, SPR_STIM,
    SPR_MEDI, SPR_SOUL, SPR_SOUL, SPR_SOUL, SPR_SOUL, SPR_SOUL, SPR_SOUL, SPR_PINV,
    SPR_PINV, SPR_PINV, SPR_PINV, SPR_PSTR, SPR_PINS, SPR_PINS, SPR_PINS, SPR_PINS,
    SPR_SUIT, SPR_PMAP, SPR_PMAP, SPR_PMAP, SPR_PMAP, SPR_PMAP, SPR_PMAP, SPR_PVIS,
    SPR_PVIS, SPR_CLIP, SPR_AMMO, SPR_ROCK, SPR_BROK, SPR_CELL, SPR_CELP, SPR_SHEL,
    SPR_SBOX, SPR_BPAK, SPR_MGUN, SPR_CSAW, SPR_LAUN, SPR_PLAS, SPR_SHOT, SPR_COLU,
    SPR_GOR1, SPR_GOR1, SPR_GOR1, SPR_GOR1, SPR_POL5, SPR_POL6, SPR_POL6, SPR_GOR2,
    SPR_GOR4, SPR_GOR5, SPR_SMIT, SPR_COL1, SPR_COL2, SPR_COL3, SPR_CAND, SPR_CBRA,
    SPR_TRE1, SPR_TRE2, SPR_ELEC, SPR_FSKU, SPR_FSKU, SPR_FSKU, SPR_COL5, SPR_COL5,
    SPR_TBLU, SPR_TBLU, SPR_TBLU, SPR_TBLU, SPR_TGRN, SPR_TGRN, SPR_TGRN, SPR_TGRN,
    SPR_TRED, SPR_TRED, SPR_TRED, SPR_TRED, SPR_SMBT, SPR_SMBT, SPR_SMBT, SPR_SMBT,
    SPR_SMGT, SPR_SMGT, SPR_SMGT, SPR_SMGT, SPR_SMRT, SPR_SMRT, SPR_SMRT, SPR_SMRT,
};
const uint8_t st_frame[424] = {
    0, 4, 0, 0, 0, 1, 2, 3, 2, 1, 0, 0, 0, 0, 1, 2,
    1, 128, 0, 0, 0, 0, 0, 1, 2, 3, 2, 1, 0, 0, 128, 129,
    0, 0, 0, 0, 1, 1, 128, 129, 0, 0, 0, 1, 1, 1, 128, 129,
    130, 131, 2, 3, 2, 2, 0, 1, 1, 0, 0, 0, 0, 1, 128, 129,
    2, 1, 0, 128, 1, 2, 3, 128, 129, 130, 131, 132, 128, 129, 130, 131,
    132, 128, 129, 128, 129, 130, 131, 132, 128, 129, 130, 131, 128, 129, 128, 129,
    130, 131, 132, 133, 134, 135, 136, 137, 128, 129, 128, 129, 130, 131, 132, 0,
    0, 1, 2, 3, 4, 133, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 0, 1, 0, 0, 1, 1, 2, 2,
    3, 3, 4, 5, 4, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
    16, 17, 18, 19, 20, 0, 1, 0, 0, 1, 1, 2, 2, 3, 3, 4,
    133, 4, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 0, 1, 0, 0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7,
    7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 0, 1,
    0, 0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 7, 8, 9, 10,
    11, 12, 13, 0, 0, 1, 2, 131, 4, 4, 5, 6, 7, 8, 9, 10,
    11, 128, 129, 130, 131, 132, 0, 1, 0, 0, 1, 1, 2, 2, 3, 3,
    4, 5, 6, 7, 7, 8, 9, 10, 11, 12, 13, 14, 128, 129, 128, 129,
    130, 131, 130, 131, 132, 132, 133, 134, 135, 136, 9, 10, 0, 129, 0, 129,
    0, 1, 128, 129, 130, 131, 132, 0, 1, 2, 3, 2, 1, 0, 1, 2,
    3, 2, 1, 0, 129, 0, 129, 0, 129, 0, 129, 0, 129, 0, 129, 0,
    0, 128, 129, 130, 131, 130, 129, 128, 129, 130, 131, 128, 128, 129, 130, 131,
    128, 128, 129, 130, 131, 130, 129, 128, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 128, 0, 1, 2, 1, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 128, 128, 0, 0, 0, 128, 129, 130, 0, 1,
    128, 129, 130, 131, 128, 129, 130, 131, 128, 129, 130, 131, 128, 129, 130, 131,
    128, 129, 130, 131, 128, 129, 130, 131,
};
const uint8_t st_tics[424] = {
    255, 0, 1, 1, 1, 4, 4, 5, 4, 5, 1, 1, 1, 4, 6, 4,
    5, 7, 1, 1, 1, 3, 7, 5, 5, 4, 5, 5, 3, 7, 4, 3,
    1, 1, 1, 4, 4, 0, 5, 5, 1, 1, 1, 8, 12, 0, 3, 4,
    4, 4, 4, 4, 1, 1, 4, 4, 0, 1, 1, 1, 3, 20, 4, 4,
    8, 8, 8, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 4, 6, 6,
    6, 6, 6, 4, 4, 4, 4, 4, 1, 8, 6, 4, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 255,
    4, 4, 4, 4, 12, 6, 4, 4, 10, 10, 10, 10, 10, 10, 255, 5,
    5, 5, 5, 5, 5, 5, 5, 255, 10, 10, 4, 4, 4, 4, 4, 4,
    4, 4, 10, 8, 8, 3, 3, 5, 5, 5, 5, 255, 5, 5, 5, 5,
    5, 5, 5, 5, 255, 10, 10, 3, 3, 3, 3, 3, 3, 3, 3, 10,
    10, 10, 3, 3, 5, 5, 5, 5, 255, 5, 5, 5, 5, 5, 5, 5,
    5, 255, 10, 10, 3, 3, 3, 3, 3, 3, 3, 3, 8, 8, 6, 2,
    2, 8, 8, 6, 6, 255, 5, 5, 5, 5, 5, 5, 5, 255, 10, 10,
    2, 2, 2, 2, 2, 2, 2, 2, 8, 8, 8, 2, 2, 8, 8, 4,
    4, 4, 255, 10, 3, 5, 5, 5, 3, 3, 6, 8, 8, 8, 8, 8,
    255, 4, 4, 6, 6, 6, 10, 10, 3, 3, 3, 3, 3, 3, 3, 3,
    8, 8, 8, 2, 2, 8, 8, 8, 8, 8, 8, 255, 10, 10, 6, 6,
    10, 4, 4, 4, 3, 3, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6,
    6, 6, 5, 5, 5, 10, 10, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 255,
    255, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 255, 6, 6, 6, 6,
    255, 6, 6, 6, 6, 6, 6, 6, 6, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 10, 15, 8, 6, 255, 6, 8, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 6, 6, 6, 14, 14,
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 4, 4, 4,
};
const uint8_t st_action[424] = {
    0x80, 0x12, 0x13, 0x14, 0x15, 0x00, 0x16, 0x00, 0x00, 0x17, 0x13, 0x14,
    0x15, 0x00, 0x18, 0x00, 0x17, 0x19, 0x13, 0x14, 0x15, 0x00, 0x1A, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x17, 0x19, 0x1B, 0x13, 0x14, 0x15, 0x1C,
    0x1C, 0x17, 0x19, 0x1B, 0x13, 0x14, 0x15, 0x1D, 0x1E, 0x17, 0x19, 0x00,
    0x1B, 0x1B, 0x13, 0x13, 0x14, 0x15, 0x1F, 0x1F, 0x17, 0x13, 0x14, 0x15,
    0x20, 0x17, 0x19, 0x19, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x0F, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x00, 0x0D,
    0x00, 0x11, 0x0E, 0x80, 0x80, 0x80, 0x80, 0x00, 0x0C, 0x0E, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x01, 0x01, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
    0x02, 0x02, 0x03, 0x04, 0x00, 0x00, 0x0D, 0x00, 0x0B, 0x0E, 0x80, 0x80,
    0x00, 0x0C, 0x0E, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x01, 0x01, 0x02,
    0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x03, 0x05, 0x00, 0x00, 0x0D,
    0x00, 0x0B, 0x0E, 0x80, 0x80, 0x00, 0x0C, 0x0E, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x01, 0x01, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
    0x03, 0x03, 0x06, 0x00, 0x0D, 0x00, 0x0B, 0x00, 0x0E, 0x80, 0x00, 0x0C,
    0x00, 0x0E, 0x80, 0x80, 0x80, 0x80, 0x01, 0x01, 0x02, 0x02, 0x02, 0x02,
    0x02, 0x02, 0x02, 0x02, 0x03, 0x03, 0x07, 0x00, 0x0D, 0x00, 0x0B, 0x00,
    0x0E, 0x80, 0x80, 0x01, 0x02, 0x03, 0x03, 0x08, 0x00, 0x0D, 0x00, 0x00,
    0x0B, 0x00, 0x00, 0x0E, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x01, 0x01,
    0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x03, 0x03, 0x09, 0x00,
    0x0D, 0x00, 0x0B, 0x00, 0x0E, 0x00, 0x00, 0x10, 0x01, 0x01, 0x02, 0x02,
    0x03, 0x0A, 0x80, 0x80, 0x00, 0x0D, 0x00, 0x0B, 0x00, 0x0E, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x00, 0x0B, 0x00, 0x0F, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80,
};
const uint16_t st_next[424] = {
    0, 0, 2, 3, 4, 6, 7, 8, 9, 2, 10, 11,
    12, 14, 15, 16, 10, 1, 18, 19, 20, 22, 23, 24,
    25, 26, 27, 28, 29, 18, 31, 1, 32, 33, 34, 36,
    37, 32, 1, 1, 40, 41, 42, 44, 45, 40, 47, 48,
    49, 1, 51, 50, 52, 53, 55, 56, 50, 57, 58, 59,
    61, 57, 1, 1, 65, 66, 0, 68, 69, 70, 0, 72,
    71, 74, 75, 0, 77, 76, 79, 80, 0, 82, 81, 84,
    85, 86, 87, 0, 88, 90, 91, 0, 93, 94, 95, 96,
    97, 98, 99, 100, 101, 102, 103, 0, 105, 106, 107, 108,
    109, 110, 0, 0, 113, 114, 115, 112, 111, 116, 119, 111,
    121, 122, 123, 124, 125, 126, 0, 128, 129, 130, 131, 132,
    133, 134, 135, 0, 137, 136, 139, 140, 141, 142, 143, 144,
    145, 138, 147, 148, 138, 150, 138, 152, 153, 154, 155, 0,
    157, 158, 159, 160, 161, 162, 163, 164, 0, 166, 165, 168,
    169, 170, 171, 172, 173, 174, 167, 176, 177, 167, 179, 167,
    181, 182, 183, 184, 0, 186, 187, 188, 189, 190, 191, 192,
    193, 0, 195, 194, 197, 198, 199, 200, 201, 202, 203, 196,
    205, 206, 196, 208, 196, 210, 211, 212, 213, 0, 215, 216,
    217, 218, 219, 220, 221, 0, 223, 222, 225, 226, 227, 228,
    229, 230, 231, 224, 233, 234, 224, 236, 224, 238, 239, 240,
    241, 242, 0, 243, 244, 246, 247, 244, 249, 250, 244, 252,
    253, 254, 255, 256, 0, 258, 257, 260, 261, 0, 263, 262,
    265, 266, 267, 268, 269, 270, 271, 264, 273, 274, 264, 276,
    264, 278, 279, 280, 281, 282, 283, 0, 285, 284, 287, 286,
    289, 290, 291, 290, 293, 286, 295, 296, 297, 298, 299, 0,
    301, 300, 303, 302, 305, 304, 307, 308, 309, 310, 0, 312,
    313, 314, 315, 316, 311, 318, 319, 320, 321, 322, 317, 324,
    323, 326, 325, 328, 327, 330, 329, 332, 331, 334, 333, 0,
    0, 338, 339, 340, 341, 342, 337, 344, 345, 346, 343, 0,
    349, 350, 351, 348, 0, 354, 355, 356, 357, 358, 353, 360,
    359, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 377, 378, 379, 376, 0, 382, 381, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 396,
    397, 395, 399, 398, 401, 402, 403, 400, 405, 406, 407, 404,
    409, 410, 411, 408, 413, 414, 415, 412, 417, 418, 419, 416,
    421, 422, 423, 420,
};

const mobjinfo_t mobjinfo[NUMMOBJTYPES] = {
    { S_PLAY, S_PLAY_RUN1, S_PLAY_PAIN, S_NULL, S_PLAY_ATK1, S_PLAY_DIE1, S_PLAY_XDIE1, 100, 255, 100, 0x02000C06UL, sfx_None, sfx_None, sfx_plpain, sfx_pldeth, sfx_None, 0, 0, 16, 56, 0 },  /* MT_PLAYER */
    { S_POSS_STND, S_POSS_RUN1, S_POSS_PAIN, S_NULL, S_POSS_ATK1, S_POSS_DIE1, S_POSS_XDIE1, 20, 200, 100, 0x00400006UL, sfx_posit1, sfx_pistol, sfx_popain, sfx_podth1, sfx_posact, 8, 8, 20, 56, 0 },  /* MT_POSSESSED */
    { S_SPOS_STND, S_SPOS_RUN1, S_SPOS_PAIN, S_NULL, S_SPOS_ATK1, S_SPOS_DIE1, S_SPOS_XDIE1, 30, 170, 100, 0x00400006UL, sfx_posit2, sfx_None, sfx_popain, sfx_podth2, sfx_posact, 8, 8, 20, 56, 0 },  /* MT_SHOTGUY */
    { S_TROO_STND, S_TROO_RUN1, S_TROO_PAIN, S_TROO_ATK1, S_TROO_ATK1, S_TROO_DIE1, S_TROO_XDIE1, 60, 200, 100, 0x00400006UL, sfx_bgsit1, sfx_None, sfx_popain, sfx_bgdth1, sfx_bgact, 8, 8, 20, 56, 0 },  /* MT_TROOP */
    { S_SARG_STND, S_SARG_RUN1, S_SARG_PAIN, S_SARG_ATK1, S_NULL, S_SARG_DIE1, S_NULL, 150, 180, 400, 0x00400006UL, sfx_sgtsit, sfx_sgtatk, sfx_dmpain, sfx_sgtdth, sfx_dmact, 8, 10, 30, 56, 0 },  /* MT_SERGEANT */
    { S_SARG_STND, S_SARG_RUN1, S_SARG_PAIN, S_SARG_ATK1, S_NULL, S_SARG_DIE1, S_NULL, 150, 180, 400, 0x00440006UL, sfx_sgtsit, sfx_sgtatk, sfx_dmpain, sfx_sgtdth, sfx_dmact, 8, 10, 30, 56, 0 },  /* MT_SHADOWS */
    { S_HEAD_STND, S_HEAD_RUN1, S_HEAD_PAIN, S_NULL, S_HEAD_ATK1, S_HEAD_DIE1, S_NULL, 400, 128, 400, 0x00404206UL, sfx_cacsit, sfx_None, sfx_dmpain, sfx_cacdth, sfx_dmact, 8, 8, 31, 56, 0 },  /* MT_HEAD */
    { S_BOSS_STND, S_BOSS_RUN1, S_BOSS_PAIN, S_BOSS_ATK1, S_BOSS_ATK1, S_BOSS_DIE1, S_NULL, 1000, 50, 1000, 0x00400006UL, sfx_brssit, sfx_None, sfx_dmpain, sfx_brsdth, sfx_dmact, 8, 8, 24, 64, 0 },  /* MT_BRUISER */
    { S_BRBALL1, S_NULL, S_NULL, S_NULL, S_NULL, S_BRBALLX1, S_NULL, 1000, 0, 100, 0x00010610UL, sfx_firsht, sfx_None, sfx_None, sfx_firxpl, sfx_None, 8, 15, 6, 8, 8 },  /* MT_BRUISERSHOT */
    { S_SKULL_STND, S_SKULL_RUN1, S_SKULL_PAIN, S_NULL, S_SKULL_ATK1, S_SKULL_DIE1, S_NULL, 100, 256, 50, 0x00004206UL, sfx_None, sfx_sklatk, sfx_dmpain, sfx_firxpl, sfx_dmact, 8, 8, 16, 56, 3 },  /* MT_SKULL */
    { S_BAR1, S_NULL, S_NULL, S_NULL, S_NULL, S_BEXP, S_NULL, 20, 0, 100, 0x00080006UL, sfx_None, sfx_None, sfx_None, sfx_barexp, sfx_None, 8, 0, 10, 42, 0 },  /* MT_BARREL */
    { S_TBALL1, S_NULL, S_NULL, S_NULL, S_NULL, S_TBALLX1, S_NULL, 1000, 0, 100, 0x00010610UL, sfx_firsht, sfx_None, sfx_None, sfx_firxpl, sfx_None, 8, 10, 6, 8, 3 },  /* MT_TROOPSHOT */
    { S_RBALL1, S_NULL, S_NULL, S_NULL, S_NULL, S_RBALLX1, S_NULL, 1000, 0, 100, 0x00010610UL, sfx_firsht, sfx_None, sfx_None, sfx_firxpl, sfx_None, 8, 10, 6, 8, 5 },  /* MT_HEADSHOT */
    { S_ROCKET, S_NULL, S_NULL, S_NULL, S_NULL, S_EXPLODE1, S_NULL, 1000, 0, 100, 0x00010610UL, sfx_rlaunc, sfx_None, sfx_None, sfx_barexp, sfx_None, 8, 20, 11, 8, 20 },  /* MT_ROCKET */
    { S_PLASBALL, S_NULL, S_NULL, S_NULL, S_NULL, S_PLASEXP, S_NULL, 1000, 0, 100, 0x00010610UL, sfx_plasma, sfx_None, sfx_None, sfx_firxpl, sfx_None, 8, 25, 13, 8, 5 },  /* MT_PLASMA */
    { S_PUFF1, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000210UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_PUFF */
    { S_BLOOD1, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000010UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_BLOOD */
    { S_TFOG, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000210UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_TFOG */
    { S_IFOG, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000210UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_IFOG */
    { S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000018UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_TELEPORTMAN */
    { S_ARM1, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC0 */
    { S_ARM2, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC1 */
    { S_BON1, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC2 */
    { S_BON2, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC3 */
    { S_BKEY, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x02000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC4 */
    { S_RKEY, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x02000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC5 */
    { S_YKEY, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x02000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC6 */
    { S_YSKULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x02000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC7 */
    { S_RSKULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x02000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC8 */
    { S_BSKULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x02000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC9 */
    { S_STIM, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC10 */
    { S_MEDI, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC11 */
    { S_SOUL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC12 */
    { S_PINV, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_INV */
    { S_PSTR, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC13 */
    { S_PINS, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_INS */
    { S_SUIT, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC14 */
    { S_PMAP, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC15 */
    { S_PVIS, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00800001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC16 */
    { S_CLIP, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_CLIP */
    { S_AMMO, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC17 */
    { S_ROCK, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC18 */
    { S_BROK, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC19 */
    { S_CELL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC20 */
    { S_CELP, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC21 */
    { S_SHEL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC22 */
    { S_SBOX, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC23 */
    { S_BPAK, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC24 */
    { S_MGUN, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_CHAINGUN */
    { S_CSAW, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC26 */
    { S_LAUN, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC27 */
    { S_PLAS, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC28 */
    { S_SHOT, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000001UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_SHOTGUN */
    { S_COLU, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC31 */
    { S_TALLGRNCOL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC32 */
    { S_SHRTGRNCOL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC33 */
    { S_TALLREDCOL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC34 */
    { S_HEARTCOL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC37 */
    { S_FLOATSKULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC39 */
    { S_TORCHTREE, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC40 */
    { S_BLUETORCH, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC41 */
    { S_GREENTORCH, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC42 */
    { S_REDTORCH, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC43 */
    { S_BTORCHSHRT, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC44 */
    { S_GTORCHSHRT, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC45 */
    { S_RTORCHSHRT, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC46 */
    { S_STALAGTITE, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC47 */
    { S_TECHPILLAR, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC48 */
    { S_CANDLESTIK, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC49 */
    { S_CANDELABRA, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC50 */
    { S_BLOODYTWITCH, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000302UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 68, 0 },  /* MT_MISC51 */
    { S_MEAT2, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000302UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 84, 0 },  /* MT_MISC52 */
    { S_MEAT4, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000302UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 68, 0 },  /* MT_MISC54 */
    { S_MEAT5, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000302UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 52, 0 },  /* MT_MISC55 */
    { S_MEAT2, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000300UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 84, 0 },  /* MT_MISC56 */
    { S_MEAT4, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000300UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 68, 0 },  /* MT_MISC57 */
    { S_MEAT5, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000300UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 52, 0 },  /* MT_MISC59 */
    { S_BLOODYTWITCH, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000300UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 68, 0 },  /* MT_MISC60 */
    { S_HEAD_DIE6, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC61 */
    { S_PLAY_DIE7, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC62 */
    { S_POSS_DIE5, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC63 */
    { S_SARG_DIE6, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC64 */
    { S_SKULL_DIE6, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC65 */
    { S_TROO_DIE5, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC66 */
    { S_SPOS_DIE5, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC67 */
    { S_PLAY_XDIE9, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC68 */
    { S_PLAY_XDIE9, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC69 */
    { S_GIBS, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000000UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 20, 16, 0 },  /* MT_MISC71 */
    { S_LIVESTICK, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 16, 16, 0 },  /* MT_MISC75 */
    { S_BIGTREE, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, S_NULL, 1000, 0, 100, 0x00000002UL, sfx_None, sfx_None, sfx_None, sfx_None, sfx_None, 8, 0, 32, 16, 0 },  /* MT_MISC76 */
};

const int16_t mi_doomednum[90] = {
    -1, 3004, 9, 3001, 3002, 58, 3005, 3003, -1, 3006, 2035, -1,
    -1, -1, -1, -1, -1, -1, -1, 14, 2018, 2019, 2014, 2015,
    5, 13, 6, 39, 38, 40, 2011, 2012, 2013, 2022, 2023, 2024,
    2025, 2026, 2045, 2007, 2048, 2010, 2046, 2047, 17, 2008, 2049, 8,
    2002, 2005, 2003, 2004, 2001, 2028, 30, 31, 32, 36, 42, 43,
    44, 45, 46, 55, 56, 57, 47, 48, 34, 35, 49, 50,
    52, 53, 59, 60, 62, 63, 22, 15, 18, 21, 23, 20,
    19, 10, 12, 24, 26, 54,
};

const uint8_t rndtable[256] = {
    0, 8, 109, 220, 222, 241, 149, 107, 75, 248, 254, 140, 16, 66, 74, 21,
    211, 47, 80, 242, 154, 27, 205, 128, 161, 89, 77, 36, 95, 110, 85, 48,
    212, 140, 211, 249, 22, 79, 200, 50, 28, 188, 52, 140, 202, 120, 68, 145,
    62, 70, 184, 190, 91, 197, 152, 224, 149, 104, 25, 178, 252, 182, 202, 182,
    141, 197, 4, 81, 181, 242, 145, 42, 39, 227, 156, 198, 225, 193, 219, 93,
    122, 175, 249, 0, 175, 143, 70, 239, 46, 246, 163, 53, 163, 109, 168, 135,
    2, 235, 25, 92, 20, 145, 138, 77, 69, 166, 78, 176, 173, 212, 166, 113,
    94, 161, 41, 50, 239, 49, 111, 164, 70, 60, 2, 37, 171, 75, 136, 156,
    11, 56, 42, 146, 138, 229, 73, 146, 77, 61, 98, 196, 135, 106, 63, 197,
    195, 86, 96, 203, 113, 101, 170, 247, 181, 113, 80, 250, 108, 7, 255, 237,
    129, 226, 79, 107, 112, 166, 103, 241, 24, 223, 239, 120, 198, 58, 60, 82,
    128, 3, 184, 66, 143, 224, 145, 224, 81, 206, 163, 45, 63, 90, 168, 114,
    59, 33, 159, 95, 28, 139, 123, 98, 125, 196, 15, 70, 194, 253, 54, 14,
    109, 226, 71, 17, 161, 93, 186, 87, 244, 138, 20, 52, 123, 251, 26, 36,
    17, 46, 52, 231, 232, 76, 31, 221, 84, 37, 216, 165, 212, 106, 197, 242,
    98, 43, 39, 175, 254, 145, 190, 84, 118, 222, 187, 136, 120, 163, 236, 249,
};

const mobjaction_t mobj_actions[AC_FIRST_WEAPON] = {
    0,
    A_Look,
    A_Chase,
    A_FaceTarget,
    A_PosAttack,
    A_SPosAttack,
    A_TroopAttack,
    A_SargAttack,
    A_HeadAttack,
    A_BruisAttack,
    A_SkullAttack,
    A_Scream,
    A_XScream,
    A_Pain,
    A_Fall,
    A_Explode,
    A_BossDeath,
    A_PlayerScream,
};
const weaponaction_t weapon_actions[NUMACTIONS - AC_FIRST_WEAPON] = {
    A_Light0,
    A_WeaponReady,
    A_Lower,
    A_Raise,
    A_Punch,
    A_ReFire,
    A_FirePistol,
    A_Light1,
    A_FireShotgun,
    A_Light2,
    A_FireCGun,
    A_GunFlash,
    A_FireMissile,
    A_Saw,
    A_FirePlasma,
};

#endif
