/* Generated by tools/gen_info.py -- do not edit. */

/* Doom's states and thing types for episode 1 (tools/gen_info.py,
 * DESIGN.md section 9). Vanilla names and order; see info.c. */
#ifndef INFO_H
#define INFO_H

#include <stdint.h>

#define NUMSTATES 424
enum {
    S_NULL,
    S_LIGHTDONE,
    S_PUNCH,
    S_PUNCHDOWN,
    S_PUNCHUP,
    S_PUNCH1,
    S_PUNCH2,
    S_PUNCH3,
    S_PUNCH4,
    S_PUNCH5,
    S_PISTOL,
    S_PISTOLDOWN,
    S_PISTOLUP,
    S_PISTOL1,
    S_PISTOL2,
    S_PISTOL3,
    S_PISTOL4,
    S_PISTOLFLASH,
    S_SGUN,
    S_SGUNDOWN,
    S_SGUNUP,
    S_SGUN1,
    S_SGUN2,
    S_SGUN3,
    S_SGUN4,
    S_SGUN5,
    S_SGUN6,
    S_SGUN7,
    S_SGUN8,
    S_SGUN9,
    S_SGUNFLASH1,
    S_SGUNFLASH2,
    S_CHAIN,
    S_CHAINDOWN,
    S_CHAINUP,
    S_CHAIN1,
    S_CHAIN2,
    S_CHAIN3,
    S_CHAINFLASH1,
    S_CHAINFLASH2,
    S_MISSILE,
    S_MISSILEDOWN,
    S_MISSILEUP,
    S_MISSILE1,
    S_MISSILE2,
    S_MISSILE3,
    S_MISSILEFLASH1,
    S_MISSILEFLASH2,
    S_MISSILEFLASH3,
    S_MISSILEFLASH4,
    S_SAW,
    S_SAWB,
    S_SAWDOWN,
    S_SAWUP,
    S_SAW1,
    S_SAW2,
    S_SAW3,
    S_PLASMA,
    S_PLASMADOWN,
    S_PLASMAUP,
    S_PLASMA1,
    S_PLASMA2,
    S_PLASMAFLASH1,
    S_PLASMAFLASH2,
    S_BLOOD1,
    S_BLOOD2,
    S_BLOOD3,
    S_PUFF1,
    S_PUFF2,
    S_PUFF3,
    S_PUFF4,
    S_TBALL1,
    S_TBALL2,
    S_TBALLX1,
    S_TBALLX2,
    S_TBALLX3,
    S_RBALL1,
    S_RBALL2,
    S_RBALLX1,
    S_RBALLX2,
    S_RBALLX3,
    S_PLASBALL,
    S_PLASBALL2,
    S_PLASEXP,
    S_PLASEXP2,
    S_PLASEXP3,
    S_PLASEXP4,
    S_PLASEXP5,
    S_ROCKET,
    S_EXPLODE1,
    S_EXPLODE2,
    S_EXPLODE3,
    S_TFOG,
    S_TFOG01,
    S_TFOG02,
    S_TFOG2,
    S_TFOG3,
    S_TFOG4,
    S_TFOG5,
    S_TFOG6,
    S_TFOG7,
    S_TFOG8,
    S_TFOG9,
    S_TFOG10,
    S_IFOG,
    S_IFOG01,
    S_IFOG02,
    S_IFOG2,
    S_IFOG3,
    S_IFOG4,
    S_IFOG5,
    S_PLAY,
    S_PLAY_RUN1,
    S_PLAY_RUN2,
    S_PLAY_RUN3,
    S_PLAY_RUN4,
    S_PLAY_ATK1,
    S_PLAY_ATK2,
    S_PLAY_PAIN,
    S_PLAY_PAIN2,
    S_PLAY_DIE1,
    S_PLAY_DIE2,
    S_PLAY_DIE3,
    S_PLAY_DIE4,
    S_PLAY_DIE5,
    S_PLAY_DIE6,
    S_PLAY_DIE7,
    S_PLAY_XDIE1,
    S_PLAY_XDIE2,
    S_PLAY_XDIE3,
    S_PLAY_XDIE4,
    S_PLAY_XDIE5,
    S_PLAY_XDIE6,
    S_PLAY_XDIE7,
    S_PLAY_XDIE8,
    S_PLAY_XDIE9,
    S_POSS_STND,
    S_POSS_STND2,
    S_POSS_RUN1,
    S_POSS_RUN2,
    S_POSS_RUN3,
    S_POSS_RUN4,
    S_POSS_RUN5,
    S_POSS_RUN6,
    S_POSS_RUN7,
    S_POSS_RUN8,
    S_POSS_ATK1,
    S_POSS_ATK2,
    S_POSS_ATK3,
    S_POSS_PAIN,
    S_POSS_PAIN2,
    S_POSS_DIE1,
    S_POSS_DIE2,
    S_POSS_DIE3,
    S_POSS_DIE4,
    S_POSS_DIE5,
    S_POSS_XDIE1,
    S_POSS_XDIE2,
    S_POSS_XDIE3,
    S_POSS_XDIE4,
    S_POSS_XDIE5,
    S_POSS_XDIE6,
    S_POSS_XDIE7,
    S_POSS_XDIE8,
    S_POSS_XDIE9,
    S_SPOS_STND,
    S_SPOS_STND2,
    S_SPOS_RUN1,
    S_SPOS_RUN2,
    S_SPOS_RUN3,
    S_SPOS_RUN4,
    S_SPOS_RUN5,
    S_SPOS_RUN6,
    S_SPOS_RUN7,
    S_SPOS_RUN8,
    S_SPOS_ATK1,
    S_SPOS_ATK2,
    S_SPOS_ATK3,
    S_SPOS_PAIN,
    S_SPOS_PAIN2,
    S_SPOS_DIE1,
    S_SPOS_DIE2,
    S_SPOS_DIE3,
    S_SPOS_DIE4,
    S_SPOS_DIE5,
    S_SPOS_XDIE1,
    S_SPOS_XDIE2,
    S_SPOS_XDIE3,
    S_SPOS_XDIE4,
    S_SPOS_XDIE5,
    S_SPOS_XDIE6,
    S_SPOS_XDIE7,
    S_SPOS_XDIE8,
    S_SPOS_XDIE9,
    S_TROO_STND,
    S_TROO_STND2,
    S_TROO_RUN1,
    S_TROO_RUN2,
    S_TROO_RUN3,
    S_TROO_RUN4,
    S_TROO_RUN5,
    S_TROO_RUN6,
    S_TROO_RUN7,
    S_TROO_RUN8,
    S_TROO_ATK1,
    S_TROO_ATK2,
    S_TROO_ATK3,
    S_TROO_PAIN,
    S_TROO_PAIN2,
    S_TROO_DIE1,
    S_TROO_DIE2,
    S_TROO_DIE3,
    S_TROO_DIE4,
    S_TROO_DIE5,
    S_TROO_XDIE1,
    S_TROO_XDIE2,
    S_TROO_XDIE3,
    S_TROO_XDIE4,
    S_TROO_XDIE5,
    S_TROO_XDIE6,
    S_TROO_XDIE7,
    S_TROO_XDIE8,
    S_SARG_STND,
    S_SARG_STND2,
    S_SARG_RUN1,
    S_SARG_RUN2,
    S_SARG_RUN3,
    S_SARG_RUN4,
    S_SARG_RUN5,
    S_SARG_RUN6,
    S_SARG_RUN7,
    S_SARG_RUN8,
    S_SARG_ATK1,
    S_SARG_ATK2,
    S_SARG_ATK3,
    S_SARG_PAIN,
    S_SARG_PAIN2,
    S_SARG_DIE1,
    S_SARG_DIE2,
    S_SARG_DIE3,
    S_SARG_DIE4,
    S_SARG_DIE5,
    S_SARG_DIE6,
    S_HEAD_STND,
    S_HEAD_RUN1,
    S_HEAD_ATK1,
    S_HEAD_ATK2,
    S_HEAD_ATK3,
    S_HEAD_PAIN,
    S_HEAD_PAIN2,
    S_HEAD_PAIN3,
    S_HEAD_DIE1,
    S_HEAD_DIE2,
    S_HEAD_DIE3,
    S_HEAD_DIE4,
    S_HEAD_DIE5,
    S_HEAD_DIE6,
    S_BRBALL1,
    S_BRBALL2,
    S_BRBALLX1,
    S_BRBALLX2,
    S_BRBALLX3,
    S_BOSS_STND,
    S_BOSS_STND2,
    S_BOSS_RUN1,
    S_BOSS_RUN2,
    S_BOSS_RUN3,
    S_BOSS_RUN4,
    S_BOSS_RUN5,
    S_BOSS_RUN6,
    S_BOSS_RUN7,
    S_BOSS_RUN8,
    S_BOSS_ATK1,
    S_BOSS_ATK2,
    S_BOSS_ATK3,
    S_BOSS_PAIN,
    S_BOSS_PAIN2,
    S_BOSS_DIE1,
    S_BOSS_DIE2,
    S_BOSS_DIE3,
    S_BOSS_DIE4,
    S_BOSS_DIE5,
    S_BOSS_DIE6,
    S_BOSS_DIE7,
    S_SKULL_STND,
    S_SKULL_STND2,
    S_SKULL_RUN1,
    S_SKULL_RUN2,
    S_SKULL_ATK1,
    S_SKULL_ATK2,
    S_SKULL_ATK3,
    S_SKULL_ATK4,
    S_SKULL_PAIN,
    S_SKULL_PAIN2,
    S_SKULL_DIE1,
    S_SKULL_DIE2,
    S_SKULL_DIE3,
    S_SKULL_DIE4,
    S_SKULL_DIE5,
    S_SKULL_DIE6,
    S_ARM1,
    S_ARM1A,
    S_ARM2,
    S_ARM2A,
    S_BAR1,
    S_BAR2,
    S_BEXP,
    S_BEXP2,
    S_BEXP3,
    S_BEXP4,
    S_BEXP5,
    S_BON1,
    S_BON1A,
    S_BON1B,
    S_BON1C,
    S_BON1D,
    S_BON1E,
    S_BON2,
    S_BON2A,
    S_BON2B,
    S_BON2C,
    S_BON2D,
    S_BON2E,
    S_BKEY,
    S_BKEY2,
    S_RKEY,
    S_RKEY2,
    S_YKEY,
    S_YKEY2,
    S_BSKULL,
    S_BSKULL2,
    S_RSKULL,
    S_RSKULL2,
    S_YSKULL,
    S_YSKULL2,
    S_STIM,
    S_MEDI,
    S_SOUL,
    S_SOUL2,
    S_SOUL3,
    S_SOUL4,
    S_SOUL5,
    S_SOUL6,
    S_PINV,
    S_PINV2,
    S_PINV3,
    S_PINV4,
    S_PSTR,
    S_PINS,
    S_PINS2,
    S_PINS3,
    S_PINS4,
    S_SUIT,
    S_PMAP,
    S_PMAP2,
    S_PMAP3,
    S_PMAP4,
    S_PMAP5,
    S_PMAP6,
    S_PVIS,
    S_PVIS2,
    S_CLIP,
    S_AMMO,
    S_ROCK,
    S_BROK,
    S_CELL,
    S_CELP,
    S_SHEL,
    S_SBOX,
    S_BPAK,
    S_MGUN,
    S_CSAW,
    S_LAUN,
    S_PLAS,
    S_SHOT,
    S_COLU,
    S_BLOODYTWITCH,
    S_BLOODYTWITCH2,
    S_BLOODYTWITCH3,
    S_BLOODYTWITCH4,
    S_GIBS,
    S_LIVESTICK,
    S_LIVESTICK2,
    S_MEAT2,
    S_MEAT4,
    S_MEAT5,
    S_STALAGTITE,
    S_TALLGRNCOL,
    S_SHRTGRNCOL,
    S_TALLREDCOL,
    S_CANDLESTIK,
    S_CANDELABRA,
    S_TORCHTREE,
    S_BIGTREE,
    S_TECHPILLAR,
    S_FLOATSKULL,
    S_FLOATSKULL2,
    S_FLOATSKULL3,
    S_HEARTCOL,
    S_HEARTCOL2,
    S_BLUETORCH,
    S_BLUETORCH2,
    S_BLUETORCH3,
    S_BLUETORCH4,
    S_GREENTORCH,
    S_GREENTORCH2,
    S_GREENTORCH3,
    S_GREENTORCH4,
    S_REDTORCH,
    S_REDTORCH2,
    S_REDTORCH3,
    S_REDTORCH4,
    S_BTORCHSHRT,
    S_BTORCHSHRT2,
    S_BTORCHSHRT3,
    S_BTORCHSHRT4,
    S_GTORCHSHRT,
    S_GTORCHSHRT2,
    S_GTORCHSHRT3,
    S_GTORCHSHRT4,
    S_RTORCHSHRT,
    S_RTORCHSHRT2,
    S_RTORCHSHRT3,
    S_RTORCHSHRT4,
};

#define NUMMOBJTYPES 90
enum {
    MT_PLAYER,
    MT_POSSESSED,
    MT_SHOTGUY,
    MT_TROOP,
    MT_SERGEANT,
    MT_SHADOWS,
    MT_HEAD,
    MT_BRUISER,
    MT_BRUISERSHOT,
    MT_SKULL,
    MT_BARREL,
    MT_TROOPSHOT,
    MT_HEADSHOT,
    MT_ROCKET,
    MT_PLASMA,
    MT_PUFF,
    MT_BLOOD,
    MT_TFOG,
    MT_IFOG,
    MT_TELEPORTMAN,
    MT_MISC0,
    MT_MISC1,
    MT_MISC2,
    MT_MISC3,
    MT_MISC4,
    MT_MISC5,
    MT_MISC6,
    MT_MISC7,
    MT_MISC8,
    MT_MISC9,
    MT_MISC10,
    MT_MISC11,
    MT_MISC12,
    MT_INV,
    MT_MISC13,
    MT_INS,
    MT_MISC14,
    MT_MISC15,
    MT_MISC16,
    MT_CLIP,
    MT_MISC17,
    MT_MISC18,
    MT_MISC19,
    MT_MISC20,
    MT_MISC21,
    MT_MISC22,
    MT_MISC23,
    MT_MISC24,
    MT_CHAINGUN,
    MT_MISC26,
    MT_MISC27,
    MT_MISC28,
    MT_SHOTGUN,
    MT_MISC31,
    MT_MISC32,
    MT_MISC33,
    MT_MISC34,
    MT_MISC37,
    MT_MISC39,
    MT_MISC40,
    MT_MISC41,
    MT_MISC42,
    MT_MISC43,
    MT_MISC44,
    MT_MISC45,
    MT_MISC46,
    MT_MISC47,
    MT_MISC48,
    MT_MISC49,
    MT_MISC50,
    MT_MISC51,
    MT_MISC52,
    MT_MISC54,
    MT_MISC55,
    MT_MISC56,
    MT_MISC57,
    MT_MISC59,
    MT_MISC60,
    MT_MISC61,
    MT_MISC62,
    MT_MISC63,
    MT_MISC64,
    MT_MISC65,
    MT_MISC66,
    MT_MISC67,
    MT_MISC68,
    MT_MISC69,
    MT_MISC71,
    MT_MISC75,
    MT_MISC76,
};

#define NUMSFX 109
enum {
    sfx_None,
    sfx_pistol,
    sfx_shotgn,
    sfx_sgcock,
    sfx_dshtgn,
    sfx_dbopn,
    sfx_dbcls,
    sfx_dbload,
    sfx_plasma,
    sfx_bfg,
    sfx_sawup,
    sfx_sawidl,
    sfx_sawful,
    sfx_sawhit,
    sfx_rlaunc,
    sfx_rxplod,
    sfx_firsht,
    sfx_firxpl,
    sfx_pstart,
    sfx_pstop,
    sfx_doropn,
    sfx_dorcls,
    sfx_stnmov,
    sfx_swtchn,
    sfx_swtchx,
    sfx_plpain,
    sfx_dmpain,
    sfx_popain,
    sfx_vipain,
    sfx_mnpain,
    sfx_pepain,
    sfx_slop,
    sfx_itemup,
    sfx_wpnup,
    sfx_oof,
    sfx_telept,
    sfx_posit1,
    sfx_posit2,
    sfx_posit3,
    sfx_bgsit1,
    sfx_bgsit2,
    sfx_sgtsit,
    sfx_cacsit,
    sfx_brssit,
    sfx_cybsit,
    sfx_spisit,
    sfx_bspsit,
    sfx_kntsit,
    sfx_vilsit,
    sfx_mansit,
    sfx_pesit,
    sfx_sklatk,
    sfx_sgtatk,
    sfx_skepch,
    sfx_vilatk,
    sfx_claw,
    sfx_skeswg,
    sfx_pldeth,
    sfx_pdiehi,
    sfx_podth1,
    sfx_podth2,
    sfx_podth3,
    sfx_bgdth1,
    sfx_bgdth2,
    sfx_sgtdth,
    sfx_cacdth,
    sfx_skldth,
    sfx_brsdth,
    sfx_cybdth,
    sfx_spidth,
    sfx_bspdth,
    sfx_vildth,
    sfx_kntdth,
    sfx_pedth,
    sfx_skedth,
    sfx_posact,
    sfx_bgact,
    sfx_dmact,
    sfx_bspact,
    sfx_bspwlk,
    sfx_vilact,
    sfx_noway,
    sfx_barexp,
    sfx_punch,
    sfx_hoof,
    sfx_metal,
    sfx_chgun,
    sfx_tink,
    sfx_bdopn,
    sfx_bdcls,
    sfx_itmbk,
    sfx_flame,
    sfx_flamst,
    sfx_getpow,
    sfx_bospit,
    sfx_boscub,
    sfx_bossit,
    sfx_bospn,
    sfx_bosdth,
    sfx_manatk,
    sfx_mandth,
    sfx_sssit,
    sfx_ssdth,
    sfx_keenpn,
    sfx_keendt,
    sfx_skeact,
    sfx_skesit,
    sfx_skeatk,
    sfx_radio,
};

#define NUMACTIONS 33
#define AC_FIRST_WEAPON 18  /* AC_ numbers from here are weapon actions */
enum {
    AC_NONE,
    AC_Look,
    AC_Chase,
    AC_FaceTarget,
    AC_PosAttack,
    AC_SPosAttack,
    AC_TroopAttack,
    AC_SargAttack,
    AC_HeadAttack,
    AC_BruisAttack,
    AC_SkullAttack,
    AC_Scream,
    AC_XScream,
    AC_Pain,
    AC_Fall,
    AC_Explode,
    AC_BossDeath,
    AC_PlayerScream,
    AC_Light0,
    AC_WeaponReady,
    AC_Lower,
    AC_Raise,
    AC_Punch,
    AC_ReFire,
    AC_FirePistol,
    AC_Light1,
    AC_FireShotgun,
    AC_Light2,
    AC_FireCGun,
    AC_GunFlash,
    AC_FireMissile,
    AC_Saw,
    AC_FirePlasma,
};

/* mobj flags (vanilla's MF_ values); MF_x_B is the byte of the flag
 * word that holds it and MF_x_M its mask in that byte, for FLAG() */
#define MF_SPECIAL        0x00000001UL
#define MF_SPECIAL_B 0
#define MF_SPECIAL_M 0x01
#define MF_SOLID          0x00000002UL
#define MF_SOLID_B 0
#define MF_SOLID_M 0x02
#define MF_SHOOTABLE      0x00000004UL
#define MF_SHOOTABLE_B 0
#define MF_SHOOTABLE_M 0x04
#define MF_NOSECTOR       0x00000008UL
#define MF_NOSECTOR_B 0
#define MF_NOSECTOR_M 0x08
#define MF_NOBLOCKMAP     0x00000010UL
#define MF_NOBLOCKMAP_B 0
#define MF_NOBLOCKMAP_M 0x10
#define MF_AMBUSH         0x00000020UL
#define MF_AMBUSH_B 0
#define MF_AMBUSH_M 0x20
#define MF_JUSTHIT        0x00000040UL
#define MF_JUSTHIT_B 0
#define MF_JUSTHIT_M 0x40
#define MF_JUSTATTACKED   0x00000080UL
#define MF_JUSTATTACKED_B 0
#define MF_JUSTATTACKED_M 0x80
#define MF_SPAWNCEILING   0x00000100UL
#define MF_SPAWNCEILING_B 1
#define MF_SPAWNCEILING_M 0x01
#define MF_NOGRAVITY      0x00000200UL
#define MF_NOGRAVITY_B 1
#define MF_NOGRAVITY_M 0x02
#define MF_DROPOFF        0x00000400UL
#define MF_DROPOFF_B 1
#define MF_DROPOFF_M 0x04
#define MF_PICKUP         0x00000800UL
#define MF_PICKUP_B 1
#define MF_PICKUP_M 0x08
#define MF_NOCLIP         0x00001000UL
#define MF_NOCLIP_B 1
#define MF_NOCLIP_M 0x10
#define MF_SLIDE          0x00002000UL
#define MF_SLIDE_B 1
#define MF_SLIDE_M 0x20
#define MF_FLOAT          0x00004000UL
#define MF_FLOAT_B 1
#define MF_FLOAT_M 0x40
#define MF_TELEPORT       0x00008000UL
#define MF_TELEPORT_B 1
#define MF_TELEPORT_M 0x80
#define MF_MISSILE        0x00010000UL
#define MF_MISSILE_B 2
#define MF_MISSILE_M 0x01
#define MF_DROPPED        0x00020000UL
#define MF_DROPPED_B 2
#define MF_DROPPED_M 0x02
#define MF_SHADOW         0x00040000UL
#define MF_SHADOW_B 2
#define MF_SHADOW_M 0x04
#define MF_NOBLOOD        0x00080000UL
#define MF_NOBLOOD_B 2
#define MF_NOBLOOD_M 0x08
#define MF_CORPSE         0x00100000UL
#define MF_CORPSE_B 2
#define MF_CORPSE_M 0x10
#define MF_INFLOAT        0x00200000UL
#define MF_INFLOAT_B 2
#define MF_INFLOAT_M 0x20
#define MF_COUNTKILL      0x00400000UL
#define MF_COUNTKILL_B 2
#define MF_COUNTKILL_M 0x40
#define MF_COUNTITEM      0x00800000UL
#define MF_COUNTITEM_B 2
#define MF_COUNTITEM_M 0x80
#define MF_SKULLFLY       0x01000000UL
#define MF_SKULLFLY_B 3
#define MF_SKULLFLY_M 0x01
#define MF_NOTDMATCH      0x02000000UL
#define MF_NOTDMATCH_B 3
#define MF_NOTDMATCH_M 0x02

/* One thing type, 32 bytes (vanilla's mobjinfo_t without doomednum and
 * raisestate). radius, height and speed are map units; a missile's speed
 * is (fixed_t)speed << FRACBITS. painchance is 16 bits: the lost soul's
 * 256 means always. */
typedef struct {
    uint16_t spawnstate, seestate, painstate, meleestate;
    uint16_t missilestate, deathstate, xdeathstate;
    int16_t  spawnhealth;
    uint16_t painchance;
    uint16_t mass;
    uint32_t flags;
    uint8_t  seesound, attacksound, painsound, deathsound, activesound;
    uint8_t  reactiontime, speed, radius, height, damage;
} mobjinfo_t;

extern const mobjinfo_t mobjinfo[NUMMOBJTYPES];
extern const int16_t mi_doomednum[NUMMOBJTYPES];   /* -1: not placed in maps */

/* the states, one byte plane per field */
extern const uint8_t  st_sprite[NUMSTATES];   /* SPR_ number (doomdata.h) */
extern const uint8_t  st_frame[NUMSTATES];    /* frame letter index, bit 7 full bright */
extern const uint8_t  st_tics[NUMSTATES];     /* 255 = forever (vanilla -1) */
extern const uint8_t  st_action[NUMSTATES];   /* AC_*, bit 7: quiet from here on */
extern const uint16_t st_next[NUMSTATES];
#define ST_FOREVER 255

/* vanilla's rndtable (m_random.c) */
extern const uint8_t rndtable[256];

/* the action tables (info.c): AC_ numbers below AC_FIRST_WEAPON call
 * mobj_actions[n](mobj), the others weapon_actions[n - AC_FIRST_WEAPON]
 * (player, psp) */
struct mobj_s;
struct player_s;
struct pspdef_s;
typedef void (*mobjaction_t)(struct mobj_s *);
typedef void (*weaponaction_t)(struct player_s *, struct pspdef_s *);
extern const mobjaction_t mobj_actions[AC_FIRST_WEAPON];
extern const weaponaction_t weapon_actions[NUMACTIONS - AC_FIRST_WEAPON];

void A_Look(struct mobj_s *actor);
void A_Chase(struct mobj_s *actor);
void A_FaceTarget(struct mobj_s *actor);
void A_PosAttack(struct mobj_s *actor);
void A_SPosAttack(struct mobj_s *actor);
void A_TroopAttack(struct mobj_s *actor);
void A_SargAttack(struct mobj_s *actor);
void A_HeadAttack(struct mobj_s *actor);
void A_BruisAttack(struct mobj_s *actor);
void A_SkullAttack(struct mobj_s *actor);
void A_Scream(struct mobj_s *actor);
void A_XScream(struct mobj_s *actor);
void A_Pain(struct mobj_s *actor);
void A_Fall(struct mobj_s *actor);
void A_Explode(struct mobj_s *actor);
void A_BossDeath(struct mobj_s *actor);
void A_PlayerScream(struct mobj_s *actor);
void A_Light0(struct player_s *player, struct pspdef_s *psp);
void A_WeaponReady(struct player_s *player, struct pspdef_s *psp);
void A_Lower(struct player_s *player, struct pspdef_s *psp);
void A_Raise(struct player_s *player, struct pspdef_s *psp);
void A_Punch(struct player_s *player, struct pspdef_s *psp);
void A_ReFire(struct player_s *player, struct pspdef_s *psp);
void A_FirePistol(struct player_s *player, struct pspdef_s *psp);
void A_Light1(struct player_s *player, struct pspdef_s *psp);
void A_FireShotgun(struct player_s *player, struct pspdef_s *psp);
void A_Light2(struct player_s *player, struct pspdef_s *psp);
void A_FireCGun(struct player_s *player, struct pspdef_s *psp);
void A_GunFlash(struct player_s *player, struct pspdef_s *psp);
void A_FireMissile(struct player_s *player, struct pspdef_s *psp);
void A_Saw(struct player_s *player, struct pspdef_s *psp);
void A_FirePlasma(struct player_s *player, struct pspdef_s *psp);

#endif
